Move TokensMoveDialog components from admin to dashboard
JoinColony/colonyDapp pull request #2300
Opened 2020-11-25 15:10 UTC by ArmandoGraterol

## Description

This PR updates styles of the TokensMoveDialog and adds a new field to it.

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves DEV-18

2020-11-25 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=2300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=2300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=2300) it.</sub>

2020-11-26 09:14 UTC, alicjakujawa commented on src/modules/admin/components/Tokens/Tokens.tsx
> +import TransferFundsDialog from '../../../dashboard/components/TransferFundsDialog';
```suggestion
'~dashboard/TransferFundsDialog'```
Should work fine

2020-11-26 09:17 UTC, alicjakujawa commented on src/modules/admin/components/Tokens/index.ts
> +export { default as TransferFundsDialog } from '../../../dashboard/components/TransferFundsDialog';
Not sure why we exporting it here 🤔  @rdig What was the reason for those exports ealier?

2020-11-26 09:20 UTC, alicjakujawa commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +    return [from];
if we returning just one value, should we just return from? and replace 
const [fromDomainTokenBalance]= with just 
const fromDomainTokenBalance=

2020-11-26 09:38 UTC, alicjakujawa commented
Tests locally, there are some minor difference between design and implementation i noticed:
1 - the line, which is below "Amount" should be a bit higher:
<img width="402" alt="Screenshot 2020-11-26 at 10 35 45" src="https://user-images.githubusercontent.com/13069555/100333663-2a58ce00-2fd3-11eb-8979-c6a532b8cbc7.png">
2 - Label text should be in different color, should be fine if you change to:
              appearance={{
                    colorSchema: 'grey',
                  }}
3. Top padding of modal should be bigger, but i added this change in my PR, so after it will be merge we should apply this to all modals, as it seems to be change for all of them. (36px padding vs current 30px)

2020-11-26 09:39 UTC, alicjakujawa requested changes
Minor things/questions to change 🔥

2020-11-26 13:02 UTC, rdig requested changes
Overall a decent first issue. I've noted the things I've picked up in terms of specs mis-alignments.

Please note that in the case of namespacing, while I just noted one of the entries, the change needs to be applied globally to the file.

:+1:

2020-11-26 13:02 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +                <FormattedMessage
In general all the fonts on this modal are too small. Please follow the spec on figma for proper font sizing.

For example, in this case:
![Screenshot from 2020-11-26 14-43-34](https://user-images.githubusercontent.com/1193222/100354022-22f7eb80-2ff8-11eb-8cc0-3ab1264120af.png)

Your
![Screenshot from 2020-11-26 14-43-53](https://user-images.githubusercontent.com/1193222/100354060-2ee3ad80-2ff8-11eb-9729-281ab2f9b416.png)
 font size is `12px` while the spec requires it to be `13px`

2020-11-26 13:03 UTC, rdig commented
@alicjakujawa @ArmandoGraterol regarding:

> 1 - the line, which is below "Amount" should be a bit higher:

No, leave it like it is. I consider the spec to be wrong in this case

2020-11-26 14:44 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +          appearance={{ theme: 'fat', resizable: 'vertical' }}
Please add the `grey` color schma here:
```suggestion
          appearance={{ theme: 'fat', resizable: 'vertical', colorSchema: 'grey' }}
```

2020-11-26 14:45 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +          appearance={{ theme: 'fat', resizable: 'vertical' }}
Also do the same for the other input on the page :+1:

2020-11-27 06:12 UTC, alicjakujawa commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
> +  font-size: 18px;
we have var for it -  --size-medium-l 🙈

2020-11-27 06:12 UTC, alicjakujawa commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
> +  font-size: 13px;
--size-smallish

2020-11-27 12:44 UTC, rdig requested changes
Overall pretty good, you fixed most of the issues found in the first round of reviews.

I've found some other minor discrepancies plus there are Alicja's notes.

Once you change those, this will be good to go.

2020-11-27 12:44 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +            title="Transfer"
titles need to be message descriptors as well

2020-11-27 12:44 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +                colorSchema: 'grey',
Sorry if I made myself misunderstood, but this should have just been applied to the two select components and the one textarea.

The way you implemented it initially was correct:

![Screenshot from 2020-11-27 14-30-47](https://user-images.githubusercontent.com/1193222/100449795-3620bf00-30bd-11eb-81b4-91714c5d8481.png)

Just remove the `colorSchema` from here, and we're all good.

2020-11-27 12:44 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
> +  & svg {
While this is technically possible currently via our webpack loaders, future updates might break it.

Please move it to a new class declaration. Something like:
```js
.transferIcon svg {
  fill: var(--temp-grey-blue-7);
}
```

2020-11-27 12:44 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +          <Textarea
Please add a character limit of `4000` to this textarea, sorry I missed it the first time around.

You can do this by passing the `maxLength` prop.

Eg:
```
maxLength={4000}
```

2020-11-30 18:10 UTC, rdig approved these changes
This looks good.

I found another place where you need to put a variable, but other than that this is good to go.

I'm pre-approving this, so after you fix the variable, you can merge it.

Congrats on your first PR! :100:

2020-11-30 18:10 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
> +  font-weight: 600;
`var(--weight-bold)`

2020-11-30 18:10 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +                        value={fromDomainTokenBalance || 0}
The default value could have been put inside the `useMemo` hook, but I guess this is fine as well

2020-12-01 06:02 UTC, merged