Transfer Funds Action Wiring
JoinColony/colonyDapp pull request #2327
Opened 2020-12-14 16:18 UTC by rdig

## Description

This PR wires up the _"Move Funds"_ flow that creates a new action from moving funds, inside a colony from a domain to the other.

**Changes** 

- [x] Added `MoveFunds` action `ColonyActions` type
- [ ] ...

**Demo**

_tba_

Resolves DEV-64

2020-12-16 17:02 UTC, alicjakujawa requested changes
So there are small design issues still here - too big spaces between header and "You need the following permission(s)" label, and at the bottom between message about permissions required - see screenshots. Also "x" doesn't look like the one from designs - Of course we can create issue for those design adjustment if you prefer.
Another problem is about modal - on my computer im not able to see full dialog see screenshots, but again this should be address as separate issue.
<img width="560" alt="1" src="https://user-images.githubusercontent.com/13069555/102380828-b35a9800-3fc8-11eb-83f4-0d1419dfd28b.png">
<img width="547" alt="2" src="https://user-images.githubusercontent.com/13069555/102380834-b48bc500-3fc8-11eb-933c-f6e6c6b502c0.png">
<img width="591" alt="3" src="https://user-images.githubusercontent.com/13069555/102380835-b5245b80-3fc8-11eb-83fd-af949b27a62e.png">

The only thing which is important - confirm button is enable if im sending from domain without funds - see screenshot

<img width="734" alt="Screenshot 2020-12-16 at 17 53 08" src="https://user-images.githubusercontent.com/13069555/102380957-e735bd80-3fc8-11eb-983b-f080779baea5.png">

2020-12-17 09:26 UTC, rdig commented
> So there are small design issues still here - too big spaces between header and "You need the following permission(s)" label, and at the bottom between message about permissions required - see screenshots. Also "x" doesn't look like the one from designs - Of course we can create issue for those design adjustment if you prefer.

I just used the standard core components, didn't really cared too much about styles. But I can look into it if you want me to.

2020-12-17 09:27 UTC, alicjakujawa commented
> > So there are small design issues still here - too big spaces between header and "You need the following permission(s)" label, and at the bottom between message about permissions required - see screenshots. Also "x" doesn't look like the one from designs - Of course we can create issue for those design adjustment if you prefer.
> 
> I just used the standard core components, didn't really cared too much about styles. But I can look into it if you want me to.

I mean we can just create task for improving styles if we want stick to designs

2020-12-17 09:28 UTC, rdig commented on src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
> +      submit={ActionTypes.COLONY_ACTION_GENERIC} // @TODO: Add in correct ActionTypes
I know them, I just don't want to wire them into this branch as well.

It'll be something like: `COLONY_ACTION_RECOVERY_UPDATE_STORAGE_SLOT` 

But that's to be done in DEV-75

For now I just needed some redux actions that exist, in order to make `eslint` stop complaining.

2020-12-17 09:29 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +    : undefined;
I need this to be explicitly `undefined`, if I use your suggested change it will end up being `false` if `toDomain` doesn't exist.

2020-12-17 09:31 UTC, rdig commented on src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
> +    return undefined;
I need to return _something_ to make `eslint` happy, It really doesn't matter what. And I prefere returning something like:
`return undefined;` or `return null;` as opposed of just an undeclared return `return;`

2020-12-17 09:31 UTC, rdig commented on src/modules/dashboard/sagas/actions.ts
> +      // payload: { colonyAddress, tokenAddress, fromPot, toPot, amount },
Good catch, it's a leftover that needs to be removed.

2020-12-17 09:32 UTC, rdig commented
> Another problem is about modal - on my computer im not able to see full dialog see screenshots, but again this should be address as separate issue.

We really need to find a good solution for this. Maybe in DEV-118 ?

2020-12-17 09:36 UTC, alicjakujawa commented
> > Another problem is about modal - on my computer im not able to see full dialog see screenshots, but again this should be address as separate issue.
> 
> We really need to find a good solution for this. Maybe in DEV-118 ?

Yes it would fits there great

2020-12-17 10:44 UTC, rdig commented
> The only thing which is important - confirm button is enable if im sending from domain without funds - see screenshot
> <Image ... />

How did you get into that state? I cannot replicate it:

![Screenshot from 2020-12-17 12-44-09](https://user-images.githubusercontent.com/1193222/102477905-a475f300-4065-11eb-81b8-a678f0010708.png)

2020-12-17 11:11 UTC, rdig commented
@alicjakujawa 
- updated error messages alignments
- improved the way available funds / select errors overlap with each other
- removed commented out code

Ready for another look-over

2020-12-17 12:09 UTC, alicjakujawa commented
<img width="781" alt="Screenshot 2020-12-17 at 13 07 25" src="https://user-images.githubusercontent.com/13069555/102486161-e81e2c00-4068-11eb-8853-bf77f811d34e.png">
@rdig So, i Select set "from" to domain without funds, set to - to root domain (at this point confirm was disabled) BUT when i type to input value, confirm button was enable again

2020-12-17 18:24 UTC, ArmandoGraterol approved these changes
It's lit, it's lit :fire::ok_hand:

2020-12-18 14:32 UTC, rdig commented
@alicjakujawa Still can't replicate your issue. Here's a demo of my following the steps you described:

![demo-move-funds-insufficient-pot](https://user-images.githubusercontent.com/1193222/102625654-77e9d600-414e-11eb-8ee9-bed076d8c5de.gif)

Are you sure you are using the latest commit from the branch?

I can investigate further, but without a proper case to replicate it's going to be very hard.

2020-12-18 14:43 UTC, rdig commented
@alicjakujawa I've refactored the way that modal is validated. Not it validates:
- on mount
- on every domain change -- both from and to
- on amount change

Please pull the latest code and test it again locally.

Thanks :+1:

2020-12-18 15:09 UTC, alicjakujawa approved these changes
Dont know, what you changed but now is working fine 🔥

2020-12-21 19:37 UTC, merged