Removed ActivityFeed
JoinColony/colonyDapp pull request #2332
Opened 2020-12-15 19:01 UTC by ArmandoGraterol

Removed ActivityFeed core component because it's no longer necessary

Resolves DEV-24

2020-12-16 08:39 UTC, alicjakujawa requested changes
Looks good to me, the only thing i feel we're missing is removing ActivityFeedItem.ts where types are define, but i can be wrong. @rdig

2020-12-16 09:23 UTC, rdig requested changes
Mostly good, but there are some leftovers.

Please also remove the `ActivityFeed` types and mentions from `immutable`
- https://github.com/JoinColony/colonyDapp/blob/9c75ef27f2f561034591547e0d86302f66e1b0d0/src/immutable/ActivityFeedItem.ts
- https://github.com/JoinColony/colonyDapp/blob/9c75ef27f2f561034591547e0d86302f66e1b0d0/src/immutable/index.ts#L3
- https://github.com/JoinColony/colonyDapp/blob/9c75ef27f2f561034591547e0d86302f66e1b0d0/src/immutable/Using-Immutable.md#L34-74

2020-12-16 13:47 UTC, alicjakujawa approved these changes

2020-12-17 09:19 UTC, rdig approved these changes
LGTM: :+1:

2020-12-17 14:04 UTC, merged