Wire Create Domains Flow
JoinColony/colonyDapp pull request #2348
Opened 2021-01-13 13:10 UTC by rdig

## Description

This PR wires in the domain create action in the UAC flow. This presents a couple of challenges:
- adding the action itself
- uploading metadata to ipfs
- reading that ipfs metadata in the action
- adding annotations
- wiring in the subgraph action itself

**Changes**

- [x] Added Redux Domain Create Actions
- [x] Removed old Redux Domain Create 

**Demo**

_tba_

Resolves DEV-68

2021-01-19 19:43 UTC, ArmandoGraterol requested changes
After reading this chunky PR, I have become enlightened :lotus_position_man: 

I only noticed some small things. Tested it and it working great for me :ok_hand:

2021-01-19 19:43 UTC, ArmandoGraterol commented on src/modules/dashboard/components/ManageDomainsDialog/ManageDomainsDialog.tsx
> +      'Domains, departments, circles: teams let you froup types of activity.',
Typo here: `froup`

2021-01-19 20:24 UTC, rdig commented on src/data/graphql/typeDefs.ts
>      description: String
Yes. Good catch

2021-01-21 17:04 UTC, rdig commented
Fixed the last review issues, rebased (plus added a couple of small fixes I've noticed after the rebase -- actions list sorting was not working)

So @JoinColony/frontend I'd appreciate another review :)

2021-01-22 21:30 UTC, ArmandoGraterol approved these changes
Tested it again, still working as expected :ok_hand: It's lit

2021-01-23 11:54 UTC, merged