Coin Machine Navigation, Routes, Layout and Grid
JoinColony/colonyDapp pull request #2444
Opened 2021-04-17 19:58 UTC by rdig

## Description

This PR adds in the initial stages of the Coin Machine component, and sets up the grid layout, as well as wiring up the route and navigation logic for it _(based on if the extension is enabled or not)_

* New stuff goes here

**Changes** 
- [x] Added coin machine route
- [x] Wired up coin machine route
- [x] Wired up `CoinMachine` within the `ColonyHome` layout
- [x] Added `CoinMachine` component

**Demo**
_tba_

Resolves DEV-297

2021-04-20 14:29 UTC, alicjakujawa requested changes
<img width="1071" alt="Screenshot 2021-04-20 at 16 26 46" src="https://user-images.githubusercontent.com/13069555/115413178-4284f000-a1f5-11eb-9dd4-3d9c3ea955a0.png">
From first look i see a few small issues:
* space on the right side should be bigger (distance between last column and screen)
* Color of titles should be --dark
* I think we also miss box-shadow on columns

2021-04-20 14:34 UTC, rdig commented
@alicjakujawa 

> From first look i see a few small issues: * space on the right side should be bigger (distance between last column and screen) * Color of titles should be --dark * I think we also miss box-shadow on columns

> "space on the right side should be bigger"
Please be more specific about the, I don't quite understand

> Color of titles should be --dark 
We don't have titles, they are placeholders -- see the comment about removing that element / css class. The actual styles will come in each widget's PR

> miss box-shadow on columns
You are correct. I noticed this while working on #2445, so you can consider this fixed as well, since it will be added by that

2021-04-20 16:15 UTC, alicjakujawa commented
> <img alt="Screenshot 2021-04-20 at 16 26 46" width="1071" src="https://user-images.githubusercontent.com/13069555/115413178-4284f000-a1f5-11eb-9dd4-3d9c3ea955a0.png">
> 
> From first look i see a few small issues: * space on the right side should be bigger (distance between last column and screen) * Color of titles should be --dark * I think we also miss box-shadow on columns

<img width="1071" alt="115413178-4284f000-a1f5-11eb-9dd4-3d9c3ea955a0" src="https://user-images.githubusercontent.com/13069555/115430159-6865c100-a204-11eb-8bd1-b706288c9011.png">

2021-04-21 11:13 UTC, alicjakujawa approved these changes

2021-04-21 12:31 UTC, merged