Motions and Disputes Reveal Vote Widget
JoinColony/colonyDapp pull request #2447
Opened 2021-04-19 19:23 UTC by rdig

## Description

This PR adds in the voting reveal widget to the motion page, but does not wire in the saga

This widget has two states:
1. vote was not revealed yet, just show a info message
2. vote was revealed, show the user's vote

**Changes** 
- [x] Extract `VoteDetails` into separate component
- [x] Added `RevealWidget` Component
- [x] Added `motionUserVoteRevealed` client resolver
- [x] Added `MotionVote` enum type
- [x] Fixed `getMotionState` util

**Demo**
![demo-md-reveal-widget-1](https://user-images.githubusercontent.com/1193222/115291719-c2f81200-a15d-11eb-974a-6cd533a1cbba.gif)
![demo-md-reveal-widget-2](https://user-images.githubusercontent.com/1193222/115291724-c390a880-a15d-11eb-88f8-5772690bc771.gif)
![demo-md-reveal-widget-3](https://user-images.githubusercontent.com/1193222/115291725-c4293f00-a15d-11eb-9fec-c69eded0e48a.gif)

Resolves DEV-288

2021-04-20 12:51 UTC, alicjakujawa requested changes
Add handling the state, when user join to colony when motion was already in reveal state. (disable or hide reveal widget)

2021-04-20 17:46 UTC, rdig commented on src/utils/colonyMotions.ts
> +  Nay = 2,
Lol! Nay is 0, not 2!

Please remember to fix this!

2021-04-21 11:05 UTC, alicjakujawa approved these changes
Just reminder:
* star alignment
* disable vote button

2021-04-21 13:55 UTC, rdig commented
@alicjakujawa 

1. Disabled voting if the user doesn't have enough reputation

![Screenshot from 2021-04-21 16-52-12](https://user-images.githubusercontent.com/1193222/115565720-4a5e9600-a2c2-11eb-90ac-775aadec703f.png)

2. Properly aligned the reputation display icon (star)

![Screenshot from 2021-04-21 16-49-22](https://user-images.githubusercontent.com/1193222/115565773-577b8500-a2c2-11eb-9e77-800b96368e01.png)

2021-04-21 14:10 UTC, merged