Use moveDecimal to display stake rewards
JoinColony/colonyDapp pull request #2469
Opened 2021-04-29 17:34 UTC by ArmandoGraterol

## Description

- Use moveDecimal to convert stake rewards instead of directly using Numeral

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

Resolves DEV-314

2021-05-03 10:03 UTC, chinins reviewed
It looks not as per specs any more - too many digits after coma:
<img width="404" alt="Screenshot 2021-05-03 at 11 53 34" src="https://user-images.githubusercontent.com/34057551/116864059-26268180-abff-11eb-8ecf-ddd5f4d74476.png">

This is how it looks on the main feature branch before the changes
<img width="420" alt="Screenshot 2021-05-03 at 11 59 53" src="https://user-images.githubusercontent.com/34057551/116864099-39395180-abff-11eb-8833-6a865e3c7602.png">

2021-05-03 10:10 UTC, chinins commented
Also I've noticed this displayed incorrectly. Maybe you haven't rebased yet? Something to make sure is correct before merging in any case.
<img width="508" alt="Screenshot 2021-05-03 at 12 09 32" src="https://user-images.githubusercontent.com/34057551/116864616-0ba0d800-ac00-11eb-9dc5-44bf892b6676.png">

2021-05-03 12:12 UTC, rdig requested changes
Sorry for butting it, but...

The refactor in here also involves showing the "correct", even if negative value, winnings, so that the user knows if they won or lost.

So, as per Olga's example, 

- Stake should display as 1083.94 A
- Winnings should display as **−541.97 A**
- Totals should display as 541.97 A

2021-05-03 13:44 UTC, ArmandoGraterol commented
> Sorry for butting it, but...
> 
> The refactor in here also involves showing the "correct", even if negative value, winnings, so that the user knows if they won or lost.
> 
> So, as per Olga's example,
> 
> * Stake should display as 1083.94 A
> * Winnings should display as **−541.97 A**
> * Totals should display as 541.97 A

Oooh, I see. Yeah, that makes sense! Thank you for the example

2021-05-03 14:30 UTC, ArmandoGraterol commented
> It looks not as per specs any more - too many digits after coma:
> <img alt="Screenshot 2021-05-03 at 11 53 34" width="404" src="https://user-images.githubusercontent.com/34057551/116864059-26268180-abff-11eb-8ecf-ddd5f4d74476.png">
> 
> This is how it looks on the main feature branch before the changes
> <img alt="Screenshot 2021-05-03 at 11 59 53" width="420" src="https://user-images.githubusercontent.com/34057551/116864099-39395180-abff-11eb-8833-6a865e3c7602.png">

From what I understand from reading the description of this task...

The idea is to better display low reward values (0.000000…), I would say it's like the `Reward` of the `VoteDetails`:

![FireShot Capture 266 - Colony - localhost](https://user-images.githubusercontent.com/18473896/116888998-7b17c700-ac02-11eb-8a79-7b2f03de46c8.png)

As you can see, the reward there is showing lots of decimals

And the other purpose of this PR is to display negative reward values like Raul already mentioned.

Perhaps I misunderstood the task, let me know what you think

2021-05-18 12:51 UTC, alicjakujawa requested changes
<img width="495" alt="Screenshot 2021-05-18 at 14 49 40" src="https://user-images.githubusercontent.com/13069555/118653919-50279880-b7e8-11eb-9b3c-82b440169ca0.png">
1. I staked and i won. Why it shows total 0? and why it shows negative value for Winnings ? 🤔 
2. I would actually show only 5 sig after comma, currently its too much. Why 5? Product already mentioned for other things related to values to show 5 sig dig

2021-05-18 13:20 UTC, ArmandoGraterol commented
> <img alt="Screenshot 2021-05-18 at 14 49 40" width="495" src="https://user-images.githubusercontent.com/13069555/118653919-50279880-b7e8-11eb-9b3c-82b440169ca0.png">
> 
> 1. I staked and i won. Why it shows total 0? and why it shows negative value for Winnings ?  2. I would actually show only 5 sig after comma, currently its too much. Why 5? Product already mentioned for other things related to values to show 5 sig dig

1. Did you stake the motion and the objection with 1 user by any chance? If that's the case, then it makes sense to me that your winnings are in the negative and the total is 0

2. Sure!

2021-05-18 13:34 UTC, alicjakujawa commented
> > <img alt="Screenshot 2021-05-18 at 14 49 40" width="495" src="https://user-images.githubusercontent.com/13069555/118653919-50279880-b7e8-11eb-9b3c-82b440169ca0.png">
> > 
> > 1. I staked and i won. Why it shows total 0? and why it shows negative value for Winnings ?  2. I would actually show only 5 sig after comma, currently its too much. Why 5? Product already mentioned for other things related to values to show 5 sig dig
> 
> 1. Did you stake the motion and the objection with 1 user by any chance? If that's the case, then it makes sense to me that your winnings are in the negative and the total is 0
> 2. Sure!

Nope you can see history here:
<img width="484" alt="Screenshot 2021-05-18 at 15 33 39" src="https://user-images.githubusercontent.com/13069555/118660402-76503700-b7ee-11eb-9090-8d45fbe9827d.png">

2021-05-18 13:38 UTC, ArmandoGraterol commented
> > > <img alt="Screenshot 2021-05-18 at 14 49 40" width="495" src="https://user-images.githubusercontent.com/13069555/118653919-50279880-b7e8-11eb-9b3c-82b440169ca0.png">
> > > 
> > > 1. I staked and i won. Why it shows total 0? and why it shows negative value for Winnings ?  2. I would actually show only 5 sig after comma, currently its too much. Why 5? Product already mentioned for other things related to values to show 5 sig dig
> > 
> > 
> > 
> > 1. Did you stake the motion and the objection with 1 user by any chance? If that's the case, then it makes sense to me that your winnings are in the negative and the total is 0
> > 2. Sure!
> 
> Nope you can see history here:
> <img alt="Screenshot 2021-05-18 at 15 33 39" width="484" src="https://user-images.githubusercontent.com/13069555/118660402-76503700-b7ee-11eb-9090-8d45fbe9827d.png">

I'll take a look at that! Thanks Alicja

2021-05-18 17:39 UTC, ArmandoGraterol commented
@alicjakujawa 

After testing some more, and looking at your screenshot more closely I noticed something

While indeed `a` "won" with the vote for the YAY side, `a` staked for the NAY side. So, he won the voting but lost all that he staked because he staked for the loser side of the voting. That's what is happening in your case, I think.

2021-05-18 17:46 UTC, rdig commented
@alicjakujawa, in this case @ArmandoGraterol is correct

Yes, you won the Vote, but you staked for both sides, so you won the YAY, but lost the NAY.

Let me try to frame this. There are 2 sets of rewards, ones for staking, and ones for voting:
- for voting, you can only vote on one side, so the winnings are only on that side (it's the reward value we see under the reveal and vote widget)
- for staking, you can stake on both sides, so if one wins, the other looses. 

Just know that these two sets of rewards are independent of each other, so if you win YAY for voting, you can also win NAY for staking (and so on)

To properly test you case, stake for YAY, then let the timer run out. In that case you should only see winning stakes.
Alternatively, stake for YAY with one account, stake for NAY with a second one, go to vote, win the vote for YAY, then you will see, again, just the winnings for the YAY side

2021-05-18 20:17 UTC, rdig approved these changes
Yeah, this is good to go, although there are still some issues regarding decimal truncating.

![Screenshot from 2021-05-18 23-17-00](https://user-images.githubusercontent.com/1193222/118717799-2e9dcf80-b82f-11eb-815e-d784d39dc89e.png)
![Screenshot from 2021-05-18 23-17-06](https://user-images.githubusercontent.com/1193222/118717803-2e9dcf80-b82f-11eb-9b25-4738292325bd.png)

2021-05-18 20:17 UTC, rdig commented
Please rebase this before merging

2021-05-19 06:35 UTC, chinins approved these changes
Seems to be good now!

2021-05-19 13:16 UTC, merged