Fix countdown timer not updating
JoinColony/colonyDapp pull request #2508
Opened 2021-05-20 17:41 UTC by ArmandoGraterol

Fixed countdown timer not updating their periods after a change of state in the motion

Resolves DEV-357

2021-05-21 14:11 UTC, rdig requested changes
This is almost good. It shows the correct time, but when the motion state changes, there  is a brief flash where the time shown is wrong.

While locally this is not a big issue, on production, where everything is slow, this will be more visible.

2021-05-21 14:11 UTC, rdig commented on src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
> +  }, [state]);
This needs to have both `data` and `refetch` as dependencies! Please don't ignore `eslint` rules

2021-05-21 14:11 UTC, rdig commented on src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
> +  }, [state]);
So this is technically working, however, when the state changes, there is a brief flash where the time is still shows wrong (adding staking + voting time)

Here's an example:
![bug-vr-counter-wrong-time-flash](https://user-images.githubusercontent.com/1193222/119150528-350e9000-ba57-11eb-94f8-14936f66b0e4.gif)

In my example, the timeout is set to 1h. As you can see when the state changes to Reveal, for a brief second it shows as 2h (voting time + reveal time), then, after the `refetch()` call finishes, it shows the proper time.

2021-05-26 09:37 UTC, chinins approved these changes
Looks good to me

2021-05-31 08:11 UTC, alicjakujawa commented
@ArmandoGraterol @rdig what is the state of this?

2021-05-31 09:04 UTC, rdig commented
Why am I tagged in this ?

2021-05-31 09:04 UTC, rdig commented
@alicjakujawa why did you tag me for this ?

2021-05-31 10:22 UTC, alicjakujawa commented
> @alicjakujawa why did you tag me for this ?

Because you are as "pending reviewer"

2021-05-31 10:25 UTC, rdig commented
I mean... if it's ready I'll gladly review it, but I have no idea what the state of this is

2021-05-31 13:30 UTC, ArmandoGraterol commented
@alicjakujawa @rdig This is ready for review! :)

2021-06-01 12:33 UTC, rdig requested changes
So after staking (but not so much that the state changes -- imagine just staking 3 out of 10), the counter gets reset.

This is incorrect, since the counter just counts down until the state changes.

Most likely to fix this you'll need to modify the resolver.

2021-06-04 13:29 UTC, alicjakujawa requested changes
Unfortunately im still experiencing this bug. When im vote and it will go to reveal state, im seeing voting state time + reveal state time untill i will refresh page.

2021-06-04 15:39 UTC, alicjakujawa approved these changes

2021-06-04 19:02 UTC, chinins approved these changes
Seems to be working properly!

2021-06-04 20:05 UTC, merged