Improve formatting of TokenActivationPopover
JoinColony/colonyDapp pull request #2565
Opened 2021-06-21 21:58 UTC by ArmandoGraterol

Improved token values formatting on the TokenActivationPopover.

The issue Jack reported about not being able to stake when he reached the limit it's not a bug inside the staking slider, more like a bug inside the TokenActivationPopover.

While testing the staking slider limit, I've encountered that the slider could have a limit of `3.96` based on the reputation of the user and the popover would show me that I've exactly `3.96` activated so I would believe that I can stake up to the limit but I can't, because that `3.96` is actually `3.959`, so less than `3.96` 

Resolves DEV-423

2021-06-22 17:09 UTC, chinins approved these changes
Seems to be working well.

2021-06-28 16:09 UTC, alicjakujawa requested changes
Noticed one bug which probably wasn't introduced here, but its important to fix before merge
<img width="267" alt="Screenshot 2021-06-28 at 17 59 18" src="https://user-images.githubusercontent.com/13069555/123668430-62f7a900-d83b-11eb-8c89-518a3752fda4.png">
So i have all tokens active, but wallet dots is saying that i have some of them inactive

Also, wondering if this is correct:
<img width="437" alt="Screenshot 2021-06-28 at 18 07 21" src="https://user-images.githubusercontent.com/13069555/123668788-bff35f00-d83b-11eb-864f-292b2d6b72c5.png">
<img width="381" alt="Screenshot 2021-06-28 at 18 07 07" src="https://user-images.githubusercontent.com/13069555/123668792-c1248c00-d83b-11eb-9466-a95d1ffd63b8.png">

So we're saying to the user "you can stake max 2.96" and then we actually take a bit more :D Maybe its worth to update also formatting for slider max value? Please ask product

2021-06-29 07:12 UTC, alicjakujawa reviewed
<img width="273" alt="Screenshot 2021-06-29 at 09 12 08" src="https://user-images.githubusercontent.com/13069555/123753412-199a6e80-d8ba-11eb-9bb0-08af24449e95.png">
Did you address wrongly displayed dots next to wallet balance?

2021-06-29 09:22 UTC, chinins commented
It all looks good to me. When I hit withdraw using `Max` button, then the dot changes to green and it's all working properly. I can reproduce what Alicja is seeing if I deactivate manually tokens with lots of decimal numbers & then activate also manually by just copy-pasting the number that I see in the inactive part. Then there is a tiny amount left but we don't see it because we round only to 5 decimals and the dot stays red.

I think that the functionality is all good like this but it is a bit confusing. Maybe we should ask product what they want to show in this situation?

2021-06-30 13:16 UTC, alicjakujawa requested changes
<img width="820" alt="Screenshot 2021-06-30 at 15 16 22" src="https://user-images.githubusercontent.com/13069555/123966936-27cdb500-d9b6-11eb-8f41-d2b00fec96dc.png">
Page is crashing when im trying to move slider

2021-07-01 07:22 UTC, alicjakujawa requested changes
<img width="926" alt="Screenshot 2021-07-01 at 09 21 28" src="https://user-images.githubusercontent.com/13069555/124083086-bfcaad80-da4d-11eb-86a0-793fb5926352.png">
Correct behaviour for staking for "yey side"
Wrong for staking for "ney"

2021-07-01 13:22 UTC, alicjakujawa approved these changes
Now it works 🔥

2021-07-01 13:28 UTC, merged