Update alignment of countdown timer
JoinColony/colonyDapp pull request #2567
Opened 2021-06-22 16:40 UTC by ArmandoGraterol

![FireShot Capture 360 - Colony - localhost](https://user-images.githubusercontent.com/18473896/122966194-684a8480-d35f-11eb-884c-d65dd388d680.png)

Resolves DEV-421

2021-06-22 18:19 UTC, chinins requested changes
If you just remove `flex-end`, then when you have voting progress bar there it will switch to the left like this:

<img width="455" alt="Screenshot 2021-06-22 at 21 19 59" src="https://user-images.githubusercontent.com/34057551/122978874-de1a1480-d38e-11eb-8590-c446e85e611b.png">


However, I confirmed the specs with Karol and he sad it should move to the right, like below. So I think that would need some conditional styles or something like this to accommodate both options.
![image](https://user-images.githubusercontent.com/34057551/122977765-b0809b80-d38d-11eb-9b77-275401e0693a.png)

2021-06-22 18:24 UTC, ArmandoGraterol commented
> If you just remove `flex-end`, then when you have voting progress bar there it will switch to the left like this:
> 
> <img alt="Screenshot 2021-06-22 at 21 19 59" width="455" src="https://user-images.githubusercontent.com/34057551/122978874-de1a1480-d38e-11eb-8590-c446e85e611b.png">
> 
> However, I confirmed the specs with Karol and he sad it should move to the right, like below. So I think that would need some conditional styles or something like this to accommodate both options.
> ![image](https://user-images.githubusercontent.com/34057551/122977765-b0809b80-d38d-11eb-9b77-275401e0693a.png)

AH indeed, I didn't occurred to me that the progress bar would need to be aligned to the right. Thanks for pointing it out

2021-06-23 08:32 UTC, chinins approved these changes
Looks all correct now!

2021-06-28 09:45 UTC, alicjakujawa approved these changes

2021-06-28 14:55 UTC, merged