Fix avatar count on ColonyHome page
JoinColony/colonyDapp pull request #2578
Opened 2021-06-28 16:34 UTC by chinins

## Description

This PR fixes math logic in `useAvatarDisplayCounter` to display avatars correctly.

To test you need either to have 16 or more members in your colony or just manually provide an array of 16 or more addresses in the `ColonyMembers` component (i just use the same address over & over again) instead of manually fetching it:
```
const members = {
  colonyMembersWithReputation: ['<user address>' (repeat 16 times)]
}
```

Resolves DEV-440

2021-06-29 11:41 UTC, alicjakujawa requested changes
Please not change useAvatarDisplayCounter logic as this is used not only in ColonyMembers, just set maxAvatar = 14 inside component

2021-06-29 17:45 UTC, ArmandoGraterol reviewed
Tested `useAvatarDisplayCounter in both of the instances where it's used and it seems like on VotingResultsItem is showing 2 avatars instead of 3

2021-07-02 16:31 UTC, chinins commented
> Please not change useAvatarDisplayCounter logic as this is used not only in ColonyMembers, just set maxAvatar = 14 inside component

Unfortunately, it's not that simple, the logic will be broken. I've added another solution.

2021-07-02 16:32 UTC, chinins commented
> Tested `useAvatarDisplayCounter in both of the instances where it's used and it seems like on VotingResultsItem is showing 2 avatars instead of 3

Good catch. I didn't realise `VotingResultsItem` uses different logic for displaying avatars.

2021-07-02 17:51 UTC, ArmandoGraterol approved these changes
Tested it and it seems to be working great now in both places where the hook is used! Good job :ok_hand:

2021-07-03 09:05 UTC, alicjakujawa requested changes
It doesn't make sense. maxAvatars is a props and value of this props should be defined outside of this component. Knowledge about how many avatars we want display should be in parent power. Please revert all changes in useAvatarDisplayCounter and pass proper maxAvatar value

2021-07-05 10:21 UTC, chinins commented
> It doesn't make sense. maxAvatars is a props and value of this props should be defined outside of this component. Knowledge about how many avatars we want display should be in parent power. Please revert all changes in useAvatarDisplayCounter and pass proper maxAvatar value

As I explained on discord, then the case when there is exactly 15 avatars is wrong:
<img width="193" alt="Screenshot_2021-07-05_at_13 03 25" src="https://user-images.githubusercontent.com/34057551/124456742-f886c180-dd82-11eb-9f1e-69d32b2ef6aa.png">

I still think that my solution is correct as it allows for both options and takes the logic away from the components. Wer can then reuse it if we have other cases like this.

2021-07-05 10:26 UTC, alicjakujawa approved these changes

2021-07-05 10:34 UTC, merged