Add RemainingDisplayWidget component
JoinColony/colonyDapp pull request #2617
Opened 2021-07-21 22:21 UTC by ArmandoGraterol

## Description

Added new RemainingDisplayWidget component to CoinMachine in order to display time and tokens remaining

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves DEV-452

2021-07-26 08:08 UTC, chinins reviewed
Have some comments/suggestions (please, see my notes).

2021-07-26 09:47 UTC, alicjakujawa requested changes

2021-07-26 09:47 UTC, alicjakujawa commented on src/modules/dashboard/components/CoinMachine/RemainingDisplayWidget/RemainingDisplayWidget.tsx
> +};
Agree with this, logic should be handled in RemainingDisplayWidget based on provided values

2021-07-27 10:41 UTC, chinins approved these changes
Good to go!

2021-07-27 14:28 UTC, alicjakujawa requested changes
Nice job with moving logic to component itself. Unfortunately we still miss part of logic, component which display "time remaning" its actually counter, you can check time in SaleStateWidget and copy/reuse it

2021-07-27 14:29 UTC, alicjakujawa commented
> Nice job with moving logic to component itself. Unfortunately we still miss part of logic, component which display "time remaning" its actually counter, you can check time in SaleStateWidget and copy/reuse it

ah and one more thing, lets be consistent and stick with same format of time displaying like in SalesStateWidget (and motions and disputes)

2021-07-27 14:30 UTC, alicjakujawa commented
> > Nice job with moving logic to component itself. Unfortunately we still miss part of logic, component which display "time remaning" its actually counter, you can check time in SaleStateWidget and copy/reuse it
> 
> ah and one more thing, lets be consistent and stick with same format of time displaying like in SalesStateWidget (and motions and disputes)

You can also extract timer logic/styles etc and reuse it in both components

2021-07-27 15:51 UTC, ArmandoGraterol commented
> Nice job with moving logic to component itself. Unfortunately we still miss part of logic, component which display "time remaning" its actually counter, you can check time in SaleStateWidget and copy/reuse it

My understanding was that this kind of logic wouldn't be included on this issue, but oh well if the logic is already done in another place and I just need to reuse it then I'll do it

2021-07-28 06:47 UTC, alicjakujawa requested changes
<img width="252" alt="Screenshot 2021-07-28 at 08 42 58" src="https://user-images.githubusercontent.com/13069555/127276340-5274df1b-c07a-410d-bc87-a28e2ca748d6.png">
Same issue with grey background

2021-07-29 11:01 UTC, alicjakujawa approved these changes
Looks good, please only update font-weight to normal for value (as in designs we dont have bold) Pre-approving

2021-07-29 11:01 UTC, alicjakujawa commented
> Looks good, please only update font-weight to normal for value (as in designs we dont have bold) Pre-approving

aha, and rebase and test haha

2021-07-29 13:32 UTC, ArmandoGraterol commented
> Looks good, please only update font-weight to normal for value (as in designs we don't have bold) Pre-approving

Hmmm, in the design the values look like they are on `700`.

I found that in Figma **only** the font-weight of `N/A`  is supposed to be "400", but the font-weight of the other values is "700". Also, if I use "400" then they wouldn't look like they appear in the design.

So basically, I think Figma is smoking crack because there's no way the "N/A" is using `400` and it looks like that. It must be using `700` like the rest of the values.

2021-07-29 13:53 UTC, merged