Add copy button to coin machine contract address
JoinColony/colonyDapp pull request #2722
Opened 2021-09-14 22:53 UTC by ArmandoGraterol

![FireShot Capture 443 - Colony - localhost](https://user-images.githubusercontent.com/18473896/133344166-cfe58df8-7c58-4569-93e0-19de40b5acc7.png)

Resolves #2720

2021-09-15 07:11 UTC, alicjakujawa requested changes
<img width="343" alt="Screenshot 2021-09-15 at 09 07 14" src="https://user-images.githubusercontent.com/13069555/133387452-fc683177-d5dc-4c00-a22d-d61af27c3cc9.png">

it seems to be not aligned on my machine :<
Also, i dont think we should introduce it ONLY for coin machine extension, but for all extensions, please recheck with product

2021-09-15 07:29 UTC, rdig requested changes
I'm good with this, apart from the fact that this needs to be enable for all extensions

2021-09-15 07:29 UTC, rdig commented on src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
> +            )}
This needs to be enabled for all extensions not just Coin Machine

2021-09-16 07:05 UTC, rdig requested changes
I'm good with your changes but now I'm reconsidering if this is the correct route to take.

We now have two ways of copying the address in the same side:
- hover + click for the user address
- just click for the extension contract address

![demo-different-types-of-address-copy](https://user-images.githubusercontent.com/1193222/133565708-3065e743-c353-4be5-9e26-742486c45637.gif)

We should standardize on just using one of them. Either the hover + click, or just showing the "Copy" and letting the user click it to copy the address into the clipboard.

Show the gif to product and tell them we need to standardize here, and that they need to pick on of them.

After that, refactor this so that it reflects those changes.

Sorry about not picking up on this earlier.

2021-09-16 10:04 UTC, alicjakujawa approved these changes

2021-09-16 10:08 UTC, chinins reviewed
The code & functionality are all good but I do agree with Raul about having it the same way. Should we also have it similar to other places in the app?

2021-09-17 09:18 UTC, rdig approved these changes
Good to go! :100:

2021-09-17 11:30 UTC, chinins approved these changes
All good!

2021-09-20 17:19 UTC, merged