Bug/issue 2768 staking error
JoinColony/colonyDapp pull request #2773
Opened 2021-10-05 19:30 UTC by ArmandoGraterol

- Fixed token activation popover not validating correctly some token amounts due to Javascript being weird with type coercion
- Fixed staking slider error showing up in cases where the user had more active tokens than reputation points, but had enough reputation to stake the entire remaining stake, and therefore the error making no sense.

Resolves #2768

2021-10-06 16:54 UTC, chinins submitted a review, later dismissed
Looks good!

2021-11-01 17:06 UTC, ArmandoGraterol commented
@rdig After rebasing, I couldn't replicate the first case and the second case seems to be correct so please test this again and notify if you see something weird again.

2021-11-08 13:21 UTC, rdig requested changes
Sadly this is still the same:

![Screenshot from 2021-11-08 15-19-36](https://user-images.githubusercontent.com/1193222/140749102-48321a60-9a8d-4ddf-ab3c-b2ca8081f4c5.png)

Error shows up, however the stake button was not disabled and I could click it an generate the transactions _(which went through successfully)_

So I guess we'll just have to replicate the logic the button is using for disabled/enabled states to show/hide the specific errors.

2021-11-08 15:11 UTC, ArmandoGraterol commented
> Error shows up, however the stake button was not disabled and I could click it an generate the transactions _(which went through successfully)_
> 
> So I guess we'll just have to replicate the logic the button is using for disabled/enabled states to show/hide the specific errors.

@rdig Wait, isn't this "error" (More of a warning than an error) correct? It's saying `You do not have enough active tokens to stake more`, which is true, you only have `0.045` active tokens and therefore you can only stake up to that amount, but if you activate more tokens, you could stake more. Basically, the error is more of an informative message or a warning

At least that's what I understand about how this error works

2021-11-08 15:52 UTC, chinins commented
> > Error shows up, however the stake button was not disabled and I could click it an generate the transactions _(which went through successfully)_
> > So I guess we'll just have to replicate the logic the button is using for disabled/enabled states to show/hide the specific errors.
> 
> @rdig Wait, isn't this "error" (More of a warning than an error) correct? It's saying `You do not have enough active tokens to stake more`, which is true, you only have `0.045` active tokens and therefore you can only stake up to that amount, but if you activate more tokens, you could stake more. Basically, the error is more of an informative message or a warning
> 
> At least that's what I understand about how this error works

@rdig, I agree with Armando. This was my understanding as well and it looks like expected behaviour. You have 0.045 active tokens and this is how much you could stake - seems correct to me

2021-11-08 15:52 UTC, rdig commented
I agree that it's more like a "info" message than anything else, however it is still styled as an error, and to the layman, they can't be differentiated.

So I'd suggest talking to product about styling it differently, and maybe even a different copy message. Something like: "this is the max you can stake right now", or something along those lines, because as it currently stands it's confusing as hell.

2021-11-08 15:54 UTC, chinins commented
> I agree that it's more like a "info" message than anything else, however it is still styled as an error, and to the layman, they can't be differentiated.
> 
> So I'd suggest talking to product about styling it differently, and maybe even a different copy message. Something like: "this is the max you can stake right now", or something along those lines, because as it currently stands it's confusing as hell.

We can revisit it with product but that was initially what was given by them...

2021-11-09 14:22 UTC, rdig approved these changes
All good now! :+1: 

I still think we should have different styling for "info"-type messages, but if product is fine with them, let's not spend more time here.

2021-11-09 16:33 UTC, chinins approved these changes
All good, nice work!

2021-11-10 00:09 UTC, merged