Update recovery resolvers with subgraph queries
JoinColony/colonyDapp pull request #2811
Opened 2021-10-20 19:40 UTC by ArmandoGraterol

**New stuff** ✨

* Added `SubgraphRecoveryModeEventsQuery` subgraph query

**Changes** 🏗

* Updated `getSessionRecoveryEvents`
* Updated `recoveryAllEnteredEvents` resolver
* Updated `recoveryRolesUsers` resolver
* Updated `legacyNumberOfRecoveryRoles` resolver

**Yapa**
* Fixed a bug where entering recovery mode would throw Apollo related errors if the list of users with recovery roles contained a user without a profile due to `getMinimalUser` not returning the users with `__typename`(s) 
* Fixed some recovery mode events on the action feed using the wrong user as the initiator

Resolves #2798

2021-10-22 04:29 UTC, alicjakujawa submitted a review, later dismissed

2021-10-29 21:43 UTC, ArmandoGraterol commented
@rdig I updated the PR's description with an explanation of the bug and the fix, it's a really _really_ weird and annoying bug, don't know if there's an alternative or something that I'm missing, but alas it should be fixed.

2021-11-02 13:24 UTC, rdig requested changes
Sadly it's even more broken now :

Entering recovery mode still fails _(first time when you give permissions, I can't test the second time around, since it's broken and doesn't let me exit recovery mode)_

![Screenshot from 2021-11-02 15-15-31](https://user-images.githubusercontent.com/1193222/139854362-ad3ec3b4-7047-47f7-aee8-2eb7c63615cf.png)

And after a page refresh, when entering the recovery mode action page, gives out the same error, and prevents you from exiting recovery mode (does not show correct number of users with permissions, and does not show the "exit recovery" button once approvals are set)

![Screenshot from 2021-11-02 15-16-24](https://user-images.githubusercontent.com/1193222/139854608-01f0fcf5-603e-4441-8a18-641c52811c48.png)

Oh! I think I know what it is. I gave "Recovery" permissions to a user that doesn't have a profile created:
(![Screenshot from 2021-11-02 15-19-53](https://user-images.githubusercontent.com/1193222/139854928-dcc17bd9-8896-4a1e-9ebc-ea835f3dfea9.png)

So this might be the problem this time around. However this is a edge case we need to fix, as this will most likely happen in production. _(I know colonies that do this)_

2021-11-02 13:24 UTC, rdig commented
Yep. I confirm this works as expected when all users have a profile created.

![Screenshot from 2021-11-02 15-23-53](https://user-images.githubusercontent.com/1193222/139855387-16981dae-bfa8-403d-9ed4-a9d2701d8dd7.png)

So I guess this is just a case of handling users who don't have a profile yet

2021-11-03 08:00 UTC, rdig requested changes
This is all good, however I think I found bug that was here before and we never noticed. So this is not on you, it's basically on me for not finding it sooner.

- I have two users with recovery permissions (`a` and `b`)
- they both create a recovery action (update slot value)
- both actions show up as user `a`

Here's a demo:
![bug-same-user-for-all-recovery-actions](https://user-images.githubusercontent.com/1193222/140025855-294e2a85-b17a-481a-9f1f-30b7488bfda2.gif)

I think this is a case of the message descriptors values not being passed around properly, because other than that, everything seems to be tracked correctly.

2021-11-03 18:29 UTC, ArmandoGraterol commented
@rdig Should be fixed now! It was indeed a case of the wrong value being used on the message descriptors

2021-11-04 07:38 UTC, rdig commented
@ArmandoGraterol let me know if you want me to merge this for you.

2021-11-04 10:52 UTC, chinins approved these changes
Working as expected - well done! it was not an easy PR.

2021-11-04 14:32 UTC, merged