Fix: fixes masked address alignment issue
JoinColony/colonyDapp pull request #2828
Opened 2021-11-02 13:12 UTC by agustif

## Description

- [x] TODO fix alignment issues on ubuntu / chrome for masked address

**New stuff** ✨
Adds line-height: 1; 
css property to MaskedAddress address css class

Resolves #2824

2021-11-02 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=2828) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=2828) before we can accept your contribution.<br/><hr/>**Agusti Fernandez Pardo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=2828) it.</sub>

2021-11-03 10:29 UTC, chinins reviewed
The code is good and at least on mac the alignment looks good. Raul and/or Armando will just need to confirm that it looks good on their OS.

Couple of notes regarding your commits & general branch management:
- no need to put `issue` word in the branch title
- make sure that your commit message isn't more than 72 characters so that we don't have `...` in the message
- you have 3 commits of `merging master` into your branch. Is it from rebasing? I don't think this should happen. How did you do the rebase? Did you do the following? (The below sequence is the common way to do the rebase here):
1. `git pull --rebase origin master`
2. `git push --force-with-lease origin maintenance/issue-2824-fix-masked-address-alignment-in-events-list `

<img width="689" alt="Screenshot 2021-11-03 at 11 24 02" src="https://user-images.githubusercontent.com/34057551/140043984-a3500f93-2c6b-47f5-aa8f-ba213a187f26.png">

2021-11-03 15:06 UTC, rdig requested changes
I'm ok with the changes. Congrats on your first PR! :cherries: 

It renders fine on my machine:

![Screenshot from 2021-11-03 16-59-56](https://user-images.githubusercontent.com/1193222/140086423-84656d3a-6389-403c-a9cd-0095cad0caac.png)

![Screenshot from 2021-11-03 17-01-35](https://user-images.githubusercontent.com/1193222/140086431-47dcd23b-78ea-40d3-8ccd-1f4cb70e4843.png)
![Screenshot from 2021-11-03 17-01-47](https://user-images.githubusercontent.com/1193222/140086434-90f6e877-0381-4aee-a6ff-6f57715bf6f8.png)

However, the commits part is off: you most likely didn't rebase properly.

Have a look at the notes @chinins left in your review.

Also, give: [Github + Git Workflows](https://www.notion.so/colony/Github-Git-Workflows-1acdaf1041ee421bb5fc6ecace31096f) another read _(it was part of your onboarding doc)_, which covers most, if not all, of what Olga highlighted.

2021-11-04 11:28 UTC, agustif commented
A new PR with the same changes has been opened at https://github.com/JoinColony/colonyDapp/pull/2831 and can be reviewed/approved there!

2021-11-04 11:28 UTC, closed without merging