Fix alignment on friendly name and masked address in events list
JoinColony/colonyDapp pull request #2832
Opened 2021-11-04 15:14 UTC by agustif

## Description

- [x] fix alignment issues  for masked address
- [x]  fix alignment issues for friendly name
- [x]  fix alignment issues inside tooltip

**Fixes**  alignment of both FriendlyName and MaskedAddress both in the events list item and in the tooltip hover.

## Screenshot
![image](https://user-images.githubusercontent.com/6601142/139853656-54a38e4e-49a6-4ae9-8320-3a801ce1b08f.png)
![image](https://user-images.githubusercontent.com/6601142/139909348-e3943057-c929-4bfb-9df1-9d55e4bec67d.png)

Supersedes #2828
```Notice: This PR is a redo of https://github.com/JoinColony/colonyDapp/pull/2828  in order to fix the bad rebasing of master branch```

Resolves #2824

2021-11-04 16:57 UTC, chinins requested changes
Ignore previous comment - the branch didn't switch :)

2021-11-04 17:32 UTC, chinins approved these changes
All good!

2021-11-05 15:05 UTC, alicjakujawa approved these changes

2021-11-05 17:26 UTC, ArmandoGraterol approved these changes
Looks good on my machine :100: Nice job!

2021-11-05 20:05 UTC, merged