Fix overlapping banner on motions
JoinColony/colonyDapp pull request #3004
Opened 2021-12-03 19:12 UTC by danbr

## Description

This fix locks the position of the motions banner to the top of the screen. It remains in place during scrolling.

<img width="1438" alt="Screenshot 2021-12-03 at 20 00 21" src="https://user-images.githubusercontent.com/582700/144658652-b6def0cb-0cd5-4251-8f92-e1d086cf9cb1.png">

Resolves #2996

2021-12-06 12:54 UTC, arrenv requested changes
@danbr I have tested locally, the banner is working better now. 

The padding just needs to be corrected. See screenshots:

![40554000-1387-4cb7-b689-91d90110bfe3](https://user-images.githubusercontent.com/33682027/144849527-68f0bd60-a42d-462c-abff-a6b5bd94281c.png)
![13d3cb38-d3de-466c-a358-6114adc02dec](https://user-images.githubusercontent.com/33682027/144849541-8d58ea68-0e76-4b67-b582-ee5e1f029a1d.png)

![98732d0d-503e-43a5-8580-b6d7bd222106](https://user-images.githubusercontent.com/33682027/144849538-5da37c31-2e27-4ceb-8a2a-e79b7b808802.png)
![9f81ffa4-4fab-4bfa-a3c8-7a8136438238](https://user-images.githubusercontent.com/33682027/144849540-56002c96-767f-4f44-b81e-f981f797ffd7.png)

2021-12-06 15:11 UTC, rdig requested changes
Holding off on my review until @arrenv 's changes are addressed

2021-12-07 12:10 UTC, arrenv commented
Nice one! Scrolling and padding are looking much better on my end.

2021-12-07 12:13 UTC, arrenv commented
Nice one! Scrolling and padding are looking much better on my end.

![scrolling-alert-1](https://user-images.githubusercontent.com/33682027/145026856-57d0371e-8717-4da9-bc7c-83e5a5293208.png)

![scrolling-alert-2](https://user-images.githubusercontent.com/33682027/145026887-f249b6d0-6d22-449a-acea-d09e7fd82cc5.png)

![scrolling-alert-3](https://user-images.githubusercontent.com/33682027/145026899-a8f4002b-cb15-4c9e-af11-b24d70713f68.png)

P.S. Sorry for closing, my internet timed out for a second as I was commenting and caused some weirdness.

2021-12-07 12:14 UTC, arrenv approved these changes

2021-12-07 12:51 UTC, rdig approved these changes
Good to go!

2021-12-07 12:58 UTC, arrenv commented on src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
> +.bannerPadding {
I was thinking that bannerPadding may be better added in DefaultMotion. Although, I suppose this allows for other extensions to use it in future.

2021-12-07 16:00 UTC, merged