Fix interpretation of the decimal points in amount fields
JoinColony/colonyDapp pull request #3023
Opened 2021-12-09 20:07 UTC by ArmandoGraterol

The problem was that `Decimal` and `parseFloat`/`parseInteger` don't interpret '.' as '0.0', so I had to use an alternative like `toFinite` to get a safe value.

- If it's `parseFloat`/`parseInteger`, it would interpret it as `NaN`, resulting in the validation of the form throwing a really long validation error message that could break the interface, and it's not user friendly (`TransferFundsDialog`, `TokenMintDialog`, `CreatePaymentDialog`)
- If it's `Decimal` the one that receives the `.`, it would just crash the page and if it somehow doesn't, it still would show the long weird error (`BuyTokens`) 

Please check all of the places where we use an amount field, all of them should be able to perceive `.` as a `0` without crashing or throwing a user-unfriendly error.

Resolves #3011

2021-12-10 10:43 UTC, arrenv requested changes
The fix works well for me, there is just one other location I found that still has the error.

![decimal-error-2](https://user-images.githubusercontent.com/33682027/145561507-f85b4e6c-d020-4703-b55a-2d9b6d1bc0af.png)

All the inputs on Motions and CoinMachine enabling, could probably benefit as well, to make the errors a little friendlier.

![decimal-unfriendly-errors](https://user-images.githubusercontent.com/33682027/145562277-161c0870-4d2d-4ef7-ba86-64bab1e4a345.png)

2021-12-10 12:26 UTC, alicjakujawa reviewed
https://github.com/JoinColony/colonyDapp/issues/3011

I was testing this "bug" on master and it wasn't happening for me 🤔

2021-12-10 15:11 UTC, ArmandoGraterol commented
@arrenv Thank you for pointing that out! I knew I was forgetting to check some places

@alicjakujawa Weird, don't know what to tell you other than to check that you are writing just a `.` with no numbers alongside it just like in Arren's screenshots or Jack's gif

2021-12-13 10:27 UTC, arrenv commented
@ArmandoGraterol Is it just on my end or are there no longer user errors showing up for the extension setup fields, only a console error and a disabled button.

![dot-in-extension-installing](https://user-images.githubusercontent.com/33682027/145795676-b7a5106a-2f4c-41e2-8fbf-0aedf1604d08.gif)

2021-12-13 16:23 UTC, ArmandoGraterol commented
> @ArmandoGraterol Is it just on my end or are there no longer user errors showing up for the extension setup fields, only a console error and a disabled button.
> 
> ![dot-in-extension-installing](https://user-images.githubusercontent.com/33682027/145795676-b7a5106a-2f4c-41e2-8fbf-0aedf1604d08.gif)

Yep, the form was missing some validation from before this PR, so I added it and now it should validate as expected. Thank you Arren!

2021-12-13 22:04 UTC, chinins approved these changes
Very good! Didn't even realise there was this bug. I tried it on master and it crashed straight away but working as expected now.

2021-12-14 12:24 UTC, arrenv approved these changes
Working great, everything I could find is working as expected.

2021-12-14 14:43 UTC, merged