Adds loading text to synaps KYC dialog
JoinColony/colonyDapp pull request #3043
Opened 2021-12-14 22:13 UTC by agustif

## Description
For testing purposes you might add the spinner loader somewhere else on the dapp with the appropiate text value. 
Btw I had to pass defaultMessage explicitly. not sure if good but is how it worked. otherwise ot showed the label instead of the text.

 
- [x] Add loading text when Synaps KYC loading asks for wallet access / confirmation

**New stuff** ✨

* Adds new message for loadingText in KYCDialog

**Changes** 🏗

* Adds loadingText prop to SpinnerLoader in KYCDialog component

Resolves #2903

2021-12-15 20:50 UTC, chinins requested changes
You need more margin below the spinner (doesn't have to be precise but just close to what Karol had in his print screen)

What you have:
<img width="540" alt="Screenshot 2021-12-15 at 15 47 01" src="https://user-images.githubusercontent.com/34057551/146262570-60555628-321c-46dc-97cf-14fc618bb47a.png">

What Karol is asking for:
<img width="257" alt="Screenshot 2021-12-15 at 15 47 36" src="https://user-images.githubusercontent.com/34057551/146262640-5ae623a9-c94b-4504-80f4-c7b94789cbf7.png">

Moreover, could you please rebase your branch and also add how to test (and for future PRs with testing that is not so straight forward). I can find my way to it but it feels a bit of a waste of time for every person to do that if we don't remember the exact flow of the dialogs.

2021-12-20 08:31 UTC, rdig commented
What's the state of this, and why, does adding some small copy take so long ?

2021-12-20 09:21 UTC, agustif commented
> What's the state of this, and why, does adding some small copy take so long ?

Will be pushing fix for olga's requested changes shortly, and it should be good to go.

Sorry for the delay!

2021-12-20 12:04 UTC, agustif commented
Added a new loadingText css class with a padding-top of 30px; 

![image](https://user-images.githubusercontent.com/6601142/146764563-36304a6d-1e40-4fea-80c0-73419a2ecb8d.png)

Rebasing now

2021-12-20 12:37 UTC, agustif commented
I've added a submodule, redoing history to squash all changes in one commit and undo it.

2021-12-20 12:58 UTC, agustif commented
good to re-review now!

2021-12-23 21:33 UTC, chinins requested changes
This is wrong. `loadingText` prop is used in lots of places - that's why it exists. Doing a simple search in a code editor should show you that:
<img width="271" alt="Screenshot 2021-12-23 at 16 30 20" src="https://user-images.githubusercontent.com/34057551/147293004-deb0fc81-a0f2-453a-a4b8-a1590368265b.png">

You broke the UI of loading spinners with loading text, these are just 2 examples (and you can see them straight away when you reload the dapp):
![loading-actions](https://user-images.githubusercontent.com/34057551/147293059-114118e0-eec6-408f-8e13-330acbfd767e.gif)

![colony-loading](https://user-images.githubusercontent.com/34057551/147293055-6e8d0e8e-b809-4591-aa11-394261b2dce5.gif)

The margin should be applied in the KYC dialog component and NOT on the core component.
Also, you should not use the `defaultMessage`. If you have to this means something is wrong.

2021-12-23 21:48 UTC, agustif commented
> This is wrong. `loadingText` prop is used in lots of places - that's why it exists. Doing a simple search in a code editor should show you that:
> 

> 
> 
> You broke the UI of loading spinners with loading text, these are just 2 examples (and you can see them straight away when you reload the dapp):
> 

> The margin should be applied in the KYC dialog component and NOT on the core component.
> 
> Also, you should not use the `defaultMessage`. If you have to this means something is wrong.
> 
> 

Thank you olga, will redo and fix

2022-01-25 02:35 UTC, danbr commented
Solved in a different PR.

2022-01-25 02:35 UTC, closed without merging