Fixes motions not appearing in the correct domain in actions list
JoinColony/colonyDapp pull request #3073
Opened 2021-12-23 17:22 UTC by arrenv

## Description

Fixes motions correctly appearing in the actions list and actions team filter. See this issue for details #3056.

**New stuff** ✨

* Adds assignment of ethDomainId to motion action item.
* Adds expectation check to actions motion transformer.

### Testing

* Ensure the 'Motions' extension is enabled.
* Create a child team.
* You will need to make sure there is funds and reputation in a team.
* Perform a motion action in the child team and ensure it finishes. You can speed up the time with the following script, this passes 3 days of time.
`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[260000],"id": 1}' localhost:8545 && curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[]}' localhost:8545`
* Ensure the motion action appears in the list. It may take a second to load after the other actions load.
* Check the domain label of the action.
* Filter the actions by the team, and ensure the motion appears in the list.

### Before

![actions-wrong-team-2](https://user-images.githubusercontent.com/33682027/147272307-ee7104b6-390e-4455-a063-56e13d79933d.png)

![actions-wrong-team](https://user-images.githubusercontent.com/33682027/147272308-a43e80fb-3c7a-45b9-b060-e1e8b3ca2d69.png)

### After  ✨

![actions-right-team](https://user-images.githubusercontent.com/33682027/147272454-96492d22-d205-4bdc-ba3c-93eb06c433c8.png)

![actions-right-team-2](https://user-images.githubusercontent.com/33682027/147272455-11856854-9c24-4e2d-91f1-13fc0cbac176.png)

Resolves #3056

2021-12-23 21:07 UTC, chinins requested changes
It doesn't seem like it's working for me....

This is the motion I'm creating:
<img width="714" alt="Screenshot 2021-12-23 at 16 02 16" src="https://user-images.githubusercontent.com/34057551/147291201-749bb23d-78ec-4a6b-a30f-4d15fdcc8698.png">

However the motion created in is `Root` and not the `cave of wonders`
<img width="1065" alt="Screenshot 2021-12-23 at 16 02 52" src="https://user-images.githubusercontent.com/34057551/147291233-a18d22fd-ff52-4e52-9300-c73694fa431d.png">

And here is this motion in the list (and actually the one before was also in the `cave of wonders` team, I just created another one to double check):
<img width="843" alt="Screenshot 2021-12-23 at 16 03 46" src="https://user-images.githubusercontent.com/34057551/147291290-4a7eba23-839b-429c-90ba-fc935b60dff6.png">

And when i'm filtering by domain neither of the motions are there:
<img width="823" alt="Screenshot 2021-12-23 at 16 05 22" src="https://user-images.githubusercontent.com/34057551/147291386-4f6d3ff2-b19c-4a9c-8629-c1500ad4b45a.png">

And here is my terminal confirmation that I'm on the correct branch:
<img width="845" alt="Screenshot 2021-12-23 at 16 06 09" src="https://user-images.githubusercontent.com/34057551/147291424-351db07f-2fdd-4bf0-bfe2-17efaa937444.png">

2021-12-24 07:36 UTC, arrenv commented
@chinins I thought that may have been a bug, that is why I had trouble replicating the issue initially.

This is a separate issue on allocating the correct team from the dialog, however, I can look into it in this issue as well. What do you think?

This PR is focused on getting the right information from the SubGraph. To create a motion in a domain, you need to select the team before creating the action. See gif below:

![correct-team-allocation](https://user-images.githubusercontent.com/33682027/147330062-c5c87ce7-5e34-4554-a361-a2a3b646d4e9.gif)

2021-12-24 17:29 UTC, chinins commented
> @chinins I thought that may have been a bug, that is why I had trouble replicating the issue initially.
> 
> This is a separate issue on allocating the correct team from the dialog, however, I can look into it in this issue as well. What do you think?
> 
> This PR is focused on getting the right information from the SubGraph. To create a motion in a domain, you need to select the team before creating the action. See gif below:
> 
> ![correct-team-allocation](https://user-images.githubusercontent.com/33682027/147330062-c5c87ce7-5e34-4554-a361-a2a3b646d4e9.gif)

We had a call with Arren and clarified where my problem was. It seems that there is a bug in `CreatePayment` dialog that doesn't send correct motion domain to the network. It is indeed a separate issue which I will create.

2021-12-24 17:29 UTC, chinins approved these changes
It's all clear and good now.

2022-01-03 12:15 UTC, alicjakujawa approved these changes

2022-01-04 10:36 UTC, merged