Fix apollo error in user resolver
JoinColony/colonyDapp pull request #3079
Opened 2021-12-29 00:40 UTC by chinins

## Description

This PR adds a try catch block around initiation of voting extension client in user resolver. If we don't do it and the voting extension is not installed then we will get an apollo error when creating a payment. This is because we use a query in the create payment saga that uses this resolver.

Resolves #3078

2021-12-29 09:41 UTC, arrenv commented
@chinins This seems to trigger the error always now. As in, just reloading the page causes the error.

![error-with-no-action](https://user-images.githubusercontent.com/33682027/147648339-c94bdf9f-3157-4730-91e4-cd72c1440136.jpg)

2021-12-29 09:41 UTC, arrenv requested changes
As of previous comment.

2021-12-29 09:46 UTC, arrenv requested changes

2021-12-29 09:46 UTC, arrenv commented on src/data/resolvers/user.ts
> +    console.error(error);
Removing the console.log should do the trick to remove the error. Otherwise, this PR fixes the main error.

2022-01-01 20:44 UTC, chinins commented
> @chinins This seems to trigger the error always now. As in, just reloading the page causes the error.
> 
> ![error-with-no-action](https://user-images.githubusercontent.com/33682027/147648339-c94bdf9f-3157-4730-91e4-cd72c1440136.jpg)

Yeah, I guess it's not worth even logging it. I've changed it to `silent` error now.

2022-01-04 09:59 UTC, arrenv approved these changes
Nice, works well for me, no more errors.

2022-01-13 19:05 UTC, ArmandoGraterol approved these changes
Good job :100:

2022-01-14 21:40 UTC, merged