Fix token activation confirm check when using max button
JoinColony/colonyDapp pull request #3083
Opened 2022-01-03 20:53 UTC by chinins

## Description

This PR fixes the situation in token activation popover when we press max button. The confirm button was disabled although the value was correct. This happens because the `toFinite` method rounds up the value in the check and the value appears to be larger than it is and so fails the disabled check.

In the current fix I have removed the `toFinite` from the check (it doesn't seem appropriate to use it here). I tried to think/remember what problem it was solving or try to find bugs/problems with my solution but couldn't. If somebody knows why `toFinite` method was added, I would then know which problem I should fix if we can't use it.

Another thing I noticed is that `amount` in values comes as a string with lots of numbers after decimals (more than 5) although when setting max we actually trim it to 5 decimal places. So there might be something wrong with the method that sets the max amount. I am looking into that.

resolves #3064

2022-01-04 14:18 UTC, arrenv requested changes
This fixes the max button, however reintroduces a previous issue that does not allow a decimal to be interpreted as a number, see https://github.com/JoinColony/colonyDapp/pull/3023, or simply add a "." into the input after removing toFinite.


I think the bug is actually caused by the same issue regarding the decimals I was talking about. The `unformattedTokenBalance` function uses `import moveDecimal from 'move-decimal-point'` which, when removed and tested with a more manual divide, calculates the max without the incorrect decimals and without causing the button to be disabled.

Here is a demo showing the incorrect decimals:
![after-fix-max-button](https://user-images.githubusercontent.com/33682027/148064615-b0a2c6b2-6c99-450f-85d6-eadcd9595006.gif)

2022-01-04 16:29 UTC, chinins commented
> This fixes the max button, however reintroduces a previous issue that does not allow a decimal to be interpreted as a number, see #3023, or simply add a "." into the input after removing toFinite.
> 
> I think the bug is actually caused by the same issue regarding the decimals I was talking about. The `unformattedTokenBalance` function uses `import moveDecimal from 'move-decimal-point'` which, when removed and tested with a more manual divide, calculates the max without the incorrect decimals and without causing the button to be disabled.

Thank you for the link to the PR! I now understand what was the initial problem I need to solve.
I thought that it was moveDecimal initially but it is not. The problem is in `toFinite` rounding up and then the value being more than it actually is (as I mentioned in my PR description). So the disabled state is triggered by it although the value is correct.

I will look into how to solve it differently... Thank you again for pointing to the initial PR that introduced `toFinite`

2022-01-04 17:03 UTC, arrenv commented
@chinins you're welcome. Also, thank you for clarifying.

2022-01-05 00:16 UTC, chinins commented
@arrenv, I've added some updates. Can you please have a look and test and tell me what you think? Thank you!

2022-01-05 17:48 UTC, arrenv approved these changes
This is now working on my end without any issues.

I tried a few different options previously as well, however I like this one the best so far.

2022-01-14 22:29 UTC, merged