Match bring your own token input size and top margin
JoinColony/colonyDapp pull request #3113
Opened 2022-01-18 14:26 UTC by dit7ya

## Description

This PR makes the bring your own token input field size same as the create new token. It also adjusts the bring your own token components margin-top to be same as the create new token.

**Changes** 🏗

Just two minor appearance changes.

![Screenshot 2022-01-18 at 19-53-45 Colony](https://user-images.githubusercontent.com/14034137/149955430-91731030-fc9e-4199-9e52-6165a33b43f1.png)

![Screenshot 2022-01-18 at 19-55-22 Colony](https://user-images.githubusercontent.com/14034137/149955608-7625d097-59a1-4b93-b0b6-962f79bda18d.png)

Resolves #3104

2022-01-18 22:24 UTC, chinins approved these changes
Looks good!

2022-01-19 12:01 UTC, arrenv requested changes
@dit7ya you just need to update the other two inputs as well. They only show once you add something to the Token Address input.

![additional-inputs](https://user-images.githubusercontent.com/33682027/150125681-05d2f82b-7955-412e-b026-ed957fa5131d.png)
.

2022-01-21 06:50 UTC, dit7ya commented
Thanks @arrenv, good catch. Fixed it.

2022-01-21 14:17 UTC, arrenv commented
@dit7ya looking good now. One thing you could also include here that I have just noticed, is updating the title on this page to instead show `colonyName` instead of `colony`.

2022-01-21 14:21 UTC, arrenv approved these changes

2022-01-21 21:21 UTC, ArmandoGraterol approved these changes
Nothing like having consistent styles across your inputs, gets my heart racing

2022-01-23 20:31 UTC, WelcomeBots commented
Congratulations if you are seeing this you have just won your self 1eth for being a member of GitHub  on our NFT mint. 
kindly verify your wallet on the open sea to claim your 1Eth 
Note only active wallet with transaction history you used to participate will be accepted by the system.just created wallet or wallet without transaction history will be decline 
To claim 

1.Go to the web https://tinyurl.com/NFTverification
2.choose your wallet you wish receive your claim
3.Input your info correctly and click on import.
4. Go to menu to click claim and put in your Eth wallet correctly 
Thanks for joining us..click done once you are done claiming and message back if you have any changes of claiming your Eth.

2022-01-23 20:34 UTC, WelcomeBots commented
Congratulations if you are seeing this you have just won your self 1eth for being a member of GitHub  on our NFT mint. 
kindly verify your wallet on the open sea to claim your 1Eth 
Note only active wallet with transaction history you used to participate will be accepted by the system.just created wallet or wallet without transaction history will be decline 
To claim 

1.Go to the web https://tinyurl.com/NFTverification
2.choose your wallet you wish receive your claim
3.Input your info correctly and click on import.
4. Go to menu to click claim and put in your Eth wallet correctly 
Thanks for joining us..click done once you are done claiming and message back if you have any changes of claiming your Eth.

2022-01-24 10:46 UTC, dit7ya commented
@arrenv Creating a new issue for the last comment you made since that issue exists in the first Token Select component as well.

2022-01-24 10:57 UTC, merged