Disable action submit button on submit
JoinColony/colonyDapp pull request #3133
Opened 2022-01-26 18:56 UTC by ArmandoGraterol

All the submit buttons which had a loading state when submitting should now be disabled instead of showing the primary color.

This includes all the submit buttons in the UAC, and some others like the one in the banning user dialog (So long as a button has a loading state, they are included).

Resolves #3124

2022-01-27 11:17 UTC, arrenv commented
@ArmandoGraterol is this one ready for review?

2022-01-27 14:35 UTC, ArmandoGraterol commented
> @ArmandoGraterol is this one ready for review?

@arrenv Oops, forgot to add reviewers! Thank you Arren

2022-01-27 15:48 UTC, arrenv approved these changes
Looks better to me!

### Before
![button-loader-before](https://user-images.githubusercontent.com/33682027/151393428-0fed84a9-c610-425f-82a2-9c074053a8e5.gif)

### After
![button-loader-after](https://user-images.githubusercontent.com/33682027/151393431-bf86832f-4484-4c1f-9770-9903ee60caa9.gif)

2022-01-27 15:55 UTC, ArmandoGraterol commented
@dit7ya You are right, we should also disable the fields to avoid any confusing behavior.

Tbh I don't think the users would expect that the transaction can be edited while submitting, it also sounds like a pain in the ass to implement hahaha I think so long as we disable the fields while submitting then it should be good

2022-01-29 01:36 UTC, chinins requested changes
Yeah, the inputs in the form need to be disabled - this was more the issue...

2022-02-02 03:43 UTC, chinins approved these changes
Nice work, looks like it's very comprehensive :)

2022-02-04 16:57 UTC, arrenv reviewed
@ArmandoGraterol works great!

Do you think there needs to be handling of rejected transactions? For e.g.

![handle-rejected-transaction](https://user-images.githubusercontent.com/33682027/152570307-6f76aada-3dc9-43b8-875e-584afba2dfff.gif)


Given you have gone to all the effort of disabling inputs, would there be any benefit in disabling the force toggle, in your opinion?

It does not seem to cause any issues with the transaction, it just keeps the dialog open.

![toggle-force](https://user-images.githubusercontent.com/33682027/152568177-280ccaee-f3b5-4896-a59f-401a14ac33b5.gif)

2022-02-07 15:14 UTC, ArmandoGraterol commented
@arrenv 

> Do you think there needs to be handling of rejected transactions? For e.g.

I think that this happens whenever an error occurs while making a transaction, not just when you reject transactions, well, at least I've seen this happens not just when you reject them. But yeah, I think we need to handle this.

> Given you have gone to all the effort of disabling inputs, would there be any benefit in disabling the force toggle, in your opinion?
> 
> It does not seem to cause any issues with the transaction, it just keeps the dialog open.

Oh nice, yeah I think it should also be disabled! I'm gonna change that

2022-02-08 00:02 UTC, merged