Fix/3159 usernavigation consistent styling
JoinColony/colonyDapp pull request #3164
Opened 2022-02-04 13:57 UTC by dit7ya

## Description

Made all font sizes to be `13px` and vertically align the reputation and notifications icon. Note: the notification icon is centered as perceived and not objectively - since it contains the notification dot. 

**Changes** 🏗

Just minor CSS changes.

![Screenshot 2022-02-04 at 19-15-21 Colony](https://user-images.githubusercontent.com/14034137/152539420-876408b3-2631-4ed8-a5a6-30d3b5687d51.png)

Resolves  #3159.

2022-02-04 14:23 UTC, arrenv requested changes
@dit7ya It looks like there are still some alignments for the fonts and sizing. This is from your screenshot

![font-alignments](https://user-images.githubusercontent.com/33682027/152545136-2e25656a-e023-4817-b745-c69029b7b79c.png)
.

2022-02-04 18:51 UTC, dit7ya commented
Things are getting a bit hacky but let's see.

![Screenshot 2022-02-05 at 00-20-23 Colony](https://user-images.githubusercontent.com/14034137/152586121-92689772-317e-49d2-916f-59f7453a0730.png)

2022-02-05 23:13 UTC, chinins reviewed
It's still not aligned on my machine... This might be the OS impacting it here. Maybe try to add line heights. I remember that we had icon alignment issue and I think that Arren fixed this by using line-heights...

<img width="456" alt="Screenshot 2022-02-05 at 17 11 03" src="https://user-images.githubusercontent.com/34057551/152662068-89e3fd31-5c74-44b1-b6b2-7d1db4e63099.png">

2022-02-23 13:23 UTC, dit7ya commented
Can someone with a Windows machine please take a look at this? I can do only so far with a slow iteration cycle.

2022-02-23 15:01 UTC, arrenv requested changes
@dit7ya I am on Windows, and still see the same issues.

- Text is not vertically centered
- The text does not align consistently with each other. (seems only reputation and balance align)

![text-alignment-2](https://user-images.githubusercontent.com/33682027/155345605-25f8b333-46d3-4de5-b5b8-5636a3f36db8.png)

2022-02-23 15:22 UTC, dit7ya commented
@arrenv Sorry, I meant to say, can someone with a Windows machine please complete this PR cause it is difficult for me to check whether something works. I can unassign myself.

2022-02-25 09:21 UTC, closed without merging