Add `Claim all` button with saga
JoinColony/colonyDapp pull request #3171
Opened 2022-02-07 21:34 UTC by ArmandoGraterol

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #3155

2022-02-08 18:22 UTC, arrenv commented
Hey @ArmandoGraterol, just confirming, this is only for the 'Claim all' button functionality. Not the copy next to the button or anything else?

2022-02-08 18:27 UTC, ArmandoGraterol commented
> Hey @ArmandoGraterol, just confirming, this is only for the 'Claim all' button functionality. Not the copy next to the button or anything else?

Uh I don't think so? Isn't that part of another issue?

2022-02-08 19:07 UTC, arrenv commented
@ArmandoGraterol I agree, it is not at all clear in the raised issue. I have updated it, it should include the "Your stakes" copy.

2022-02-08 19:56 UTC, ArmandoGraterol commented
> @ArmandoGraterol I agree, it is not at all clear in the raised issue. I have updated it, it should include the "Your stakes" copy.
> 
> I hope that is okay, otherwise, I will create a separate issue for it.

Done! Thank you for the clarification

2022-02-09 15:38 UTC, arrenv requested changes
@ArmandoGraterol really nice work. I like how you used the same saga.

I tested and everything seemed to work great. However, I tested it again so that I could do a screen record and the result was the following gif. I will restart my dev environment and test again though.

![claimable-transactions-not-working](https://user-images.githubusercontent.com/33682027/153235005-59319013-bed6-4503-a66c-32d36f829f8b.gif)

2022-02-09 16:28 UTC, ArmandoGraterol commented on src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.css
> +  font-size: --size-smallish;
Oh damn you are right! Thank you

2022-02-09 17:15 UTC, ArmandoGraterol commented
> I tested and everything seemed to work great. However, I tested it again so that I could do a screen record and the result was the following gif. I will restart my dev environment and test again though.

Please do so! I haven't been able to reproduce that

2022-02-10 11:36 UTC, arrenv commented
@ArmandoGraterol I have been testing this some more and the issue is with the `useClaimableStakedMotionsQuery` query.
Curerntly, you have to reload the app for the query to update, and it also includes motions that have been staked and not finalized.

I will create a separate issue for updating the resolver.

With this PR, do you think there needs to be feedback or fallback for if the transaction fails or can't be performed. For example, in the Network tab in console, when my gif above happens, I get this error.

`message: "VM Exception while processing transaction: revert voting-rep-motion-not-claimable"`

2022-02-10 18:10 UTC, arrenv commented
@ArmandoGraterol I have updated the resolver, which should help with this issue - https://github.com/JoinColony/colonyDapp/pull/3175

2022-02-10 18:19 UTC, ArmandoGraterol commented
> @ArmandoGraterol I have updated the resolver, which should help with this issue - #3175

Nice! I also added an extra, just in case, error that was missing from the saga, and added a query to update the claim list after claiming something with the saga. So, the case in your gif should now not happen

2022-02-11 10:41 UTC, arrenv reviewed
@ArmandoGraterol It is working great, nice!

With the changes I made to `useClaimableStakedMotionsQuery`  in https://github.com/JoinColony/colonyDapp/pull/3175 returning motions as opposed to just an array of motionIds, should we manage that in this PR or do another PR for it?

2022-02-11 14:18 UTC, ArmandoGraterol commented
> With the changes I made to `useClaimableStakedMotionsQuery` in #3175 returning motions as opposed to just an array of motionIds, should we manage that in this PR or do another PR for it?

I think it's more convenient if you merge yours first and then I update this one with the changes you made on that PR :)

2022-02-14 20:47 UTC, chinins approved these changes

2022-02-14 20:58 UTC, chinins approved these changes
Very nice work. 
I noticed that after claiming all I still have value in the staked pat of the token activation popover which resets to zero after I refresh. I think it would be good to refresh the query that provides these numbers (I think it's user lock query)  in the claimMotionRewards saga after the action success.
<img width="445" alt="Screenshot 2022-02-14 at 23 55 38" src="https://user-images.githubusercontent.com/34057551/153945056-a55afaa3-3846-4cbc-b988-22075602a5c0.png">

2022-02-15 14:16 UTC, ArmandoGraterol commented
> I noticed that after claiming all I still have value in the staked pat of the token activation popover which resets to zero after I refresh. I think it would be good to refresh the query that provides these numbers (I think it's user lock query) in the claimMotionRewards saga after the action success.

Oh yeah, I agree with you! I Thank you for bringing that up

2022-02-15 17:15 UTC, danbr commented on src/modules/users/components/TokenActivation/TokenActivationContent/StakesTab.tsx
> +    id: 'users.TokenActivation.TokenActivationContent.ClaimsTab.noClaims',
.ClaimsTab..... - but was renamed to StakesTab. I can update when i make my changes for the dialog.

2022-02-16 14:42 UTC, danbr approved these changes
nice work - was good for me to review, as i'll be rebasing off your PR and incorporating your changes with my PR.

2022-02-16 19:25 UTC, merged