Whitelisted modal content
JoinColony/colonyDapp pull request #3218
Opened 2022-02-28 14:44 UTC by alicjakujawa

## Description

This pr is adding content for whitelisted tab 

**New stuff** ✨

* UserCheckbox component
* WhitelistedAddresses component

**Changes** 🏗

* Refactored styles for Checkbox

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-03-08 18:01 UTC, ArmandoGraterol requested changes
Nice work! What about the no addresses state thought?

![FireShot Capture 548 - Verified Recipients – Figma - www figma com](https://user-images.githubusercontent.com/18473896/157297851-337bf2b4-a1e3-4757-82cf-b7b037bfa404.png)

It was mentioned in the issue that it's also included.

I think the items need to have more space between them, as per the specs:
![FireShot Capture 551 - Verified Recipients – Figma - www figma com](https://user-images.githubusercontent.com/18473896/157298071-67102e11-5b9f-423b-b277-011c249604dd.png)

Right now:
![FireShot Capture 550 - Colony - localhost](https://user-images.githubusercontent.com/18473896/157298094-e775423a-0a0e-457a-8ca4-7cde7ea3384f.png)

2022-03-08 20:53 UTC, arrenv requested changes
@alicjakujawa It is looking really good.

In addition to what Armando raised, I also noticed that the search filter does not reset after clearing the input. See gif below:

![search-filter](https://user-images.githubusercontent.com/33682027/157323129-f408a89d-0b79-47b7-bb38-85f8831b6f34.gif)

2022-03-09 09:25 UTC, alicjakujawa commented on src/modules/core/components/Fields/Checkbox/Checkbox.tsx
> +  }, []);
nope, i dont want additional deps here, i want fire it only once at the beginning

2022-03-09 09:28 UTC, danbr requested changes
UI looking pretty. 
The tooltips were temperamental. I found it difficult to make them appear. Without them, it's quite confusing to know which action is about to happen.

![manageWhitelist](https://user-images.githubusercontent.com/582700/157411775-7a7b4b82-9296-44c1-bbce-943ffdcf9d6e.gif)

Perhaps it is not covered in this PR (i'll add my comment, just in case), but the colour of the 'Confirm' button should be red.
<img width="516" alt="Screenshot 2022-03-09 at 16 05 03" src="https://user-images.githubusercontent.com/582700/157412237-e6c96eb9-a735-4a06-a493-1a2782f22bda.png">

2022-03-11 14:09 UTC, alicjakujawa commented
@danbr @ArmandoGraterol @arrenv Made updates. I will handle tooltip issue in separate PR to not block other tasks from this feature. Also currently we always display annotation field, later on when we implement logic for both tabs, we would need to also create logic when/how to display annotation (as it wont always display)

2022-03-14 17:39 UTC, ArmandoGraterol approved these changes
Looking good! I think all of the changes were addressed :+1:

2022-03-15 11:55 UTC, arrenv approved these changes
Looks good to me. Considering that the tooltip will be handled in another issue.

2022-03-15 15:23 UTC, merged