Incorporate network fees in Create Payment
JoinColony/colonyDapp pull request #3275
Opened 2022-03-29 13:55 UTC by dit7ya

## Description

This PR 

- displays the network fee in Create Payment Dialog
- Calls the network contract with the total amount (amount to be received + fees) so that the recipient simply gets the amount typed in the form.

![Screenshot 2022-03-29 at 19-11-40 Actions Colony - Notun](https://user-images.githubusercontent.com/14034137/160626786-97fa980d-c02e-4e79-97a7-9474c1d0b48a.png)

Resolves #3266.

2022-03-29 20:03 UTC, ArmandoGraterol requested changes
I like this change! It should definitely improve the UX

Something weird is happening tho:
![FireShot Capture 557 - Pay esotericdog 9 99999 PRR - Action - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/160697257-f624e191-db03-4161-a72d-0e1dfa95ed85.png)
![FireShot Capture 558 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/160697266-f133f279-5185-4c6e-adc5-3b944a3d950c.png)
![FireShot Capture 559 - Events - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/160697272-3e2dbf39-c5ae-4673-af44-998d2dc2f90a.png)

The amount shown in event and action list is different from the amount in the action page

2022-03-31 12:10 UTC, dit7ya commented
Good point @ArmandoGraterol. Fixed that in the last commit. 

One point worth noting is that now is no easy way for the payment initiator to know exactly how much they spent on a payment including fees.

2022-04-01 18:20 UTC, chinins reviewed
It looks ok, I just have a question about come number calculations.

2022-04-04 04:04 UTC, dit7ya commented on src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
> +    ? (1 / parseInt(networkFeeInverse, 10)) * 100
Ummm, I thought feeInverse is generally a small number and `parseInt` should work okay unless the fee percentage is smaller than like `10^-15` or so. I can use `bigNumberify` here anyway if you want.

2022-04-04 04:04 UTC, dit7ya commented on src/modules/core/components/ActionsList/ActionsListItem.tsx
> +    ? (1 / parseInt(networkFeeInverse, 10)) * 100
Same :point_up:

2022-04-05 09:44 UTC, arrenv requested changes
The design seems off when comparing to the design. There is no colon punctuation mark in the design, the font is more consistent in weight and size, and is closer to the the input field. See following comparison.

![network-fee](https://user-images.githubusercontent.com/33682027/161726736-7068c3c0-d2bb-49a5-8362-5c901e647ddf.jpg)

2022-04-05 09:44 UTC, arrenv commented on src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
> +    ? (1 / parseInt(networkFeeInverse, 10)) * 100
I feel as though it would be better to better support large numbers.

2022-04-05 10:24 UTC, dit7ya commented
@arrenv Thanks for the comments.

I will change the font weight. However, IMO the colon is consistent with the Available Funds subtitle. What do you think?

About the spacing - it is the same spacing as the Available Funds subtitle (which is also not following the spec). Do you want me to change both? If yes, what do you suggest to deal with the conflict with the insufficient balance warning? 
![2022-04-05_15-48](https://user-images.githubusercontent.com/14034137/161733051-5cba4286-64f1-4ccb-b91b-04225376e7f8.png)

2022-04-05 11:54 UTC, arrenv commented
> IMO the colon is consistent with the Available Funds subtitle. What do you think?

I agree with you, good observation.

> About the spacing - it is the same spacing as the Available Funds subtitle (which is also not following the spec). Do you want me to change both? If yes, what do you suggest to deal with the conflict with the insufficient balance warning?

Another good pickup. It seems there is no decided solution for this after to chatting to Karol. One idea though was to have only one visible at a time, i.e. either the error message or the sub-text be visible at any given time. Although, that would be a separate issue to this. For the purpose of this PR, what you have makes sense.

2022-04-07 15:08 UTC, ArmandoGraterol reviewed
Now the amount shown in the action list seems to be after fees so good work! However, I still found something that might be confusing:
![FireShot Capture 564 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/162230221-1701c1a6-a837-44ad-8467-8c323761782b.png)
![FireShot Capture 565 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/162230234-f5075e95-6bb2-4cd5-838d-a44ff577892d.png)
![FireShot Capture 566 - Pay esotericdog 10 99999 PRR - Action - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/162230246-3bd25a85-41c2-4312-9a36-b195c9754c8f.png)

I paid myself 10 and 11 tokens, when I went to the action page or to the token activation popover I see that it's shown as 9.9999... and 10.999... which is a different amount than what we show in the action list.

So from this, I have questions, is the amount shown on the action page/token activation popover the real value, and the one shown in the action list is rounded up? Or is the value in the action page/token activation popover wrong?

2022-04-07 16:07 UTC, arrenv commented
@dit7ya Yeah, I am seeing the same as Armando, it seems as though it has reverted back to how it was originally. And ignoring the fee, despite showing it.

2022-04-07 16:18 UTC, dit7ya commented
@ArmandoGraterol I will take a look at the rounding tomorrow and do the needful. @arrenv What do you mean by it has gone back to how it was? I did some tests and it seems like it is just the rounding error of `0.00001` instead of `1%` decrease like before.

2022-04-07 16:28 UTC, arrenv commented
> @ArmandoGraterol I will take a look at the rounding tomorrow and do the needful. @arrenv What do you mean by it has gone back to how it was? I did some tests and it seems like it is just the rounding error of `0.00001` instead of `1%` decrease like before.

I think it is just to do with the rounding errors.

2022-04-08 09:56 UTC, dit7ya commented
@ArmandoGraterol @arrenv Figured that out. It was happening because the contract adds an extra 1 Wei of fee after the percentage calculation. For large amounts it was getting rounded in the UI (but not actually in the wallet balance).

Changed the calculation equation and it should be good now.

![2022-04-08_15-23](https://user-images.githubusercontent.com/14034137/162412561-f9d5839e-24ab-44f8-b735-40eed638eb35.png)

2022-04-08 13:32 UTC, arrenv approved these changes
Working for me now, nice work!

2022-04-08 17:24 UTC, ArmandoGraterol approved these changes
Nice work!  It's looking good in every place that I could check

2022-04-11 07:36 UTC, chinins approved these changes
Looking good now - nice work!

2022-04-11 07:52 UTC, merged