Fix/3461 magnify icon
JoinColony/colonyDapp pull request #3470
Opened 2022-06-10 16:03 UTC by willm30

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-06-10 16:29 UTC, chinins requested changes
The height of the icon is not correct as per my comment.

2022-06-10 16:29 UTC, chinins commented on src/modules/dashboard/components/Members/MembersTitle.css
> +  height: 13.33px;
The icon should actually be 20 px as per figma file. The 13.3 px is only if you select the circle only.
Generally, we try to never use decimals for pixels as well.
<img width="1097" alt="Screenshot 2022-06-10 at 18 27 06" src="https://user-images.githubusercontent.com/34057551/173110273-b7aa3e2b-8d84-4ef6-8238-aea6df7356a2.png">

2022-06-13 08:55 UTC, willm30 commented
> The height of the icon is not correct as per my comment.

Thanks for pointing out, have now fixed.

2022-06-13 10:37 UTC, rdig approved these changes
Seems fine now

2022-06-13 17:23 UTC, dit7ya approved these changes
LGTM.

2022-06-15 06:27 UTC, chinins approved these changes
All good now!

2022-06-15 11:52 UTC, merged