Fix: include @ symbol in user search
JoinColony/colonyDapp pull request #3472
Opened 2022-06-13 10:00 UTC by willm30

## Description

This PR includes the @ symbol in user searches, so you can search for a user like "@will" as well as simply "will". 

**Changes** 🏗

- [x] Add '@' symbol to user selection filter

## Screenshot

**_Previously, starting a search with the @ symbol would not return the selected user._**

![at-symbol-user-search](https://user-images.githubusercontent.com/64402732/173329522-e454f935-4a37-48cd-a9b8-733d139d565c.gif)

Resolves #3462

2022-06-13 10:52 UTC, rdig requested changes
The `@` filtering logic is fine, however, the `user` object existence checks are not

2022-06-13 10:52 UTC, rdig commented on src/modules/core/components/SingleUserPicker/utils.ts
> +    const { username } = user.profile;
The user object might not exist ?

```suggestion
    const { username } = user?.profile;
```

2022-06-13 10:52 UTC, rdig commented on src/modules/core/components/SingleUserPicker/utils.ts
>        user.profile &&
Aren't you already checking for it's existence above? 

You should just check for `username` in this instance, which should be enough.

2022-06-13 11:37 UTC, willm30 commented
> The `@` filtering logic is fine, however, the `user` object existence checks are not

Should be better now.

2022-06-13 11:50 UTC, rdig approved these changes
Good with it now, however I did find more stuff to nitpick about :)

2022-06-13 11:50 UTC, rdig commented on src/modules/core/components/SingleUserPicker/utils.ts
> +        user.id.toLowerCase().includes(filterValue.toLowerCase()))
I'm going to nitpick some more :P

Why call `filterValue.toLowerCase()` three times ? It won't change, so why not assign it to a variable, and use that for checks ?

```suggestion
      (`@${username}`.toLowerCase().includes(valueToLoweCase) ||
        walletAddress.toLowerCase().includes(valueToLoweCase) ||
        user.id.toLowerCase().includes(valueToLoweCase))
```

2022-06-13 11:50 UTC, rdig commented on src/modules/core/components/SingleUserPicker/utils.ts
> +        user.id.toLowerCase().includes(filterValue.toLowerCase()))
`user.id` is the same as `walletAddress`, so there's no point in filtering by it two times. Just remove one of them

2022-06-13 12:49 UTC, rdig approved these changes
Very nice! Much cleaner now.

Sorry for all the back and fourth :)

2022-06-13 15:15 UTC, will commented
> a user like "@will"

:(

2022-06-13 15:18 UTC, rdig commented
> > a user like "@will"
> 
> :(

Haha. Be careful who you ping @willm30 :stuck_out_tongue:

2022-06-15 06:39 UTC, chinins approved these changes
Very nice and clean1

2022-06-15 12:07 UTC, merged