Feature/3441 locked values
JoinColony/colonyDapp pull request #3473
Opened 2022-06-13 12:35 UTC by agnieszkajarosikloj

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves to #3441

2022-07-01 12:49 UTC, arrenv requested changes
@agnieszkajarosikloj 

1. There are some issues with the validation, for example, the Team, Token and period select options invalidate incorrectly if you don't change them, even if they have their default selections. 

2. The Team field seems to default to the last in the list, when it should be the first in the list.

![694701a0-f4d5-4170-ad85-d0960b0ee4e4](https://user-images.githubusercontent.com/33682027/176894323-a887c42b-a1ef-4762-9a95-2ee470bc4930.png)

3. The 'Claim delay' field is optional and does not need a required validation.

4. The recipient validation can just change the blue icon to red, instead of having the text.

5. There should be validation on the Value field, which should just sit under the input.

6. I think that the token values style and claim delay should be updated to match the style of the balance values, i.e. the same font-weight, size and line-heights.

![08b67acb-9cc6-42d0-9fb6-5a25be5db0d5](https://user-images.githubusercontent.com/33682027/176895544-30ce1d41-ddca-4ce0-a5a7-ce0fdf62b520.png)

7. This hover state and title tag are not needed.

![Screenshot 2022-07-01 144158](https://user-images.githubusercontent.com/33682027/176896622-4674fe36-7a3a-4154-b277-cabbda32b70f.png)

2022-07-01 12:49 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Delay/Delay.tsx
> +export default Delay;
After seeing how this needed to be implemented, it is not really necessary to have the shortened version of the time period. We can just have the full time period label for each.

2022-07-01 12:49 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
> +
This can be removed.

2022-07-01 12:49 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/LockedExpenditureSettings.css
> +  background-color: rgb(229, 230, 247);
Can we please replace all instances of this color with this variable `--grey-blue-1`

2022-07-01 12:49 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.css
> +  background-color: rgb(229, 230, 247);
Can we please replace all instances of this color with this variable `--grey-blue-1`

2022-07-05 14:31 UTC, arrenv requested changes
@agnieszkajarosikloj, thank you.

There looks to be some alignment issues, as well as a error with the unique key.

![7aee2356-ff72-4f88-90ab-bbdfcfc79a2e](https://user-images.githubusercontent.com/33682027/177350164-7add6931-7cf4-4226-977a-b9fda8e0cd79.png)

In the locked state, in the title, the claim delay would be better with a space between the number and the period.

![3843aa65-559f-4750-b3bd-bbd02dc1ccab](https://user-images.githubusercontent.com/33682027/177350516-c52e5428-8718-4fdd-8b58-a9a0c72327bb.png)

2022-07-06 10:18 UTC, arrenv approved these changes
Thank you @agnieszkajarosikloj. Please see some comments below.

Can we please have these paddings in the minimised locked state match the minimised state in the non-locked state.

### Locked

![download (46)](https://user-images.githubusercontent.com/33682027/177527479-db814678-a305-48d1-84d0-df043d713be9.png)

### Unlocked

![download (47)](https://user-images.githubusercontent.com/33682027/177527491-1e0496e4-1937-4e25-bf54-68fb094c9278.png)

2022-07-13 15:52 UTC, willm30 commented
@agnieszkajarosikloj Not suggesting this is a problem with your implementation, but I found the validation in this form too subtle to be useful. I had validation errors after clicking `Submit draft` and had to put `console.logs` in the code to figure out what they were. The pink highlighting of the relevant fields didn't sufficiently draw my attention, and in the case of the `Expenditure Title` field, it tells you _that_ something is wrong but not _what_ (i.e. it requires a title of at least three characters). 

I personally would prefer specific messages under the input fields, as I've become acustomed to in the rest of the app. (e.g. "Enter a title of at least three characters" or similar). 

That aside, I can confirm that form values can't be edited once the values have been locked. 

Also, not sure if it's in scope, but deleting the expenditure doesn't update the UI, which is also confusing because I clicked the button a few times and nothing happened. Refreshing does update the UI, but it would be better to not have to manually refresh the window.

2022-07-13 19:41 UTC, arrenv commented
> @agnieszkajarosikloj Not suggesting this is a problem with your implementation, but I found the validation in this form too subtle to be useful. I had validation errors after clicking `Submit draft` and had to put `console.logs` in the code to figure out what they were. The pink highlighting of the relevant fields didn't sufficiently draw my attention, and in the case of the `Expenditure Title` field, it tells you _that_ something is wrong but not _what_ (i.e. it requires a title of at least three characters).
> I personally would prefer specific messages under the input fields, as I've become acustomed to in the rest of the app. (e.g. "Enter a title of at least three characters" or similar).

Good feedback regarding validation, this is a product issue, that we will need to address separately.

> That aside, I can confirm that form values can't be edited once the values have been locked.
> 
> Also, not sure if it's in scope, but deleting the expenditure doesn't update the UI, which is also confusing because I clicked the button a few times and nothing happened. Refreshing does update the UI, but it would be better to not have to manually refresh the window.

This is out of scope of this feature at the moment. This is all UI only.

2022-07-14 08:54 UTC, willm30 approved these changes

2022-07-14 09:27 UTC, merged