Align Colony Icons with User Avatar and Menu
JoinColony/colonyDapp pull request #3485
Opened 2022-06-13 18:39 UTC by willm30

## Description

This PR is the feature for a mobile responsive Colony Home page. 

**New stuff** ✨

- [ ] Align Colony Avatars with User Avatar and Hamburger Menu

## TODO

Sections To Complete:

- [ ] Colony Avatars / User Avatar / Hamburger Menu
- [ ] Colony Info / Join Colony
- [ ] Funds info / manage funds
- [ ] Actions summary

Resolves #3475

2022-06-15 18:08 UTC, dit7ya commented
This is huge, whoa! Are we sure there is no other simpler way to achieve this without external libraries? (It might very well be the case but I am just double-checking).

2022-06-16 08:34 UTC, willm30 commented
> This is huge, whoa! Are we sure there is no other simpler way to achieve this without external libraries? (It might very well be the case but I am just double-checking).

I went for [react-responsive](https://github.com/yocontra/react-responsive) mainly for peace of mind. We could write our own hook to detect screen size I guess but using the library was quicker and probably more reliable short-term (better tested).

I guess we generally try to avoid external libraries where possible?

2022-06-17 11:28 UTC, rdig requested changes
This is mostly good and kudos to you for the amount of work you've put in. :100: 

Other than what I've picked up in the review _(see comments)_, there's also some other things need discussing:

1. We've changed the design specs for the _Joined Colonies_ list, so your implementation is no longer up to spec. You can tackle it here, or in a separate PR, up to you.

2. There's a discussion on how tread intermediate view port sizes, and if we should cater to them _(ie: tablets / smaller laptops)_, since the view is good for vertical view phones, >1200 desktop sizes, but broken for everything in between.

So I'd suggest the 3 of us _(me, you, Arren)_ get together in a call an hash this out.

2022-06-17 11:28 UTC, rdig commented on src/modules/pages/components/RouteLayouts/Default/Default.tsx
> +            )
Please try to reduce code repetition as much as possible:
```suggestion
const SubscribedColonies = () => hasSubscribedColonies ? (
    <div className={styles.coloniesList}>
      <SubscribedColoniesList />
    </div>
  ) : null;

{isMobile ? (
  // Render the UserNavigation and SubscribedColoniesList in shared parent on mobile
  <div className={styles.head}>
    <div className={navStyles.nav}>
      <UserNavigation />
    </div>
    {SubscribedColonies()}
  </div>
) : SubscribedColonies()
```

2022-06-18 13:37 UTC, willm30 commented on src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
> +          className={styles.joinButton}
This I saw after I submitted the PR and addressed it in the other PR I submitted. Am I ok to leave it in the other one?

2022-06-18 13:38 UTC, willm30 commented
> 1. We've changed the design specs for the _Joined Colonies_ list, so your implementation is no longer up to spec. You can tackle it here, or in a separate PR, up to you.

I will address it in a separate PR.

2022-06-19 15:57 UTC, willm30 commented
@rdig I have implemented the changes requested, ready for a re-review and updated the PR body (inc updated screenshots). Will split out screen 2 (joined colonies list) into separate PR.

2022-06-21 17:42 UTC, arrenv approved these changes
It is looking good to me, just a couple of comments.

2022-06-21 17:54 UTC, willm30 commented on src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
> +          className={`${styles.createUserRedirect}`}
Good spot

2022-06-21 20:04 UTC, rdig approved these changes
All good now. Nice work Will! :tada:

2022-06-21 20:07 UTC, rdig commented
Also @willm30 as per Github's specs liked issues should be one per line.

So this:
![Screenshot from 2022-06-21 23-05-44](https://user-images.githubusercontent.com/1193222/174888196-6d06275d-a880-48d8-85ba-97fa3f4644ce.png)

Should be written as:
```
Resolves #3475
Resolves #3486
Resolves #3495
Resolves #3499
```

See more: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2022-06-22 08:30 UTC, merged