Add Remove Safe Dialog
JoinColony/colonyDapp pull request #3496
Opened 2022-06-14 20:21 UTC by danbr

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #3449

2022-06-21 14:16 UTC, arrenv requested changes
Nice one @danbr. A couple of things I noticed.

The validation didn't seem to work for me when I had only one Safe but not selected.

![validation-not-working](https://user-images.githubusercontent.com/33682027/174817648-631f3006-7471-4c2e-81cd-76ae1ed0ce87.gif)

The spec shows a height of `42px` per Safe, while this is showing a height of `50px`.

![Screenshot 2022-06-21 160343](https://user-images.githubusercontent.com/33682027/174819484-36e46db7-85da-403e-931e-450609060bec.png)

![50cbb9bc-7120-4b78-b540-99d6dba34424](https://user-images.githubusercontent.com/33682027/174819495-0dfaafbb-3e1f-4d1a-875d-75d4d60abd64.png)

2022-06-21 14:16 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
> +const safes: Safe[] = [
I think it would be good to put a comment here for this mock data, so, that we know to remove it in future.

2022-06-21 14:16 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
> +    defaultMessage: 'Remove safe',
Although, not in the spec, I think that "safe" should be capitalised here to "Safe". Given it is a name.

2022-06-21 14:16 UTC, arrenv commented on src/styles/variables.css
> +  --temp-grey-blue-9: rgb(200, 214, 245); /* Used for Safe Control Checkbox */
Let's remove this and instead use `--temp-grey-blue-4` which matches it pretty well.

2022-06-22 06:30 UTC, danbr commented
> @arrenv Thanks for the comments. I've addressed them all as requested.

2022-06-22 07:28 UTC, arrenv approved these changes
Looks good to me!

2022-06-22 10:12 UTC, chinins commented on src/modules/dashboard/components/Dialogs/RemoveSafeDialog/types.ts
> +}
Safe will also have chain property

2022-06-22 10:13 UTC, chinins commented on src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.tsx
> +        {safe.name}
As far as I understand the display name is a combination of name and chain so it should be `${safe.name}} (${safe.chain})`

2022-06-22 23:41 UTC, ArmandoGraterol approved these changes
Looking great Dan! Other than Olga's comments, for me, this is good to go

2022-06-26 18:23 UTC, merged