add ability to claim expenditure
JoinColony/colonyDapp pull request #3527
Opened 2022-06-22 10:48 UTC by agnieszkajarosikloj

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-06-22 10:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3527) it.</sub>

2022-07-20 10:19 UTC, willm30 requested changes
@agnieszkajarosikloj Hey, I leave a few notes for your attention. 🙂

1. When you don't enter any delay, I would expect the delay to say "None" and there be something to claim immediately. Below, there is nothing to claim and no delay at all is shown.
![no-delay](https://user-images.githubusercontent.com/64402732/179957044-61756943-9754-49a5-bc5f-9179c6ddec13.png)

1. There is an icon next to the payments heading in the design that is missing
![payments-icon](https://user-images.githubusercontent.com/64402732/179957052-7c4a2829-6071-482d-b143-bafd0d885706.png)

1. The "completed" button differs from design (although I personally feel your implementation looks fine. Just bringing to your attention in case it wasn't intentional).
![completed](https://user-images.githubusercontent.com/64402732/179957057-2c3ba981-ec85-4f7d-bbbc-fd525b814fb1.png)

1. There are funds that can be claimed now, but the section header says "nothing to be claimed". Also, when there are multiple tokens, the 'value' label hugs the bottom of the container where it should probably either be centered or stay at the top.
![claim-now](https://user-images.githubusercontent.com/64402732/179957067-d1685009-e2d1-48e3-950e-479e3a4f7ae6.png)

1. Hours are displayed differently to the design
![hrs-expenditures](https://user-images.githubusercontent.com/64402732/179957070-712dbc51-667c-4b2f-a5e6-c3012dead083.png)

1. Probably shouldn't be able to enter the same coin more than once
![duplicate-coin](https://user-images.githubusercontent.com/64402732/179957072-56f752ef-39e2-421c-8c75-cbc975702f3e.png)

2022-07-21 08:47 UTC, agnieszkajarosikloj commented
<img width="285" alt="Screenshot 2022-07-21 at 10 34 49" src="https://user-images.githubusercontent.com/91876137/180169353-88bd86e9-509b-47e4-b8ba-24520ab82fcd.png">
I've used here FormattedRelativeTime component from Format.js and it's default formatting, when the style is set to "short".
<img width="436" alt="Screenshot 2022-07-21 at 10 46 03" src="https://user-images.githubusercontent.com/91876137/180171640-f1b0afbd-a8be-401c-b510-989759aa4bc1.png">
Can it stay this way or does it have to be exactly the same as in the design?

2022-07-21 09:12 UTC, arrenv commented
> The "completed" button differs from design (although I personally feel your implementation looks fine. Just bringing to your attention in case it wasn't intentional).

This one is not intended to be a button, it is intended to be a tag/pill component. As being completed, there is no more actions to do and thus a button is not required. So, this should be updated to the design.

> There are funds that can be claimed now, but the section header says "nothing to be claimed". Also, when there are multiple tokens, the 'value' label hugs the bottom of the container where it should probably either be centered or stay at the top.

We can have this say "Now" if there is no timeout, so, that it is consistent as a time indicator.

> Hours are displayed differently to the design

This has something that was brought up previously. Can we just make it all long format for now @agnieszkajarosikloj plese, i.e. minutes, hours, days, months.

> Probably shouldn't be able to enter the same coin more than once

This one is not too big of an issue, I don't think we need to do check for this.

2022-07-21 11:36 UTC, arrenv requested changes
@agnieszkajarosikloj looks good, thank you.

Could we please have this timer as the lowest time, i.e. this should show `Now`.

![9cc199b8-501c-4f94-8212-54dfcd6932a6](https://user-images.githubusercontent.com/33682027/180181297-2755bddf-e5c5-4d6c-9ea1-8ececca4638a.png)

Can the padding here be more consistent to match the design:

![b5a44834-a9cc-4717-8bbf-d3ae8af3fc88](https://user-images.githubusercontent.com/33682027/180182904-5ac65735-f278-47df-a20e-455dc11a2e2b.png)

**Design**

![Screenshot 2022-07-21 114040](https://user-images.githubusercontent.com/33682027/180183037-0af04597-75c3-409c-a7e3-79ba5c7bf3c5.png)

2022-07-27 14:50 UTC, chinins requested changes
Huge PR - nice work. Some changes needed for the data handling - as per my comments.

2022-07-27 14:50 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
> +                    unit={getTokenDecimalsWithFallback(0)}
it should be token.decimals as an argument to call this function

2022-07-27 14:50 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
> +  const convertToTokensWithIds = useMemo(
I think this is unnecessary. You can just use nanoid() as key when you call numeral.

2022-07-27 14:50 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
> +interface TokenWithId {
We have a type for token `Token` or `AnyToken`. You can remove any fields that wouldn't be used. I made a log and I see all of this for token:
```
{
token:
address: "0x47b3CfC8EeaEae8Ad83845a19112BeA8ca961fb8"
decimals: 18
iconHash: null
id: "0x47b3CfC8EeaEae8Ad83845a19112BeA8ca961fb8"
name: "b"
processedBalances: (4) [{…}, {…}, {…}, {…}]
symbol: "B"
__typename: "Token"
}
```

2022-07-27 14:50 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
> +  totalClaimable?: Token;
I think that you should pass an array if there are several tokens/amounts per user (which I can see is possible). Then you won't need any supplementary functions.

2022-07-27 14:50 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
> +    totalClaimable,
I think that all of the about should be an array of objects if there are several tokens/amounts per recipient. Then you don't need to create arrays from them later.

2022-07-28 14:07 UTC, willm30 approved these changes
Looking good from my side

2022-07-29 16:02 UTC, Julianahlk requested changes
Question, should this cancel expenditure button still be active in the following steps?

<img width="456" alt="Screen Shot 2022-07-29 at 5 25 30 PM" src="https://user-images.githubusercontent.com/71563622/181798627-26a81730-a074-4144-93d7-14c08143473c.png">
<img width="419" alt="Screen Shot 2022-07-29 at 5 30 09 PM" src="https://user-images.githubusercontent.com/71563622/181798649-cc8b09b7-9b67-418b-99c9-cdaa7c55b2d4.png">

Also, I noticed when I do not add a value for the first recipient I do get an error message for not adding anything to the input field

<img width="438" alt="Screen Shot 2022-07-29 at 5 35 37 PM" src="https://user-images.githubusercontent.com/71563622/181798789-2ff0ab01-977b-4a91-b128-7783a542ae77.png">

But when I don't add a value to the second recipient I do not see any warning error in the input field so it was difficult to see what I was missing. 

<img width="432" alt="Screen Shot 2022-07-29 at 5 35 55 PM" src="https://user-images.githubusercontent.com/71563622/181799404-70af38c6-75e4-42e4-8923-b71f7df16648.png">

2022-07-29 17:04 UTC, arrenv commented
> Question, should this cancel expenditure button still be active in the following steps?

Yes, cancelling an expenditure can be done all through, even through the Claiming stage. Just not after it has been fully claimed.

2022-08-01 09:30 UTC, agnieszkajarosikloj commented
> Also, I noticed when I do not add a value for the first recipient I do get an error message for not adding anything to the input field

By default, the Input component does not display an error message when field isn't touched. I've added setting touched value for this input in Formik, so now error message should be displayed after clicking submit button.

2022-08-02 08:10 UTC, Julianahlk approved these changes
The input field errors work as I expected now. Thank you for making the changes @agnieszkajarosikloj all good from my end now 👍.

2022-08-02 19:05 UTC, chinins requested changes
Much better now -very nice. There are still some things to clean up. Please, update and comment once it's ready . I'll try to prioritise the review and respond quickly.

2022-08-02 19:05 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/TimeRelativeShort/TimeRelativeShort.tsx
> +const displayName = 'TimeRelative';
Please, update the display name:
`dashboard.ExpenditurePage.TimeRelativeShort`

2022-08-02 19:05 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/TimeRelativeShort/TimeRelativeShort.tsx
> +        // eslint-disable-next-line react/style-prop-object
I don't think that there is a need for the `eslint-disable-next-line` here. When i removed it i didn't have any warning,

2022-08-03 07:37 UTC, agnieszkajarosikloj commented
> Much better now -very nice. There are still some things to clean up. Please, update and comment once it's ready . I'll try to prioritise the review and respond quickly.


@chinins I've just added fixes

2022-08-03 13:24 UTC, chinins approved these changes
Very nice! Just remember to add the enum for the `advanced` string where I left the comment before merging.

2022-08-03 13:24 UTC, chinins commented on src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
> +  expenditure: 'advanced',
You need to use the created enum here as well.

2022-08-08 17:36 UTC, arrenv approved these changes
@agnieszkajarosikloj thanks for your hard work on this. Looks good.

2022-08-09 07:04 UTC, merged