Add UI to remove expenditure draft
JoinColony/colonyDapp pull request #3561
Opened 2022-06-29 21:01 UTC by agnieszkajarosikloj

## Description

UI part of deleting expenditure draft. 
<img width="940" alt="Screenshot 2022-06-29 at 22 37 56" src="https://user-images.githubusercontent.com/91876137/176540380-68f881e7-5921-4cb8-a82d-e0281d03fed6.png">

[Figma link:](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=2875%3A335017)

**New stuff** ✨

* DeleteDraftDialog
* action after clicking 'Share' icon
* tooltips for icons and button

## TODO

- backend action after clicking delete draft

Resolves  #3544

2022-06-29 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3561) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3561) it.</sub>

2022-06-30 07:16 UTC, danbr approved these changes
Looking good.
I left a couple of minor comments, but approving, well done.

2022-06-30 07:16 UTC, danbr commented on src/modules/dashboard/components/Dialogs/DeleteDraftDialog/DeleteDraftDialog.css
> +  composes: themeDanger from '~core/Button/Button.css';
Figma uses pink color for button (very similar to danger)

2022-07-01 08:58 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj, only a couple of things.


Can we improve the alignment of the icon and hover state.

![download (31)](https://user-images.githubusercontent.com/33682027/176861820-50414682-6b09-4d3a-acef-777b11af1f46.png)

This is the design:
![Screenshot 2022-07-01 105313](https://user-images.githubusercontent.com/33682027/176861306-b6eaa756-2f74-47a0-99af-dcb5fd51dac7.png)

Also, please update the copy to the design:

![Screenshot 2022-07-01 105541](https://user-images.githubusercontent.com/33682027/176861587-48cdd425-be84-45ef-af82-1d4558941e19.png)

2022-07-05 14:38 UTC, arrenv approved these changes
Thank you @agnieszkajarosikloj, looking good to me!

2022-07-05 21:23 UTC, merged