Add multi-transaction functionality to Gnosis Safe Control dialog
JoinColony/colonyDapp pull request #3607
Opened 2022-07-08 22:12 UTC by ArmandoGraterol

Added the possibility of creating multiple transactions to the safe control dialog. Each transaction should now be inside a tab that can be opened, closed, and/or deleted.

The validation of the form should also now be dynamic and adapt to the different numbers of transactions and disable the submit button if the validation fails in any of the transactions.

![FireShot Capture 657 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/178076407-6fbf8d7c-5605-42b1-ba31-c44ccb61949a.png)
![FireShot Capture 658 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/178076430-d22d94c0-55fa-40ff-9148-07f1e4fcc62b.png)

Resolves #3563

2022-07-11 10:51 UTC, willm30 requested changes
Carets could be aligned: 

![align-carets](https://user-images.githubusercontent.com/64402732/178247978-113a1f3d-ffc3-4a7a-8c97-46142555d9f3.png)

Validation message should be user-friendly:

![err-msg](https://user-images.githubusercontent.com/64402732/178247091-fd0d4cbf-427f-4e1e-9ebb-e98072ca7e9b.png)
![err-msg2](https://user-images.githubusercontent.com/64402732/178247143-0f7cd9de-21ba-4cc3-b591-028864db11ed.png)

Is there anyway to stop my browser from thinking this is a residential address input? The autofill is overlaying the wallet addresses. 

![form-val](https://user-images.githubusercontent.com/64402732/178247205-a2b6a68b-a4fc-44b2-bf51-de8e3979cad7.png)

When you have two transactions and you delete the first one, they both disappear and the form becomes un-interactive.  

![multi-trans](https://user-images.githubusercontent.com/64402732/178247493-ca8b3bc5-1282-4af9-b764-9a9ce1a8854b.gif)

When you have two of the same transaction and delete the second one, they both disappear, and then when you click "add another transaction", the first one reappears. 

![double-trans](https://user-images.githubusercontent.com/64402732/178247718-62ab9a82-c32d-495b-ba84-726a118c5467.gif)

2022-07-11 18:42 UTC, ArmandoGraterol commented
> Carets could be aligned:
> 
> ![align-carets](https://user-images.githubusercontent.com/64402732/178247978-113a1f3d-ffc3-4a7a-8c97-46142555d9f3.png)

I've improved the alignment of the carets in the tabs relative to the carets in the select fields, as they are aligned in the specs, however the rest I'll leave as they are because changing them implies changing the SVG or core components, which is something that I already did in #3506 (Not on this feature branch) and it is quite a painful process :)

2022-07-12 10:08 UTC, willm30 approved these changes
Working as expected! Just made a note about wrapping the Form in an actual `<form>` tag, as I believe this is necessary for the `autocomplete='off'` to work on the individual inputs (or, at least, this is the behaviour I encountered in my local environment).

2022-07-12 13:57 UTC, danbr approved these changes
Looks good overall, just a couple of minor points.... to check/add - but I'll approve. Well done.

Should the confirm button copy display 'Interact' or 'Create transaction'? 
<NEWSFLASH> @chinins just told me that she already encountered this discrepancy, and as expected - you correctly used the appropriate option (well done you)

`Max` button missing from amount.......
FIgma
<img width="594" alt="Screenshot 2022-07-12 at 16 48 06" src="https://user-images.githubusercontent.com/582700/178506623-84e07ed8-aa30-4968-923a-fd16db79d6b6.png">

2022-07-12 16:48 UTC, ArmandoGraterol commented on src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
>      <>
Hmmm, we do not support Brave, only Google Chrome. I know that Brave is based on Chrome but as we can see here, there are differences.

When you are testing or developing things, I would advise you to use Google Chrome as that's officially the only browser that Colony is developed in, and to.

2022-07-12 16:58 UTC, ArmandoGraterol commented
> Should the confirm button copy display 'Interact' or 'Create transaction'?
> @chinins just told me that she already encountered this discrepancy, and as expected - you correctly used the appropriate option (well done you)

Ah, yes, just as I planned all along (??

> Max button missing from amount.......

I didn't include it the first time because I saw that the other amount fields for tokens that we have don't max buttons, so for consistency's sake, I left it like that, but yeah I can include it and if it doesn't make sense later then we can just remove it :)

2022-07-12 16:59 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
>      <>
Ok good to know

2022-07-12 17:56 UTC, merged