add cancel expenditure dialog
JoinColony/colonyDapp pull request #3618
Opened 2022-07-13 07:20 UTC by agnieszkajarosikloj

## Description

- This PR adds the ability to cancel expenditures, including the dialog with the "Penalize" and "Show mercy" options. UI only.

**New stuff** ✨

* CancelExpenditureDialog
<img width="556" alt="Screenshot 2022-07-13 at 09 19 37" src="https://user-images.githubusercontent.com/91876137/178674470-7ae2a1d2-eb49-42b7-8b29-88e9cac70e3f.png">

* LinkedMotions component
<img width="453" alt="Screenshot 2022-07-13 at 15 57 18" src="https://user-images.githubusercontent.com/91876137/178751460-47cc873b-a644-44a7-b0df-cb89139cc0de.png">

## TODO
* Add calls to the backend
* Remove unnecessary setTimeout and setStates from handleCancelExpenditure function

Resolves #3536

2022-07-13 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3618) it.</sub>

2022-07-13 16:18 UTC, willm30 requested changes
Looking good! Would personally say remove this tooltip if that's all it's going to say, as adds nothing to this modal.

![tooltip](https://user-images.githubusercontent.com/64402732/178782258-280508ec-8576-4a98-b12c-bf0a587042b9.png)

2022-07-20 09:30 UTC, willm30 approved these changes

2022-07-20 09:33 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureDialogForm.tsx
> +          <div className={styles.tokensWarpper}>
Typo here in class name, fyi

2022-07-20 09:36 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureDialogForm.tsx
> +            close();
Should these be removed in this pr or a future one?

2022-07-22 14:06 UTC, chinins requested changes
Please, implement the changes left in my separate comments.

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
> +  status: 'passed' | 'failed' | 'pending';
It should be an enum here

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
> +        {status === 'pending' && motionLink ? (
Should all be enums

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
> +            text={status === 'passed' ? MSG.passed : MSG.failed}
ditto

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
> +                status === 'passed' ? styles.passedColor : styles.failedColor,
ditto

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
> +  status: 'passed' | 'failed' | 'pending';
You already have it declared, you just need to use it here instead of the strings

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
> +    if (status === 'cancelled' || status === 'forceCancelled') {
Should be an enum

2022-07-22 14:06 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
> +      if (status === 'forceCancelled' && index === activeIndex) {
Should be enum (and everywhere else in the file)

2022-07-27 13:18 UTC, chinins reviewed
I'm mostly good with this. But it seems that there is another branch/PR that's been added. 
@agnieszkajarosikloj, can you please, confirm that this is just the cancel expenditure branch files?

2022-07-27 13:18 UTC, chinins commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureForm.tsx
> +            <IconTooltip
You can just use `QuestionMarkTooltip` component

2022-07-27 13:18 UTC, chinins commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureForm.tsx
> +          text={MSG.submit}
Please, use `text={{ id: 'button.submit' }}` instead and delete the button in MSG

2022-07-27 13:36 UTC, arrenv requested changes
Looking good @agnieszkajarosikloj, in addition to @chinins feedback.

Could we please remove the cancel icon on the completed phase, after that we should be good for this PR.

![0d61068f-003e-49ab-b1b6-0f787c493981](https://user-images.githubusercontent.com/33682027/181260494-7f08deac-9a22-4939-ae3a-cdf2d755ade2.png)

2022-07-27 22:05 UTC, agnieszkajarosikloj commented
> I'm mostly good with this. But it seems that there is another branch/PR that's been added. @agnieszkajarosikloj, can you please, confirm that this is just the cancel expenditure branch files?

Yes, it's just cancel expenditure branch files.
I removed from here changes in StakeExpenditureDialog (ids have been fixed in another [PR](https://github.com/JoinColony/colonyDapp/pull/3609/files#diff-a484286860d2c811eadd757f4b5801a49fb15824a51126f6b026c9aabc654320)). 
I preferred to add LinkedMotions here than in this [PR ](https://github.com/JoinColony/colonyDapp/pull/3609), where there are even more changes.

2022-08-01 12:10 UTC, Julianahlk commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureForm.tsx
> +    id: `dashboard.CancelExpenditureDialog.CancelExpenditureForm.creationTarget`,
The final part of this id should match the message label createDomain: 
id: `dashboard.CancelExpenditureDialog.CancelExpenditureForm. createDomain `,

2022-08-01 13:22 UTC, Julianahlk approved these changes
Looking good! Although, I have one question: 

I keep getting many warnings in this PR. Have you looked into these warnings and are these going to be fixed eventually? 

<img width="1445" alt="Screen Shot 2022-08-01 at 3 17 00 PM" src="https://user-images.githubusercontent.com/71563622/182157109-8c3a003f-d5d2-4892-ab2b-580c22b08104.png">

The last warning showed up when I toggle the force button.

2022-08-01 13:32 UTC, agnieszkajarosikloj commented
> Looking good! Although, I have one question:
> 
> I keep getting many warnings in this PR. Have you looked into these warnings and are these going to be fixed eventually?
> 
> <img alt="Screen Shot 2022-08-01 at 3 17 00 PM" width="1445" src="https://user-images.githubusercontent.com/71563622/182157109-8c3a003f-d5d2-4892-ab2b-580c22b08104.png">
> 
> The last warning showed up when I toggle the force button.

We talked about the last warning here:  https://github.com/JoinColony/colonyDapp/pull/3517#discussion_r929030346
The warning with formik context I fixed in this [PR](https://github.com/JoinColony/colonyDapp/pull/3609).

2022-08-01 17:35 UTC, Julianahlk commented
> We talked about the last warning here: [#3517 (comment)](https://github.com/JoinColony/colonyDapp/pull/3517#discussion_r929030346) The warning with formik context I fixed in this [PR](https://github.com/JoinColony/colonyDapp/pull/3609).

Thanks @agnieszkajarosikloj for pointing those out. All good from my side! 👍

2022-08-04 14:46 UTC, arrenv approved these changes
Looks great @agnieszkajarosikloj, thanks for your hard work on this!

2022-08-06 08:51 UTC, chinins approved these changes
Very nice wrok! Just please  remember to remove `handleMotionDomainChange` before merging.

2022-08-06 08:51 UTC, chinins commented on src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureForm.tsx
> +  const handleMotionDomainChange = useCallback(
You don't need this function, it doesn't add anything. Please, remove.

2022-08-08 08:21 UTC, merged