Add gnosis transaction preview dialog
JoinColony/colonyDapp pull request #3656
Opened 2022-07-19 20:13 UTC by chinins

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #3543

2022-07-22 23:37 UTC, ArmandoGraterol requested changes
Great work! Just a couple of details/questions and this should be good to go from my side.

1. In the specs now the "Target contract" field is called "Safe".
![FireShot Capture 674 - Safe Control – Figma - www figma com](https://user-images.githubusercontent.com/18473896/180580112-0ec77df0-8f20-4b99-9d5d-5394501a83a3.png)

2. Also it seems like the values of the things like `Data` or `Value (wei)` should be bolder. In the specs they are `600`, which looks too different from the `400` we have implemented.

3. "Title of the set of all the arbitrary transactions" should now be simply "Title"

4. "Explain why you’re making arbitrary transaction (optional)" is now "Description" which I'm gonna assume now that it's required because it doesn't have the "(optional)"

5. The field values should be aligned to the right, as per the screenshot above of the specs.

6. If I focus on the title field, then focus out and go back to the previous screen then the "Create transaction" button shows as disabled even though the current form is completed.

7. In the case of the "Transfer funds" transaction form, when I go back the amount field is empty and I have to re-enter the amount.

8. This is more of an idea/suggestion, what do you think of adding `appareance={{ theme: 'sidepadding' }}` to the section with the transaction title? In my opinion it seems like it makes it closer to the specs (in the specs there's not that much space between the title and description).

2022-07-25 11:31 UTC, willm30 reviewed
Correct me if I'm wrong but this now needs to be updated to reflect the added ability to add multiple transactions? I just added 3 but only received a preview for the first one.

2022-07-25 12:06 UTC, willm30 commented
> Correct me if I'm wrong but this now needs to be updated to reflect the added ability to add multiple transactions? I just added 3 but only received a preview for the first one.

Ah, I see this is a [separate issue ](https://github.com/JoinColony/colonyDapp/issues/3564)👍

2022-07-26 14:34 UTC, Julianahlk commented on src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/SafeTransactionPreview.tsx
> +    defaultMessage: `Explain why you’re making arbitrary transaction (optional)`,
I think it would sound better if we add the word "the": "Explain why you’re making the arbitrary transaction (optional)"

2022-07-26 14:37 UTC, chinins commented
> Great work! Just a couple of details/questions and this should be good to go from my side.
> 
> 1. In the specs now the "Target contract" field is called "Safe".

> 2. Also it seems like the values of the things like `Data` or `Value (wei)` should be bolder. In the specs they are `600`, which looks too different from the `400` we have implemented.
> 3. "Title of the set of all the arbitrary transactions" should now be simply "Title"
> 4. "Explain why you’re making arbitrary transaction (optional)" is now "Description" which I'm gonna assume now that it's required because it doesn't have the "(optional)"
> 5. The field values should be aligned to the right, as per the screenshot above of the specs.
> 6. If I focus on the title field, then focus out and go back to the previous screen then the "Create transaction" button shows as disabled even though the current form is completed.
> 7. In the case of the "Transfer funds" transaction form, when I go back the amount field is empty and I have to re-enter the amount.
> 8. This is more of an idea/suggestion, what do you think of adding `appareance={{ theme: 'sidepadding' }}` to the section with the transaction title? In my opinion it seems like it makes it closer to the specs (in the specs there's not that much space between the title and description).

@ArmandoGraterol, thank you for the feedback Please, see my comments:
1, 3 & 4 - updated (didn't notice the spec changed before). Descriptions should still be optional (saying it in brackets) - confirmed with Arren
2 - in the figma it says font-weight: 400 but I asked Arren & confirmed that we can do 700 - updated.
5 - on my screen it's all aligned to the right like in the specs. Can you please check and maybe offer a fix for your system (can't fix myself as I can't replicate)
<img width="499" alt="Screenshot 2022-07-26 at 11 59 49" src="https://user-images.githubusercontent.com/34057551/181032604-d7081483-213f-49dd-aa53-db207ecc1e49.png">

7 -  good catch. Fixed now although it take me a while 🙈
8 - talked to Arren and he said use margin above the Title field but not between  title and description - updated.

6 - OMG, this is a nightmare bug! I understand why it's happening but I haven't been able to fix it. Kept trying for almost the whole day. It validates it based on the old validation form although it's already update and it triggers re-validation only after you focus & unfocus a field. I tried all of the Formik validation props & functions but unsuccessfully. I will try again tomorrow... Any suggestions are welcome.

2022-07-26 14:48 UTC, Julianahlk commented
I noticed that the avatar does not have a border radius.
<img width="497" alt="Screen Shot 2022-07-26 at 5 25 23 PM" src="https://user-images.githubusercontent.com/71563622/181037862-71ea9f08-fcfd-454a-bc21-0e4bd51e211b.png">

2022-07-26 14:54 UTC, Julianahlk commented on src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/SafeTransactionPreview.tsx
> +    defaultMessage: `Explain why you’re making arbitrary transaction (optional)`,
Never mind, I was going through your code and while I was reviewing it you already made the changes.

2022-07-26 14:54 UTC, Julianahlk commented on src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/SafeTransactionPreview.tsx
> +    defaultMessage: 'Title of the set of all the arbitrary transactions',
Never mind, I was going through your code and while I was reviewing it you already made the changes.

2022-07-26 23:49 UTC, ArmandoGraterol commented
> 1, 3 & 4 - updated (didn't notice the spec changed before). Descriptions should still be optional (saying it in brackets) - confirmed with Arren

Thank you for confirming that!

> 5 - on my screen it's all aligned to the right like in the specs. Can you please check and maybe offer a fix for your system (can't fix myself as I can't replicate) <img alt="Screenshot 2022-07-26 at 11 59 49" width="499" src="https://user-images.githubusercontent.com/34057551/181032604-d7081483-213f-49dd-aa53-db207ecc1e49.png">

My bad, I think I didn't explain myself well, I'm talking about the inner alignment of the values:
![FireShot Capture 678 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/181131057-3c5c1de7-4d74-4532-bd3e-63d34c77ace6.png)

Data's value is internally aligned to the left when it has multiple lines as you can see from my screenshot, while in the specs even internally they are aligned to the right:

![180580112-0ec77df0-8f20-4b99-9d5d-5394501a83a3](https://user-images.githubusercontent.com/18473896/181131198-eb79d423-cb55-48f3-b8fc-dc9659440623.png)


> 6 - OMG, this is a nightmare bug! I understand why it's happening but I haven't been able to fix it. Kept trying for almost the whole day. It validates it based on the old validation form although it's already update and it triggers re-validation only after you focus & unfocus a field. I tried all of the Formik validation props & functions but unsuccessfully. I will try again tomorrow... Any suggestions are welcome.

I'll also take a stab at it to see if I can come up with some suggestions :+1:

2022-07-27 00:39 UTC, ArmandoGraterol commented
@chinins Suggestion time! This worked for me:

1. Make the initial value of `showPreview` `null`: `const [showPreview, setShowPreview] = useState<boolean | null>(null);`.
2. Add this effect to the `GnosisControlSafeForm` component:
```
  useEffect(() => {
    if (!isNil(showPreview) && !showPreview) {
      validateForm();
    } 
  }, [showPreview, validateForm]);
```

`validateForm` comes from the `FormikProps`.

This way I have been able to re-run the validation when going back to the previous dialog and get rid of the preview error :) Perhaps there's a better way but at least it's a start.

2022-07-27 08:53 UTC, chinins commented
> Data's value is internally aligned to the left when it has multiple lines as you can see from my screenshot, while in the specs even internally they are aligned to the right:

I see now - when the data has spaces! Good catch - fixed now.

2022-07-27 08:55 UTC, chinins commented
> @chinins Suggestion time! This worked for me:
> 
> 1. Make the initial value of `showPreview` `null`: `const [showPreview, setShowPreview] = useState<boolean | null>(null);`.
> 2. Add this effect to the `GnosisControlSafeForm` component:
> 
> ```
>   useEffect(() => {
>     if (!isNil(showPreview) && !showPreview) {
>       validateForm();
>     } 
>   }, [showPreview, validateForm]);
> ```
> 
> `validateForm` comes from the `FormikProps`.
> 
> This way I have been able to re-run the validation when going back to the previous dialog and get rid of the preview error :) Perhaps there's a better way but at least it's a start.

I think it's a very good solution. Yesterday everything I tried was in the Dialog component (even the validate).
I've added the fix. It seems that the null & isNil check is not even necessary. Working without it.

Thank you for the idea!

2022-07-27 16:39 UTC, willm30 reviewed
Looking good. One question: should there be validation on the title field? If you enter a single space it will let you submit the form without a title.

2022-07-27 19:28 UTC, ArmandoGraterol approved these changes
Looks good to me! Great job. Just take into consideration what Will mentioned about the title

2022-07-27 19:57 UTC, chinins commented
@willm30 @ArmandoGraterol it's the same validation as we have everywhere else in the dapp - empty strings are accepted.

2022-07-27 19:58 UTC, merged