Add split equal
JoinColony/colonyDapp pull request #3659
Opened 2022-07-20 09:55 UTC by agnieszkajarosikloj

## Description

This PR adds split equal option. User can set a max amount of funds, change currency, add/delete and select recipients. After adding recipients there is displayed recipients counter and share for each of them.

[Figma Link - Equal Distribution](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3807%3A285937)
[Figma Link - Equal Distribution with selections](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3802%3A277457)

**New stuff** ✨

* new part in form after selecting equal split
<img width="404" alt="Screenshot 2022-07-20 at 11 52 50" src="https://user-images.githubusercontent.com/91876137/179953726-ec9d7596-d21b-4081-8b3a-08c7422ad591.png">

* yup validation for new fields

Resolves  #3635

2022-07-20 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3659) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3659) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3659) it.</sub>

2022-07-25 11:04 UTC, willm30 requested changes
@agnieszkajarosikloj Made a few notes 🙂
1. There's a duplicate key error when adding recipients.
![duplicate-k](https://user-images.githubusercontent.com/64402732/180760857-678a573a-9554-4e25-8e49-c5c6e6d88555.png)

1. I don't think you should be able to add the same recipient more than once, and similarly, I don't think you should be able to submit the form if there's only one recipient added, as both are counterintuitive for a split payment function. Is that right?

1. ~~When  you put in a ridiculously large number it overflows the "max" label. Also, if you then click the "max" label it resets the value in the input to 0 and flashes a warning that the value should be greater than 0. (Unsure if this latter functionality is intentional but if so isn't intuitive to me).~~ I see this is a problem with the component not your branch 🙂

2022-07-27 16:15 UTC, willm30 reviewed
@agnieszkajarosikloj I see there's no longer the duplicate key error. 👍

However, the user dropdown picker is off the screen for me when selecting a second user:

![off-screen-popover](https://user-images.githubusercontent.com/64402732/181297223-0c5050d0-7551-4fb5-91c4-5d66812203a4.png)

2022-08-02 13:28 UTC, willm30 commented
@agnieszkajarosikloj I've made a gif to help illustrate what's happening on my machine. I have four members, and the last one is being left off screen even when scrolled to the bottom of the dropdown and the aside.  

![dropdown-offscreen](https://user-images.githubusercontent.com/64402732/182386064-39ddfcd6-da2d-4bce-a3a0-9f7e41b3f8f3.gif)

2022-08-03 09:59 UTC, willm30 commented
@agnieszkajarosikloj Dropdown menu height is fixed! I am however noticing a problem with the recipients list. Adding unique recipients works fine, but adding the same person twice causes some funny behaviour (and generates a duplicate key error in the console). 

In the gif below, I am clicking the delete icon next to the first "will" user, which is resulting is all non-will users being deleted, additional "wills" being added to the bottom and the recipients count dropping to zero.
  
![multiple-recipients](https://user-images.githubusercontent.com/64402732/182580213-c12609f4-e34a-4bb1-82b5-51b0240c4715.gif)

2022-08-03 11:46 UTC, willm30 commented
@agnieszkajarosikloj Fixed the problem. Just one comment / question:

When you delete the last remaining recipient you get what feels like a duplicate message (0 recipients and no recipients). 
![split-view-no](https://user-images.githubusercontent.com/64402732/182598977-f96c57f9-8e68-410c-ab18-008c044dc7bf.png)

Maybe the latter should be hidden instead?
![split1](https://user-images.githubusercontent.com/64402732/182600114-4ae3502c-1e25-44cd-946a-ff98118e0af8.png)

2022-08-03 12:00 UTC, agnieszkajarosikloj commented
@willm30  you're right. I've hidden this section when there are 0 recipients. Thank you.

2022-08-03 12:06 UTC, willm30 approved these changes
UI looking nice 👍

2022-08-03 15:39 UTC, Julianahlk commented
UI looks good! Just a few things:

1. The the state of the Max input field is not being saved when I toggle from Equal to Unequal. I find this odd because everything else is being saved except for that. 
![toogle-equal](https://user-images.githubusercontent.com/71563622/182649016-7221b1e3-59ba-4135-a9be-a3f90df8f964.gif)

2. I think I mentioned this before but I think we shouldn't be able to add users that do not exist:
<img width="474" alt="Screen Shot 2022-08-03 at 5 35 47 PM" src="https://user-images.githubusercontent.com/71563622/182649419-e7680f9c-f6ac-4c2c-a969-865e744210c1.png">
<img width="431" alt="Screen Shot 2022-08-03 at 5 35 55 PM" src="https://user-images.githubusercontent.com/71563622/182649432-adfaebfa-ec0d-4013-87eb-2aa6dbf43da5.png">

Especially because these recipients are being counted towards the Split Equal count:
![recipients](https://user-images.githubusercontent.com/71563622/182650346-8635327e-0a1d-40ae-8a25-0b0c951c64b0.gif)

2022-08-03 15:41 UTC, Julianahlk approved these changes

2022-08-09 19:42 UTC, chinins requested changes
Great job! Please, implement the changes requested (mostly small things) and ping me so that I can re-review with priority.

2022-08-09 19:42 UTC, chinins commented on src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.tsx
> +    return height > 180 ? 180 : height;
Can you please declare `56` and `180` as variables (you can do it outside of the component) and use variables? Not great to have just numbers.
Please, use capital letters for the variables, e.g. ELEMENT_HEIGHT

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.tsx
> +import { Recipient as RecipientType } from '../Payments/types';
Please, group and separate `../` & `./` imports (as per earlier guidelines)

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.tsx
>  const displayNameLockedRecipient = 'dashboard.ExpenditurePage.LockedRecipient';
Should just be `displayName` and you are missing `Recipient` before `LockedRecipient`

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +import { nanoid } from 'nanoid';
Belongs to the upper group

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +import { initalRecipient } from '../constants';
Should be before styles import & separated by an empty line

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why are `recipients` not included in the dependency array? If there is a specific reason, please, add a comment explaining

2022-08-09 19:42 UTC, chinins commented on src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
> +  const secondFormSection = useMemo(() => {
I would prefer to have it directly in the html with just a ternary operator. No need to separate it out with the use memo.

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +            {recipientsCount}{' '}
Please, do this string via `FormattedMessage`, not good to have spaces in the html like that

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +              />{' '}
Please, remove spaces and use margin instead in both cases

2022-08-09 19:42 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +                    return (
You don't need return word here, you can just do `=> (<div ...`

2022-08-09 20:24 UTC, ArmandoGraterol requested changes
Looking good! Apart from what Olga already mentioned, I noticed this:
![FireShot Capture 691 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/183753453-79fd1391-5b03-4c23-965b-29a4f1873529.png)

`.` should count as 0 like the other amount inputs that we have in the dapp, but it's being interpreted as `NaN` and it's showing a user-unfriendly error

2022-08-11 17:59 UTC, ArmandoGraterol approved these changes
Nice job! This is good to go from my side :ok_hand:

2022-08-23 19:46 UTC, arrenv approved these changes
Nice work @agnieszkajarosikloj, thank you!

2022-08-24 08:23 UTC, merged