Added reserve progress bar
JoinColony/colonyDapp pull request #3670
Opened 2022-07-22 07:33 UTC by agnieszkajarosikloj

## Description

This PR adds  reserve bar when toggle switch is on "Unequal". A reserve bar will show a percentage usage of max amount.
<img width="394" alt="Screenshot 2022-07-22 at 09 26 16" src="https://user-images.githubusercontent.com/91876137/180386718-62214a8c-62a6-4ebb-9da6-9b616c59c935.png">

[Figma Link - Reserve percent bar](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3807%3A285480)

## TODO
* display the actual percentage on the progress bar after adding recipients

Resolves  #3649

2022-07-22 07:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3670) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3670) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3670) it.</sub>

2022-07-25 10:30 UTC, willm30 approved these changes
Looks good to me 👍

2022-07-26 13:30 UTC, Julianahlk commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
> +const displayName = 'dashboard.ExpenditurePage.Split';
This has the same displayName as Split.tsx. How about using 'dashboard.ExpenditurePage.SplitUnequal'?

2022-07-26 13:44 UTC, Julianahlk approved these changes
Other than my one comment, everything works as intended 👍

2022-07-26 15:33 UTC, danbr approved these changes
LGTM - well done.

2022-07-26 16:26 UTC, arrenv requested changes
@agnieszkajarosikloj looks good, just please update the font size to match the rest, as of the circled.

![download (62)](https://user-images.githubusercontent.com/33682027/181059874-f13295c0-abf7-4a50-afae-d82beeb76eb6.png)

2022-08-12 09:29 UTC, merged