Add slider
JoinColony/colonyDapp pull request #3676
Opened 2022-07-25 12:05 UTC by agnieszkajarosikloj

## Description
This PR adds a progress slider that is visible when the switch is in the "Unequal" position. A slider bar allows to set a percentage usage of max funds.

<img width="355" alt="Screenshot 2022-07-25 at 07 49 16" src="https://user-images.githubusercontent.com/91876137/180707051-3afc0bcd-b061-4f8d-90ce-857f77bbc51f.png">

**Changes** 🏗

* Changed Slider component by adding possibility to override styling. It has been done by adding four optional props in Slider component:  
```
  handleStyle?: React.CSSProperties;
  dotStyle?: React.CSSProperties;
  railStyle?: React.CSSProperties;
  trackStyle?: React.CSSProperties;
```
These objects override the default styles:
```
 trackStyle={{
          backgroundColor: colors.backgroundColor,
          height: sizes.height,
          ...trackStyle,
        }}
```

## TODO

- add the rest of "Unequal" form in the next PR

Resolves #3650

2022-07-25 12:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3676) it.</sub>

2022-07-26 10:27 UTC, willm30 requested changes
@agnieszkajarosikloj Works nicely 🙂Noticed a few small things. 

1. Percentage label is a little too close to slider when 100%

![too-close](https://user-images.githubusercontent.com/64402732/180984328-267f3545-50ae-4791-a268-435ba45a8efe.png)

1. There are some lines visible in the sliders when the sum is below 100%

![lines-vis](https://user-images.githubusercontent.com/64402732/180984346-d5aeb48e-5776-4e6a-84ea-92b4a4a5ddc8.png)

1. I think the form should be disabled if the sum of the sliders is under 100%?

2022-07-26 15:27 UTC, danbr approved these changes
Looks good, working well for me. well done.

2022-07-26 15:27 UTC, danbr commented on src/modules/dashboard/components/ExpenditurePage/Split/Split.tsx
> +import { SplitUnequal } from '.';
Usually style imports last

2022-07-27 16:00 UTC, willm30 approved these changes
Nice one 👍

2022-08-04 08:00 UTC, merged