Fix: confirm button flashing on dialog open
JoinColony/colonyDapp pull request #3677
Opened 2022-07-25 13:39 UTC by willm30

## Description

Small pr to fix a small bug with the confirm button of the Ban User form that was flashing upon first open. 

**Changes** 🏗

* Form is now disabled if not dirty (i.e. on first open)

Resolves #3632

2022-07-25 22:33 UTC, ArmandoGraterol requested changes
Unfortunately, it can't be this simple:
![FireShot Capture 676 - Members - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/180884991-f69162fa-0853-4aec-8e84-68090f8918ce.png)

Now when I want to ban a user through the "Ban user" option in the 3 dots tooltip of the member list I can't because the user address is prefilled and therefore the form is not dirty

2022-07-26 13:08 UTC, willm30 commented
> Now when I want to ban a user through the "Ban user" option in the 3 dots tooltip of the member list I can't because the user address is prefilled and therefore the form is not dirty

Nice catch. Should be fixed now (still fairly simple 🙂).

2022-07-26 16:05 UTC, ArmandoGraterol approved these changes
Nice one! It's working properly now. I like Dan's suggestion, it's even more simple than what we currently have :)

2022-07-26 16:19 UTC, arrenv approved these changes
Looks good, I also prefer Dan's suggestion.

2022-07-26 19:52 UTC, chinins approved these changes
Please, make sure that you update it based on Dan's suggesiton.

2022-07-26 19:52 UTC, chinins commented on src/modules/core/components/Comment/Dialogs/BanUser/BanUser.tsx
> +        const isEmptyString = values.userAddress === '';
This is not good practice to have a stateless variable like this.

2022-07-27 05:40 UTC, willm30 commented
@danbr When you go to ban an address that is prepopulated, there are a couple of renders where the initial values are actually `{userAddress: undefined}`, which means that with `!values.userAddress` you still get a flash. 

![ban-user-flash](https://user-images.githubusercontent.com/64402732/181169147-484a99ff-6d55-45db-91c2-681ddd3e094a.gif)
 

Is that ok or should I do something like `disabled={!isValid || isSubmitting || values.userAddress === ''}`?

2022-07-27 07:48 UTC, chinins commented
> @danbr When you go to ban an address that is prepopulated, there are a couple of renders where the initial values are actually `{userAddress: undefined}`, which means that with `!values.userAddress` you still get a flash.
> 
> 
> Is that ok or should I do something like `disabled={!isValid || isSubmitting || values.userAddress === ''}`?

That's fine as well

2022-07-27 15:26 UTC, merged