Add split locked
JoinColony/colonyDapp pull request #3693
Opened 2022-07-28 07:06 UTC by agnieszkajarosikloj

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-07-28 07:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3693) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3693) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3693) it.</sub>

2022-08-24 11:01 UTC, ArmandoGraterol requested changes
Solid work! I just noticed some small things:
![FireShot Capture 699 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/186400632-fbd05477-7313-42a0-ba57-b751ba7b1fc2.png)
![FireShot Capture 700 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/186402061-623fbf1c-5749-490d-b315-3a6b0eef472a.png)

1. The recipient's containers look like they have different padding for the top and bottom, so it doesn't look centered.
2. We could use more space between the token icon and the amount, currently it's `4px`, if we use `8px` it could look closer to the specs.
3. The amount label doesn't look aligned to me, but only by like `1px` - `2px`. Might be screen/OS but it's noticeable
4. With really long usernames it goes out of the container. We should establish a width in which we should cut off the name with an ellipsis, like how we do it in other places in the dapp.

2022-08-24 13:59 UTC, arrenv approved these changes
Looks good to me @agnieszkajarosikloj

2022-08-25 14:53 UTC, chinins approved these changes
Well done!

2022-09-01 00:32 UTC, ArmandoGraterol approved these changes
Excellent work! Just noticed that the empty brackets are still there, but other than that detail, this is good to go

2022-09-01 00:32 UTC, ArmandoGraterol commented on src/modules/dashboard/components/ExpenditurePage/Split/LockedSplit.tsx
> +                  </>
The unnecessary empty bracket are still here

2022-09-14 07:13 UTC, merged