Add unequal split
JoinColony/colonyDapp pull request #3694
Opened 2022-07-28 07:12 UTC by agnieszkajarosikloj

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-07-28 07:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3694) it.</sub>

2022-08-04 11:42 UTC, willm30 approved these changes
Working well for me.

2022-08-04 22:55 UTC, Julianahlk approved these changes
Works as expected! 👍
<img width="398" alt="Screen Shot 2022-08-05 at 12 52 59 AM" src="https://user-images.githubusercontent.com/71563622/182968666-4fa802c6-7828-4836-a40b-0b3698fddf50.png">
One thing regarding the Amount input, if you toggle to Equal and toggle back to Unequal, the state of everything else is saved except for the amount.

2022-08-10 19:46 UTC, ArmandoGraterol requested changes
Looking good! Just some small comments regarding the labels

2022-08-10 19:46 UTC, ArmandoGraterol commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
> +                label=""
Please always include a label, the label is used for accessibility purposes

2022-08-10 19:46 UTC, ArmandoGraterol commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
> +                        label=""
Same here, add `elementOnly` to this component and then add a label

2022-08-11 19:39 UTC, ArmandoGraterol approved these changes
Looks good to me! Good job

2022-08-12 09:29 UTC, merged