Staged payment locked
JoinColony/colonyDapp pull request #3714
Opened 2022-08-02 13:35 UTC by agnieszkajarosikloj

## Description

This PR adds locked state of staged payment.
<img width="431" alt="Screenshot 2022-08-02 at 15 23 51" src="https://user-images.githubusercontent.com/91876137/182385748-8bf6c181-2abe-4326-9c25-899034bfbf29.png">

[Figma Link - Staged payments locked state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3802%3A279744)

## TODO

- Add edits in locked state, when [PR](https://github.com/JoinColony/colonyDapp/pull/3609) will be merged.

(Resolves) #3682

2022-08-02 13:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3714) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3714) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3714) it.</sub>

2022-08-03 13:44 UTC, danbr approved these changes
LGTM - well done.

2022-08-03 13:44 UTC, danbr commented on src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css
> +  letter-spacing: 0.25px;
var(--spacing-normal)

2022-08-03 13:44 UTC, danbr commented on src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css
> +  letter-spacing: 0.5px;
--spacing-medium

2022-08-04 11:27 UTC, willm30 commented
@agnieszkajarosikloj I'm getting a few warnings in the console. 

1. When selecting "Staged"
![staged-key](https://user-images.githubusercontent.com/64402732/182835651-e61d4b5f-bcd1-43dc-86b9-ae8ac55ab020.gif)

2. When submitting the draft and clicking "Stake" on the modal (before locking)
![locked-warning2](https://user-images.githubusercontent.com/64402732/182835448-12852323-4429-46d2-be80-e2cee4dc9a01.png)

3. When I click "Lock values"
![locked-warnings](https://user-images.githubusercontent.com/64402732/182835438-fa6dd663-236b-4bfb-9645-04a2402c5839.png)

Looks good though.

2022-08-04 23:27 UTC, Julianahlk reviewed
Very nice! It is working well for me. 

A few comments:
1. In the design, the input field doesn't have a border. However, I think adding a border is a good idea because it makes very clear where to add a name for the milestones. We can double check with @arrenv if we should add it or not and what the color should be.  
<img width="397" alt="Screen Shot 2022-08-05 at 1 09 23 AM" src="https://user-images.githubusercontent.com/71563622/182970954-3f2343e1-991c-4da4-a4d2-dd87ac4fe512.png">
2. I am getting these Popper warnings 
<img width="1689" alt="Screen Shot 2022-08-05 at 1 15 44 AM" src="https://user-images.githubusercontent.com/71563622/182971787-fb30ef3f-98cf-4db3-a0ce-b46b06f65fba.png">

2022-08-05 15:45 UTC, arrenv commented
> 1. In the design, the input field doesn't have a border. However, I think adding a border is a good idea because it makes very clear where to add a name for the milestones. We can double check with @arrenv if we should add it or not and what the color should be.

Just confirming you mean turning these text inputs into typical inputs field designs? At the moment, this would be a scope creep for the project, so, we can revisit it again when we do the wiring up.

2022-08-08 18:00 UTC, arrenv requested changes
Looks good @agnieszkajarosikloj, just noticed the font does not match.

I'm pretty sure you're going to include the edit icon in another PR, but I have pointed it out in this screenshot anyway.

![8cdba69a-0f27-4164-b1c5-8a6eadc17453](https://user-images.githubusercontent.com/33682027/183483231-0925c08f-e73e-44b8-b0ac-3ba928e9e8ef.png)

2022-08-20 00:13 UTC, ArmandoGraterol approved these changes
Looks good to me :+1: 

![FireShot Capture 695 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/185721592-5608dd82-0920-4744-aa6b-e4757d2ab97d.png)

2022-08-23 19:19 UTC, arrenv approved these changes
Looks good @agnieszkajarosikloj, thank you!

2022-08-24 06:05 UTC, merged