Decisions details modal
JoinColony/colonyDapp pull request #3719
Opened 2022-08-03 19:07 UTC by willm30

## Description

- This PR tracks the work involved in creating the Decisions details modal, accessed via the New Decisions button.

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #3708

2022-08-08 07:21 UTC, danbr commented
@willm30 Hey - unfortunately for me the dapp doesnt compile & npm is complaining.

<img width="758" alt="Screenshot 2022-08-08 at 10 17 05" src="https://user-images.githubusercontent.com/582700/183361786-b3b799a2-718b-4cbd-855b-5cc57f50e9eb.png">

2022-08-08 07:59 UTC, willm30 commented
> @willm30 Hey - unfortunately for me the dapp doesnt compile & npm is complaining.
> 

@danbr 
I'm using the tiptap library like in the coinmachine implementation.

You should be able to resolve with: npm install --legacy-peer-deps

2022-08-08 10:05 UTC, Julianahlk approved these changes
Very nice! It works well for me. 

<img width="500" alt="Screen Shot 2022-08-08 at 11 56 55 AM" src="https://user-images.githubusercontent.com/71563622/183393345-7b793025-280a-447e-82d0-9668a4db04bc.png">

As a side note, images are not fully loading and the text color cannot be changed. Might be a good things to address in another PR?

2022-08-08 10:23 UTC, danbr commented
@willm30 package-lock.json needs to be committed.

2022-08-08 10:29 UTC, willm30 commented
> @willm30 package-lock.json needs to be committed.

@danbr Ah ok, apologies. Now pushed.

2022-08-08 14:10 UTC, danbr requested changes
Looking really good. Well done. 
The core functionality is there, but i've found a few things to address:

- Icon names, i made a comment in the code.

- Create Motions in..... should be 'Proposal will be created in'
<img width="571" alt="Screenshot 2022-08-08 at 13 35 14" src="https://user-images.githubusercontent.com/582700/183430510-352f1a4b-ba02-40c5-82bd-21600a7c6d7f.png">

- RickText - I'm a bit confused by the name of the component. For me, I think of the file format, so i didnt find it intuitive to know its purpose. 

- Preview button is 160px in figma

- Its hard to know which icons in the toolbar have been selected. Would expect icon to be colorised/inverted.

- Toolbar icon tooltips - some show title, some show shortcuts (Github show both as a tooltip)
<img width="528" alt="Screenshot 2022-08-08 at 13 38 37" src="https://user-images.githubusercontent.com/582700/183432902-3be6a9f4-ced5-41b5-8b51-88eccf9c4d97.png">
<img width="549" alt="Screenshot 2022-08-08 at 13 38 43" src="https://user-images.githubusercontent.com/582700/183432907-42cadbf0-cb99-445e-b912-21dfa1816926.png">

- Toolbar has several extra buttons, URL and File. Not sure they are necessary for this feature (could be useful to have in other dialogs in the future)???
Especially supporting 'files' increases complexity as we would then need to handle the provided files. 
I would suggest to keep it simple, and progress from there and add files in V2 if required.

- I think there is already a comment for this issue (i'll add just in case not). Selecting a color does not change the color of the text.

- Should we have a placeholder for Title? What think?

- Spacing between seems too large:
<img width="523" alt="Screenshot 2022-08-08 at 15 18 04" src="https://user-images.githubusercontent.com/582700/183433211-3015432d-81b8-4a21-83d2-487445352cc9.png">

- I was playing a little with the editor, and the backtick char (`) gave unexpected behaviour. This is within TipTap?

This issue has become quite large, so we can break out into smaller if you wish? 
Well done, once again.......

2022-08-10 22:21 UTC, willm30 commented
> Looking really good. Well done. The core functionality is there, but i've found a few things to address:
> 

> This issue has become quite large, so we can break out into smaller if you wish? Well done, once again.......

@danbr Thanks for the detailed feedback!

I have fixed the following:

> * Icon names, i made a comment in the code.
> * Create Motions in..... should be 'Proposal will be created in'
> * RickText - I'm a bit confused by the name of the component. For me, I think of the file format, so i didnt find it intuitive to know its purpose.

(changed to `RichTextEditor`)

> * Preview button is 160px in figma
> * Its hard to know which icons in the toolbar have been selected. Would expect icon to be colorised/inverted.
> * Toolbar icon tooltips - some show title, some show shortcuts (Github show both as a tooltip)
> * Toolbar has several extra buttons, URL and File. Not sure they are necessary for this feature (could be useful to have in other dialogs in the future)???
> * Should we have a placeholder for Title? What think?
> * Spacing between seems too large

This works for me. Can you help me reproduce?
> * I think there is already a comment for this issue (i'll add just in case not). Selecting a color does not change the color of the text.

![change-color](https://user-images.githubusercontent.com/64402732/184030480-68645b53-10bd-4987-839b-ad28b6b5f499.gif)

> * I was playing a little with the editor, and the backtick char (`) gave unexpected behaviour. This is within TipTap?

This is caused by the `MuliWeb` font. It also happens in the Title input. I think we should change the font inside the RichTextEditor -- any suggestions?

2022-08-11 08:51 UTC, willm30 commented on src/modules/core/components/Button/Button.tsx
> +    | React.MutableRefObject<HTMLButtonElement | null>;
Updating the component to allow the passing of an actual ref object (used by the color picker), not just the function you receive when using the popover component

2022-08-11 08:55 UTC, willm30 commented on src/modules/dashboard/components/MotionDomainSelect/MotionDomainSelect.tsx
> +            )} ${formatMessage({
Modifying component to accept a custom label. If I didn't do this, I feel like I would basically be copying this component into a new component with a different name for use in this form.

2022-08-12 09:27 UTC, danbr commented
> The color picker works for me. Can you help me reproduce?
I re-checked...... and its working perfectly.



> > * I was playing a little with the editor, and the backtick char (`) gave unexpected behaviour. This is within TipTap?
> 
> This is caused by the `MuliWeb` font. It also happens in the Title input. I think we should change the font inside the RichTextEditor -- any suggestions?
> 
> I also updated the styling for code blocks (white text on black background).

Not sure how coinMachine implemented it, but the code block doesnt look pretty i.e. the black block.
I like how GitHub implements this action. But this would mean that we need Markdown in TipTap, but they dont support it...... <BIG BUT> I found MD for TipTap - https://github.com/aguingand/tiptap-markdown 
Its a new project..... Perhaps you can check if it's usable. Internally when we discussed the decisions editor, MD was spoken about. I think MD is ubiquitous these days, and a reasonable expectation from the users for it to be supported. 
Especially when things like code blocks are included.

If the MD npm isnt suitable, then i suggest to leave 'as is' and we can review this in the future.

2022-08-12 09:30 UTC, danbr approved these changes
Good work @willm30 - looking great. Thanks for the updates.

2022-08-12 15:08 UTC, merged