Feature/3713 batch upload
JoinColony/colonyDapp pull request #3728
Opened 2022-08-08 07:49 UTC by agnieszkajarosikloj

## Description

This PR adds batch payment type. When user selects "Batch" payment type, new form section is displayed. This new section contains: 
- dropdown to upload .csv file,
- uploading process icon,
- clear batch button (when file is uploaded),
- view all data button (modal should be visible here, but it will be added with next PR),
- recipients counter,
- batch value and multiple currencies.

<img width="405" alt="Screenshot 2022-08-08 at 09 44 23" src="https://user-images.githubusercontent.com/91876137/183366159-a30adb14-1a00-4083-a115-1187c8c20760.png">

[Figma Link - Download and upload Batch](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A319781)
[Figma Link - Uploading state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A319521)
[Figma Link - Uploaded state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A319256)
[Figma Link - Uploaded with multiple tokens](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3807%3A290638)

## TODO

- form validation - will be added in next PR
- modal with data details - also in next PR

Resolves #3713

2022-08-08 07:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3728) it.</sub>

2022-08-09 15:27 UTC, Julianahlk reviewed
Looking good! A few questions regarding the design. I see a few discrepancies from what you have and what's on Figma: 
<img width="755" alt="Screen Shot 2022-08-09 at 5 17 27 PM" src="https://user-images.githubusercontent.com/71563622/183689736-5fb6173f-1f36-43d7-8e8a-019c091cf97c.png">

1. Expenditure type - Should this text be changed to Payment type? 
2. Team - Should team be switched to From? 
3. Balance - This is not in the Figma design. 
4. Owner - Should the initial state for the owner be empty? 
<img width="412" alt="Screen Shot 2022-08-09 at 5 07 10 PM" src="https://user-images.githubusercontent.com/71563622/183691332-09d52498-1dda-4723-990e-acd09be5fcf5.png">

2022-08-16 11:11 UTC, agnieszkajarosikloj commented
> Looking good! A few questions regarding the design. I see a few discrepancies from what you have and what's on Figma: <img alt="Screen Shot 2022-08-09 at 5 17 27 PM" width="755" src="https://user-images.githubusercontent.com/71563622/183689736-5fb6173f-1f36-43d7-8e8a-019c091cf97c.png">
> 
> 1. Expenditure type - Should this text be changed to Payment type?
> 2. Team - Should team be switched to From?
> 3. Balance - This is not in the Figma design.
> 4. Owner - Should the initial state for the owner be empty?
> 
> <img alt="Screen Shot 2022-08-09 at 5 07 10 PM" width="412" src="https://user-images.githubusercontent.com/71563622/183691332-09d52498-1dda-4723-990e-acd09be5fcf5.png">


@arrenv if you could confirm, we agreed that the ExpenditureSettings section should be the same as for the other payment types

2022-08-16 13:23 UTC, arrenv commented
> * Expenditure type - Should this text be changed to Payment type?

Yes, we eventually want the naming to be updated across the whole feature from "Expenditure" to "Payment". So, you can just replace it.

> * Team - Should team be switched to From?

No, leave it as "Team".

> * Balance - This is not in the Figma design.

This can stay there.

> * Owner - Should the initial state for the owner be empty?

No, leave it as it is, i.e. auto added based on who is creating it.

2022-08-18 09:44 UTC, willm30 reviewed
@agnieszkajarosikloj With the following CSV data I'm not getting a value for recipients or value: 

Recipient | Token | Amount
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1000
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1001
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1002
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1003
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1004
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1005
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1006
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1007
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1008

2022-08-19 09:39 UTC, willm30 commented
@agnieszkajarosikloj Recipient is showing up for me now but value is not. Using the same CSV.

2022-08-19 14:38 UTC, agnieszkajarosikloj commented
> @agnieszkajarosikloj Recipient is showing up for me now but value is not. Using the same CSV.

@willm30 token in CSV file should be added by the token address/id. 
I added displaying 'Recipients' and 'Value' with message even when there are no valid data. Thanks for pointing it.

2022-08-19 15:22 UTC, Julianahlk commented
I can't get recipients counter, batch value and multiple currencies to be shown. 

<img width="410" alt="Screen Shot 2022-08-19 at 5 20 09 PM" src="https://user-images.githubusercontent.com/71563622/185652327-ee77bf88-17dd-44a1-aa3d-5235e33eca9f.png">

2022-08-21 17:04 UTC, willm30 commented
@agnieszkajarosikloj I've updated my CSV to the below, using the token address in the token column (the address is for Tether):
```
Recipient | Token | Amount
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1000
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1001
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1002
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1003
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1004
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1005
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1006
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1007
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | 0xdAC17F958D2ee523a2206206994597C13D831ec7 | 1008
```

I'm only seeing this view:

![batch-csv](https://user-images.githubusercontent.com/64402732/185802194-4d9f20d6-25c5-40bc-a658-e3872a9ee17a.png)

What CSV are you using in your screenshot in the issue description?

2022-08-22 08:43 UTC, agnieszkajarosikloj commented
@willm30 I've merged PR with 'Download template' button. Could you try to download the template and then try to upload the CSV file from the example with your data? Please let me know if that works.
And just to be sure, recipient id's and tokens are valid? Because I am filtering the data: 
```
const { data: colonyMembers } = useMembersSubscription({
    variables: { colonyAddress: colony.colonyAddress || '' },
  });
const { tokens: colonyTokens } = colony || {};
    
const validatedData = data.map(({ recipient, amount, token }) => {
      const correctRecipient = colonyMembers?.subscribedUsers.find(
        (user) => user.id === recipient,
      );
      const correctToken = colonyTokens?.find(
        (tokenItem) => tokenItem.id === token,
      );
      return {
        recipient: correctRecipient ? recipient : undefined,
        amount,
        token: correctToken || undefined,
      };
    });
```

2022-08-23 08:30 UTC, willm30 commented
@agnieszkajarosikloj Got it working now. I was going wrong with the tokens (maybe a more explicit error message here, something like "token address not found in colony..." would be helpful).

This csv produces a value of `3,000` and `3` recipients. Should it be 1 recipient given that it's the same address three times? 

```csv
Recipient | Token | Amount
0xb77D57F4959eAfA0339424b83FcFaf9c15407461 | 0xC9Ef69D2bE69C3BC9D7444982597fAF1A90697d1 | 1000
0xb77D57F4959eAfA0339424b83FcFaf9c15407461 | 0xC9Ef69D2bE69C3BC9D7444982597fAF1A90697d1 | 1000
0xb77D57F4959eAfA0339424b83FcFaf9c15407461 | 0xC9Ef69D2bE69C3BC9D7444982597fAF1A90697d1 | 1000
```

2022-08-23 10:02 UTC, agnieszkajarosikloj commented
@willm30  I'm glad it works now :)  On [this](https://github.com/JoinColony/colonyDapp/pull/3751) branch, after opening the modal, a detailed list is displayed, where you can check if some data was invalid (e.g. token was not found).
@arrenv could you please confirm if i have to check if it's the same address?

2022-09-02 14:58 UTC, chinins reviewed
The code looks fine but I can't make the csv template work (and I've tried many different options inlucding download template). I think that it would be great to include a working file for testing where we can just replace the values. Could you please add it to github either in PR description or in a comment. 

@arrenv, as a side note, I spent a very long time to try and make it work but couldn't. How are normal users supposed to use it? I would be infuriated if I was just a user and would abandon the task.

2022-09-02 17:12 UTC, arrenv commented
> @arrenv, as a side note, I spent a very long time to try and make it work but couldn't. How are normal users supposed to use it? I would be infuriated if I was just a user and would abandon the task.

I am about to test it, do you mean the download template is not complete? The one I provided included example data in it. I think it can be improved from I provided though, this one just looks to be a blank csv.

2022-09-02 19:50 UTC, chinins commented
> I am about to test it, do you mean the download template is not complete? The one I provided included example data in it. I think it can be improved from I provided though, this one just looks to be a blank csv.

There is no example data in the download template, unless I went mad :) So I tried to add data and submit and never managed to. Maybe I'm doing something really wrong but I don't think that's a great UX.
<img width="882" alt="Screenshot 2022-09-02 at 22 48 58" src="https://user-images.githubusercontent.com/34057551/188226426-a2073b90-a3e4-4633-ba8e-c459b8816262.png">

2022-09-02 20:04 UTC, arrenv commented
> There is no example data in the download template, unless I went mad :) So I tried to add data and submit and never managed to. Maybe I'm doing something really wrong but I don't think that's a great UX. 

Yeah, that is not the csv example I provided, I will provide it again.

2022-09-05 10:08 UTC, willm30 commented
@chinins I [got it working](https://github.com/JoinColony/colonyDapp/pull/3728#issuecomment-1223737449) by ensuring the tokens are an address and exist in the colony.

@arrenv  If there are three entries with the same recipient, should this show up as 1 or 3 recipients? I would have thought just 1 since it's the same address.

2022-09-07 07:00 UTC, arrenv commented
> @chinins I [got it working](https://github.com/JoinColony/colonyDapp/pull/3728#issuecomment-1223737449) by ensuring the tokens are an address and exist in the colony.
> 
> @arrenv If there are three entries with the same recipient, should this show up as 1 or 3 recipients? I would have thought just 1 since it's the same address.

I think this comes down to more the label of the row. Ignoring that, either option seems reasonable, although, I would lean more towards showing 3, given that is what was added in the csv file.

However, perhaps the `Recipients` label should be improved to be more accurate, e.g. `Imported payments`.

2022-09-12 11:34 UTC, willm30 reviewed
@agnieszkajarosikloj Working well for me. I do agree though that the "Recipients" heading should be changed to "Imported payments" (and in the template as well).

2022-09-14 15:21 UTC, willm30 reviewed
@agnieszkajarosikloj The template still includes the heading "Recipient". I also expect you'll need to update `useCalculateBatchPayment` with the new heading.

2022-09-16 07:46 UTC, agnieszkajarosikloj commented
@willm30 I thought that only label should be changed to "Imported payments". If we also change the header in the template, the user may not know that we need user id here.

2022-09-16 12:07 UTC, willm30 requested changes
@agnieszkajarosikloj I can see what you mean. Let's leave as is. 

With respect to the error state, when you upload the provided template as is, in the "Recipients" column the preview says that "the address format is wrong". I don't think that is correct. Should it not be something like "Address not found in colony"?

When a token is not found, [the row should be red](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5937%3A331943).

I also think the  `Not all rows were imported, please review.` message should read `Not all rows were imported correctly, please review.`, to avoid confusion. Otherwise it implies that we're expecting some set amount of rows to be imported, which we aren't. 

And when that message is showing, I would still [expect to see](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5941%3A332960) some calculation in "Imported Payments" and "Value". Currently, when uploading the template unchanged, it says "No payments" and "No tokens", even though there is data in the csv (albeit erroneous data).

2022-09-16 13:33 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj 

1. Could we replace the download template with this one:
[expenditures_batch.csv](https://github.com/JoinColony/colonyDapp/files/9584312/expenditures_batch.csv)


2. It does not seem to be supporting contract addresses. The following two should both say 5 imported payments and 360,000 total ETH payments:

![32487698-f74533f6ab18cb0002fe91171f52b052 (1)](https://user-images.githubusercontent.com/33682027/190647931-a718e7a7-1a9d-46b5-a41d-4517836d74cd.png)

![32488174-1feb8609c9a7280f19b4474da99afb3a](https://user-images.githubusercontent.com/33682027/190650038-109dfcdd-4b4c-4485-b059-588f0221508b.png)



4. I have a request. Could we please add in this tooltip to help - https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A319781

![Screenshot 2022-09-16 145638](https://user-images.githubusercontent.com/33682027/190644073-86c7ed3d-058d-41a8-bfe2-d11beb20c9ae.png)


5. Could we please have the weight of this font the same as the blue font.

![32487547-2ad90ec0e91219757c0e3eb8f8f5cf82](https://user-images.githubusercontent.com/33682027/190646783-868a377b-4dc8-46f5-988c-569dfba7372b.png)


6. There is no validation on the number of rows imported:

![32488058-e3c67b55e8c671ea6959936932bc12e3](https://user-images.githubusercontent.com/33682027/190649464-a05b52d1-4717-44ac-aae0-bb273bb56212.png)

2022-09-16 13:33 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/constants.ts
> +export const CSV = [
Please change to updated provided CSV.

2022-09-19 07:40 UTC, agnieszkajarosikloj commented
<img width="638" alt="Screenshot 2022-09-19 at 09 36 04" src="https://user-images.githubusercontent.com/91876137/190970094-125f9d73-d34a-46f0-96aa-08928e92b69a.png">

@arrenv validation has been added in other PR : https://github.com/JoinColony/colonyDapp/pull/3757

2022-09-19 09:55 UTC, willm30 reviewed
@agnieszkajarosikloj At the moment when uploading a csv of more than 400, not seeing an error.
![400](https://user-images.githubusercontent.com/64402732/190992960-1849fb7f-2895-46cf-a27e-2c447b571493.png)

2022-09-19 10:12 UTC, agnieszkajarosikloj commented
@willm30 form validation has been added in other PR: https://github.com/JoinColony/colonyDapp/pull/3757. 
In this PR error message is displayed only if user address or token address aren't correct.
(I've changed the recipient ID validation, it doesn't have to be a member of the colony now.)

2022-09-19 10:15 UTC, willm30 approved these changes
@agnieszkajarosikloj Ok thanks. Good to go from me.

2022-09-26 15:46 UTC, arrenv approved these changes
Looking and working great, just a small point. Thanks @agnieszkajarosikloj

2022-09-26 15:46 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Batch/Batch.tsx
> +    defaultMessage: `Download and use the .csv import template. Be sure to remove the sample data and view the details are correct once they have been imported.`,
Sorry, can we please change this to "Download and use the .csv import template. Be sure to remove the sample data and confirm the details are correct once imported."

2022-09-28 12:05 UTC, merged