Add batch preview
JoinColony/colonyDapp pull request #3751
Opened 2022-08-16 13:03 UTC by agnieszkajarosikloj

## Description

This PR adds modal with payment preview. After clicking 'View all' button modal with payment details is displayed.

<img width="722" alt="Screenshot 2022-08-16 at 15 01 07" src="https://user-images.githubusercontent.com/91876137/184885922-1efc16f7-f06d-4ac4-95f3-90ffad6792aa.png">

[Figma Link - Batch Payment Preview](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3807%3A291681)

Resolves  #3711

2022-08-16 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3751) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3751) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3751) it.</sub>

2022-08-18 09:37 UTC, willm30 requested changes
Currently, the amount values aren't showing up for me, using the following CSV data.

```csv

Recipient | Token | Amount
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1000
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1001
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1002
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1003
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1004
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1005
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1006
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1007
0xCd96D435128415F3265c32f9eaeFaCc6Be53b7D7 | xDai | 1008
```

2022-08-18 09:37 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.tsx
> +                <div className={styles.right}>{value}</div>
I tried this with a CSV with column headings 'Recipients, Token, Amount' and the amount isn't showing in the preview. I believe "value" here should read "amount".

2022-08-18 17:28 UTC, Julianahlk reviewed
I am having a similar  issue as Will, here is what my .cvs file looks like when I upload it:
<img width="585" alt="Screen Shot 2022-08-18 at 4 14 45 PM" src="https://user-images.githubusercontent.com/71563622/185457721-a14dfff6-af07-4aba-b520-7f174550eec8.png">

2022-08-24 14:19 UTC, willm30 commented
@agnieszkajarosikloj Tried again with the valid and invalid data and it's looking good. I did notice though that the scrollbar when present isn't styled according to the design (i.e. rounded).

2022-08-29 21:57 UTC, Julianahlk approved these changes
This is working well for me now 👍
<img width="496" alt="Screen Shot 2022-08-29 at 11 54 39 PM" src="https://user-images.githubusercontent.com/71563622/187306061-cfaf34a0-1eb8-427d-b577-c9a9a4aab083.png">

2022-09-02 19:51 UTC, chinins reviewed
The code looks good. You can update with minor things I mentioned and once I have an example of csv file from the other PR and test it I'll approve shortly.

2022-09-05 10:01 UTC, willm30 commented
> @agnieszkajarosikloj Tried again with the valid and invalid data and it's looking good. I did notice though that the scrollbar when present isn't styled according to the design (i.e. rounded).

@agnieszkajarosikloj Can you let me know what you've agreed with product re the scroll bar? If you're not planning to add it I can approve as the preview functionality is working nicely for me.

2022-09-07 10:15 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.css
> +    border-left: 2px solid var(--colony-light-blue);
@agnieszkajarosikloj The scrollbar is looking a little warped for me. 

I tried this instead. Let me know what you think.

``` css
&::-webkit-scrollbar-thumb {
    border-radius: 6px;
    border: 2px solid var(--colony-light-blue);
    background-color: color-mod(var(--temp-grey-blue-7) alpha(65%));
  }
```

Before:
![scrollbar1](https://user-images.githubusercontent.com/64402732/188853366-9c04f074-8ac6-45d6-b14f-6cad4d65691f.png)

After:
![scrollbar2](https://user-images.githubusercontent.com/64402732/188853392-d499d181-b1cc-4cad-9b0e-0cf5224378bb.png)

2022-09-09 09:31 UTC, willm30 approved these changes
Looking good 😎

2022-09-09 12:47 UTC, merged