Add NFT preview
JoinColony/colonyDapp pull request #3772
Opened 2022-08-25 10:46 UTC by willm30

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-08-25 11:02 UTC, willm30 commented
@ArmandoGraterol I'm not sure what to do about [this screen](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=5418%3A22229). 

![image](https://user-images.githubusercontent.com/64402732/186647641-ee8fb0b5-78ac-43fc-84b4-368f8da50486.png)

It differs from the [single transaction preview](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=5416%3A22136) in a number of respects (the `1. Transfer NFT` section has different row headings and then there's the presence of the section `2. Approve NFT`), and I'm not sure how the user flow would be differ to get here compared with the other screen.

What do you recommend?

2022-09-01 12:45 UTC, arrenv commented
> Yeah I understand why it's confusing and I believe the Transfer NFT section in the single transaction preview specs is the correct one, and the approve NFT part might just be a contract interaction. We could confirm if this is the case with @arrenv when he comes back as I believe he's taking some time off and the NFT transactions are not as high-priority as the others.

The main purpose of this it to transfer ownership of the NFT from one person to another. So, however many transactions are required to do that is the goal.

If referring to the [EIP-721 NFT standard](https://eips.ethereum.org/EIPS/eip-721), there are two methods that are required `Transfer` and `Approval`. Which, is why both are included here.

2022-09-08 12:42 UTC, willm30 commented
@arrenv I've been looking into this and this is my understanding so far:

 `Approve` [can only be called by the token owner](https://docs.openzeppelin.com/contracts/2.x/api/token/erc721#ERC721-approve-address-uint256-). Assuming the Safe owns the NFT, then it would not be possible for a Colony to call the `approve` method on an ERC721 contract (NFT). 

A user would first need to interact with the NFT from within the Safe UI & approve the Colony before we could call `safeTransferFrom` from the Colony UI. 

In which case, there'd be no need for the "approve" block in the screen above. 

Do I understand this correctly?

2022-09-09 13:58 UTC, arrenv commented
@willm30 The AMB would be able to trigger the Safe to do both of these transactions though, right?

2022-09-12 09:54 UTC, willm30 commented
> @willm30 The AMB would be able to trigger the Safe to do both of these transactions though, right?

@arrenv Ah good point. I was assuming the Colony contract would be calling the function in the ERC721 contract, but of course it actually gets called more like this:

Colony --> AMB 1 --> Bridge Monitor --> AMB2 --> Zodiac module --> Safe --> ERC721. So the safe would still be calling the functions on the ERC721 contract. 

I will assume we can make the calls from the colony UI and test using our mock deployment.

2022-09-13 22:33 UTC, ArmandoGraterol requested changes
Looking great to me :+1: Just noticed some small things and I also have a question:

What's the reason for separating the "Approve" section from this issue? I don't have anything against implementing that in a separate issue, just wanna know.

2022-09-13 22:33 UTC, ArmandoGraterol commented on src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
> +                      key={`${key}${label.defaultMessage}`}
I believe we could remove the key prop from `transactionTypeFieldsMap` and make this key better if we use autogenerated ids. Check out how we `nanoid` to generate ids in cases like this where there's no clear way to get a unique id.

2022-09-14 15:38 UTC, willm30 commented
> What's the reason for separating the "Approve" section from this issue? I don't have anything against implementing that in a separate issue, just wanna know.

@ArmandoGraterol I'm assuming it'll be it's own transaction type, so thought to separate it from this one which is just the `transfer NFT` flow.

2022-09-14 18:49 UTC, Julianahlk reviewed
As I was testing this I realized the NFT's images are not connected to the safes yet (which you are doing in your other PR) but also, whenever I change Safes, the SinglePickerUser for the NFTs continues giving me the same options no matter what safe I pick. 
![NFTallthesame ](https://user-images.githubusercontent.com/71563622/190237342-e4e9ae87-2ad5-4ed8-955a-008c260dcf9d.gif)

But the preview is looking good:
<img width="497" alt="Screen Shot 2022-09-14 at 8 55 17 PM" src="https://user-images.githubusercontent.com/71563622/190239430-1ed1216f-3f84-4937-8db0-0e3308f58d1d.png">

2022-09-15 00:08 UTC, ArmandoGraterol commented
> @ArmandoGraterol I'm assuming it'll be its own transaction type, so thought to separate it from this one which is just the `transfer NFT` flow.

As far as I know and according to the specs that we have, the `Approve` transaction is not its own type like the way the 4 transaction types are. 

This transaction only appears in the preview screen and its only appears following an NFT transfer, so when creating an NFT transfer transaction it's by default a multi-transaction.

2022-09-15 00:12 UTC, ArmandoGraterol commented
> ...whenever I change Safes, the SinglePickerUser for the NFTs continues giving me the same options no matter what safe I pick. 

That's expected, the PR you mentioned is about connecting the NFT picker: #3838

This issue/PR is only for adding the "Transfer NFT" transaction type to the Preview dialog, so only UI

2022-09-15 08:29 UTC, willm30 commented
> As far as I know and according to the specs that we have, the `Approve` transaction is not its own type like the way the 4 transaction types are.
> 
> This transaction only appears in the preview screen and its only appears following an NFT transfer, so when creating an NFT transfer transaction it's by default a multi-transaction.

@arrenv Are you able to confirm whether `approve NFT` should be its own transaction type? If it is not, then that would imply that every `transfer NFT` comes with an `approve NFT` call, which would seem unnecessary if the Colony had already been approved. And I'm not sure why [this screen](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=5416%3A22136) would exist if every `transfer NFT` call were also to include an `approve NFT` call. Can you clarify?

2022-09-15 08:30 UTC, willm30 commented
> > ...whenever I change Safes, the SinglePickerUser for the NFTs continues giving me the same options no matter what safe I pick.
> 
> That's expected, the PR you mentioned is about connecting the NFT picker: #3838
> 
> This issue/PR is only for adding the "Transfer NFT" transaction type to the Preview dialog, so only UI

@Julianahlk

2022-09-15 10:11 UTC, arrenv commented
> @arrenv Are you able to confirm whether `approve NFT` should be its own transaction type? If it is not, then that would imply that every `transfer NFT` comes with an `approve NFT` call, which would seem unnecessary if the Colony had already been approved. And I'm not sure why [this screen](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=5416%3A22136) would exist if every `transfer NFT` call were also to include an `approve NFT` call. Can you clarify?

From reading the documentation on Approve, it implies that you are giving permission to the Safe to transfer the NFT. This would only apply for a single NFT, so, it would make sense that every NFT Transfer includes both transactions in most cases.

If the exact same NFT was transferred back to the Safe and that was transferred out again, then I would assume that it would already have permission, so then it would not need the approve. In this case, I believe that the Transfer should be the only transaction.

If you discover something else though, please do update me.

2022-09-15 14:14 UTC, Julianahlk approved these changes
LGTM 👍

I found the warning below after creating only one transaction.  Steps to repro:

1. Create only one transaction
2. Create transaction
3. Go back to add a second one (it only happens the first time after refreshing the page)

<img width="1331" alt="Screen Shot 2022-09-15 at 4 24 02 PM" src="https://user-images.githubusercontent.com/71563622/190429998-194f5b22-8d2b-4059-97c9-e5fff937d48b.png">

2022-09-16 08:02 UTC, willm30 commented
> I found the warning below after creating only one transaction. Steps to repro:

@Julianahlk Thanks. Have created an issue for it as it's a bug on the main branch.

2022-09-16 16:03 UTC, ArmandoGraterol approved these changes
Nice work Will! This is good to go :ok_hand:

2022-09-19 11:14 UTC, merged