added edition in locked state
JoinColony/colonyDapp pull request #3805
Opened 2022-09-01 22:34 UTC by agnieszkajarosikloj

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-09-01 22:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3805) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3805) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3805) it.</sub>

2022-10-10 09:48 UTC, willm30 requested changes
Looking good to me! Just noticing a couple of things:

1. The discard button remains after discarding the change to the split when there are multiple sections (e.g. change title also):
![discard-remains](https://user-images.githubusercontent.com/64402732/194839293-0b373964-ea97-4997-ac40-06335dc44ad2.gif)

2. The cursor for the edit icon should be `cursor: pointer`

2022-10-12 05:54 UTC, agnieszkajarosikloj commented
@willm30 I have added fix. Can you have a look please?

2022-10-12 09:27 UTC, willm30 reviewed
Thanks. Just a couple of questions, the same that I left on one of the other edit prs. 

Would it make more sense to have it "Change recipient: 1", since the other headings have "change" in them? And changing "Change to" to just "To" to avoid repeating "Change"? 

And also noticing here that the user's name doesn't have the "@" in front, like in the design.

2022-10-14 08:38 UTC, agnieszkajarosikloj commented
@willm30 I have added changes. Can you have a look please?

2022-10-17 09:43 UTC, willm30 requested changes
Minor comments on the code but this looks good to me so can re-review once you've had a look through.

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
> +    defaultMessage: 'Mielstone has been deleted',
Typo: "Mielstone"

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
> +    id: `dashboard.EditExpenditureDialog.ChangedStaged.ChangedRecipient.removed`,
Id should be ChangedSplit

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
> +const displayName = `dashboard.EditExpenditureDialog.ChangedStaged.ChangedRecipient`;
Same

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
> +              <div className={styles.row} key={index}>
Reason for using index as key as opposed to `nanoId`?

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
> +              key={index}
Same q re index as key

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.tsx
> +
This is defined in Changed Staged. Only need one.

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.tsx
> +          <Fragment key={index}>
Index as key here?

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialog.tsx
> +        const { [name]: removedProperty, ...updatedValues } = newPayment || {};
Reason for unused var?

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Perhaps leave a comment here that setValue causes infinite loop?

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
> +    [recipients, setValue],
Given that setValue is recreated on every render, there's no point in using `useCallback` here -- or, remove from dependencies array.

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
> +    [amount.value, setFieldValue, amount.tokenAddress],
I think same will apply to setFieldValue, i.e. recreated each render

2022-10-17 09:43 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
> +    [recipients, setValue, amount.tokenAddress],
Same thought re setValue and useCallback here and above

2022-10-17 13:18 UTC, agnieszkajarosikloj commented
@willm30 I have added changes. It's ready for re-review.

2022-10-18 09:36 UTC, willm30 approved these changes
Nice one. Leaving the same comments here as the other one but looks good to me these aside.

1. The user avatar and token avatars aren't same size
2. Could we just have "Change Amount" instead of "Change Split Amount"? 
3. Could we capitalise "title" and "description" in "Change Title" and "Change Description"?

2022-10-20 07:22 UTC, agnieszkajarosikloj commented
@JoinColony/frontend can you review it, please?

2022-10-24 13:06 UTC, chinins approved these changes
Well done - quite a PR!

2022-10-24 13:23 UTC, merged