Decisions: Connect Decisions list to query
JoinColony/colonyDapp pull request #3823
Opened 2022-09-06 18:34 UTC by danbr

## Description

This PR:

- Adds extra props to Subscription SubgraphMotion
- Removes Decisions from ColonyActions
- Connect ColonyDecisions to query
- 

Resolves #3790

2022-09-09 23:23 UTC, ArmandoGraterol reviewed
Looking good to me :ok_hand: 

A small suggestion, instead of going back to the action list after exiting a decision action page you could go back to the decision list. I feel like this could improve UX, what do you think?

2022-09-09 23:24 UTC, ArmandoGraterol approved these changes

2022-09-13 08:47 UTC, willm30 requested changes
1. When I successfully stake a motion, clicking claim is producing the following error: 

![claimerr](https://user-images.githubusercontent.com/64402732/189850633-f7eab182-f838-4e25-8167-bfa50a8e5dba.png)

This doesn't happen after successfully objecting to a motion.
2. Agree that the "back" button should go to `/decisions`
3. If, after publishing a decision, you refresh the browser without staking or objecting, the motion fails. However, it doesn't show up as a failed decision in the decisions list. Should it?
4. If, after publishing a decision, I click the back button and navigate to `/decisions`, I only see "No decisions exist" (even if they do). I need to manually refresh to see my decisions list. 


And relatedly, if not directly relevant to this issue, I would think the decisions list default sort should be most recent first (reverse chronological), so the decision I just made is at the top. Also the label "Ending soonest/latest" is a bit confusing for decisions that have already ended (i.e. it's not obvious which sorting direction it refers to). This could be a separate issue if you agree.

2022-09-13 10:53 UTC, Julianahlk reviewed
Perhaps not part of this issue but thought I should mention my findings below: 

* If I refresh the Preview page before hitting the publish button, for a few secs you can see the Connect Wallet to Log in popup: 
![decisionrefresh](https://user-images.githubusercontent.com/71563622/189880948-e72cf9bd-9e41-436d-bd6c-ee4a073d6ac3.gif)

* In the **Should "Discussion" be approved?** if you vote **no** I am getting the following message:
<img width="1436" alt="Screen Shot 2022-09-13 at 12 37 20 PM" src="https://user-images.githubusercontent.com/71563622/189881927-c4d3f876-02d4-4744-9527-7f28981d11fb.png">

* RichTextEditor messages are not being posted to the ActionPage feed.

2022-09-13 11:15 UTC, chinins reviewed
It's working properly except for the decision is not showing up in the list before it's staked 10%. I thought that we don't have the 10% threshold fr decisions. Could you, please, confirm?

Also, the loading should show for the whole time until the subscription is loaded so that we don't have a message about installing voting extension. I assume, you need to move around the loading states.

2022-09-13 11:22 UTC, chinins commented
@willm30, the back button is not related to this issue and is being fixed some place else.

@Julianahlk, the connect wallet is there because the app needs some time to reconnect the user and it's a wallet protected route. The warning that you have in the console is the same as in the motions.

2022-09-13 11:37 UTC, Julianahlk commented
> @willm30, the back button is not related to this issue and is being fixed some place else.
> 
> @Julianahlk, the connect wallet is there because the app needs some time to reconnect the user and it's a wallet protected route. The warning that you have in the console is the same as in the motions.

Nice! Good to know 👍 Thanks.

2022-09-15 10:49 UTC, danbr commented
> Looking good to me 👌
> 
> A small suggestion, instead of going back to the action list after exiting a decision action page you could go back to the decision list. I feel like this could improve UX, what do you think?

@ArmandoGraterol Thank you. Yes thank you. That is the plan, its been implemented in another PR.

2022-09-16 20:57 UTC, chinins approved these changes
Other than the bug you mention and that is treated separately, everything is good - well done!

2022-09-18 17:22 UTC, merged