Add a new modal after making an edit
JoinColony/colonyDapp pull request #3824
Opened 2022-09-07 06:55 UTC by agnieszkajarosikloj

## Description

This PR adds a new modal after making an edit in payment.

Single funding source/recipient - [Figma](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5010%3A301542)
Multiple funding sources/recipients - [Figma](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5944%3A332264)

## TODO

- Add this modal in 'Split', 'Staged' and 'Batch' payment.

Resolves #3793

2022-09-07 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3824) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3824) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3824) it.</sub>

2022-09-08 09:21 UTC, willm30 reviewed
Nice one. Noticed a few small things.

1. The tooltip isn't aligned with the toggle at the top
2. Multiple tokens aren't centered in the row
3. In figma it says "Funding source" instead of "Recipient"
4. In figma there is the text: "Note: if this variable has previously been voted on..."

![editpymntmotion](https://user-images.githubusercontent.com/64402732/189083592-4f2738a6-9575-4be2-9b2f-fb55d7bd5579.png)

2022-09-09 09:24 UTC, willm30 requested changes
Also noticed the tooltip is behaving strangely on hover.

![hover](https://user-images.githubusercontent.com/64402732/189317774-09f735ef-e5e1-4edd-b565-c76ae02c6a9d.png)

2022-09-09 09:27 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.css
> +  justify-content: end;
The use of `end` is giving me warnings in the compiler. It recommends `flex-end` instead.

![end](https://user-images.githubusercontent.com/64402732/189318559-c2c0f6fc-e268-4777-8c9e-1e7dee4b24b9.png)

2022-09-12 10:59 UTC, willm30 reviewed
@agnieszkajarosikloj 

There's still a warning for me in the terminal:
![warn](https://user-images.githubusercontent.com/64402732/189635184-187beb94-a5a9-465b-957e-3626b487f90e.png)

Also, this tooltip icon is a couple of pixels too low.
![to (1)](https://user-images.githubusercontent.com/64402732/189636244-728e888d-63aa-47e4-827c-b3326bdc4514.png)

There are a couple of errors in the console:
![errorsc](https://user-images.githubusercontent.com/64402732/189637205-2837d58d-a68d-40c1-9d22-c7f002b87da4.png)

And separately, visiting the `/extensions` route on the `/feature/advanced-expenditures-phase-2` branch is causing the dapp to crash for me. Just bringing to your attention. May require rebasing.

![err-1](https://user-images.githubusercontent.com/64402732/189634955-5fb7329f-704b-4b06-8c4a-7c81d36fb98f.png)

2022-09-13 18:32 UTC, Julianahlk approved these changes
Good work @agnieszkajarosikloj! Modal is working well for me.
<img width="489" alt="Screen Shot 2022-09-13 at 8 17 19 PM" src="https://user-images.githubusercontent.com/71563622/189981555-fac4ce8c-a517-4071-96e1-f4db39afcdf3.png">

Question regarding the "Explain why you're changing the expenditure" message, when was this changed from optional to required when toggling the Force toggle? I was not aware of this change. 
<img width="495" alt="Screen Shot 2022-09-13 at 8 12 42 PM" src="https://user-images.githubusercontent.com/71563622/189980704-061a5d97-a659-4b1c-90e5-664def462029.png">

Also, I have created a new issue to make sure all the tooltips for the force toggles are updated for Expenditures: https://github.com/JoinColony/colonyDapp/issues/3850

Thanks!

2022-09-14 15:56 UTC, chinins reviewed
Very nice! Just a question about `any` values (and one other minor comment).

2022-09-14 15:56 UTC, chinins commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/ChangeItem.tsx
> +  oldValue?: any;
Why are these 2 values any? Usually, we try to avoid it. Or at least make a comment as to why it has to be any.

2022-09-14 15:56 UTC, chinins commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.tsx
> +                <FieldArray
This component is very "heavy". I think it would be great to have a child component with part of the logic/html separated there

2022-09-14 15:56 UTC, chinins commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.tsx
> +    defaultMessage: `Explain why you're changing the payment {optional}`,
I think that you are missing a dot in `EditExpenditureDialogFormdescriptionLabel`

2022-09-27 08:34 UTC, agnieszkajarosikloj commented
@willm30 I've added changes. Can you have a look please?

2022-09-27 08:58 UTC, willm30 commented
@agnieszkajarosikloj I am still noticing 1, 2, and 3
 
> 1. The tooltip isn't aligned with the toggle at the top
> 2. Multiple tokens aren't centered in the row
> 3. In figma it says "Funding source" instead of "Recipient"
> 4. In figma there is the text: "Note: if this variable has previously been voted on..."

Also Juliana's comment about the annotation message being required when you force the motion is still relevant as I'm also seeing it. If it is correct, then the form should be disabled until something has been entered.

2022-09-27 12:40 UTC, agnieszkajarosikloj commented
@willm30 I've added fixes. 
3. Text "Recipient" is displayed, because that text depends on where you added the change.
Currently, editing in the locked state works only for the "Advanced expenses" payment type.

2022-09-27 13:54 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj, looks good. Just one comment and a request.

I noticed these headings were missing.
![32827196-2f0a00b41b9bd6c6ac756813840c5f1a](https://user-images.githubusercontent.com/33682027/192545672-15ce80b6-bb2b-40ef-8612-577537e4b37e.png)

2022-09-27 13:54 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.tsx
> +    defaultMessage: `Note: if this variable has previously been voted on, subsequent votes will require more Reputation to be in favour in order for changes to be valid.`,
Can we please remove this paragraph, then just have a text link in the above paragraph with the text 'Learn more'. Like in this design - https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=7057%3A334987

The link will then go to this URL: https://colony.gitbook.io/colony/expenditures/advanced-payments#editing-locked-payments

2022-09-27 13:54 UTC, arrenv commented
> @willm30 I've added fixes. 3. Text "Recipient" is displayed, because that text depends on where you added the change. Currently, editing in the locked state works only for the "Advanced expenses" payment type.

Correct, `Recipient` is the correct text to show here.

2022-09-28 08:32 UTC, agnieszkajarosikloj commented
@arrenv  @willm30 I've added changes. Can you have a look please?

2022-09-28 08:53 UTC, willm30 approved these changes
Looking good from me. Have noticed the tooltip misaligned at the top of some of the other modals so may be worth adding an issue to amend.

2022-09-29 11:44 UTC, arrenv approved these changes
Looks good @agnieszkajarosikloj, thank you!

2022-09-29 11:58 UTC, merged