Connect Nft Picker to Existing safes
JoinColony/colonyDapp pull request #3838
Opened 2022-09-09 14:33 UTC by willm30

## Description

This PR connects the Nft Picker to the existing Safes in the colony. 

You can add the following safes with NFTS to your colony in order to test (both Rinkeby):

1. [0x05b990D01A2f86852feD1E7d609dd3E52aA9EA27](https://gnosis-safe.io/app/rin:0x05b990D01A2f86852feD1E7d609dd3E52aA9EA27)
1. [0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A](https://gnosis-safe.io/app/rin:0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A)

And this one doesn't have NFTs (also Rinkeby):
1. 0x0DA0C3e52C977Ed3cBc641fF02DD271c3ED55aFe

To test:
1. Add a safe with and without nfts
3. Go to safe control
4. Select a safe and select "Transfer NFT"
5. Should display loading state while we fetch nft data. If there's none, should display relevant message. If there's an error fetching (e.g. no internet connection), should also display relevant message. 
6. Once data is fetched, you should be able to select an nft in the safe. If it has an image uri, this should show in the avatar component, and the contract name and id should be correctly inputted. 

It also does a little bit of housekeeping:
1. Removing "testnet" from Goerli and Rinkeby. I added these in an earlier PR thinking they'd be useful but they just take up unnecessary space in the safe picker input and it's also not how Gnosis Safe refers to them. So reverting.
7. Updates validation schema for `safe`
8. renamed `getSafeCoreSDK.ts` to `safeHelpers.ts` and added a few utility functions.

**Changes** 🏗

* Wires up the NFT picker to the safes that exist in the colony.

## Screenshot

![nfta](https://user-images.githubusercontent.com/64402732/189651478-109226e3-66c7-49f1-b7e7-529bcdf052ff.png)

Resolves #3835
Contributes to #3722

2022-09-13 07:39 UTC, willm30 commented
> Not a full-scale review but I noticed you use both `Nft` and `NFT` which seems a bit inconsistent

@jakubcolony Can you leave an in-line comment in the code where you see this?

2022-09-13 07:48 UTC, jakubcolony reviewed
The existing code seems to favour `NFT` while most of the stuff you added is `Nft`. I highlighted two files in which you use `NFT`. Probably not a big deal but hope this helps

2022-09-13 07:48 UTC, jakubcolony commented on src/modules/dashboard/sagas/utils/safeHelpers.ts
> +export const getIdFromNFTDisplayName = (displayName: string) => {
`NFT`

2022-09-13 07:48 UTC, jakubcolony commented on src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.tsx
> +    const getNFTs = async (chosenSafe: SelectedNft) => {
`NFT`

2022-09-13 11:19 UTC, Julianahlk reviewed
Nice work @willm30! 

<img width="498" alt="Screen Shot 2022-09-13 at 1 09 04 PM" src="https://user-images.githubusercontent.com/71563622/189888194-0289de87-5d96-4a15-b1bd-f346f619e3bc.png">
<img width="495" alt="Screen Shot 2022-09-13 at 1 09 21 PM" src="https://user-images.githubusercontent.com/71563622/189888205-2f170324-a587-49d5-9233-42c408064d79.png">
<img width="496" alt="Screen Shot 2022-09-13 at 1 09 33 PM" src="https://user-images.githubusercontent.com/71563622/189888211-eb95669d-a684-47c4-9ae2-35e31678a021.png">
<img width="494" alt="Screen Shot 2022-09-13 at 1 20 58 PM" src="https://user-images.githubusercontent.com/71563622/189888434-8deb00a1-ab2f-42e2-a567-5bc3b4d7a5ca.png">
<img width="497" alt="Screen Shot 2022-09-13 at 1 15 46 PM" src="https://user-images.githubusercontent.com/71563622/189888451-6682b55a-7340-4311-978c-ce320ac01a1f.png">

Question regarding the following:

1. I added this safe [0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A](https://gnosis-safe.io/app/rin:0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A) but I didn't see any NFT image loaded, does this NFT have an image?

<img width="496" alt="Screen Shot 2022-09-13 at 1 21 10 PM" src="https://user-images.githubusercontent.com/71563622/189888762-bff2b8b7-1309-4674-8ba1-463a679a9551.png">

![creature](https://user-images.githubusercontent.com/71563622/189888923-c88a90bb-229f-42af-91e4-0cdc103e6e31.gif)

2. I was testing what happens if you confirm a transaction and hit the back button to go back to the control safe dialog and when I go back I see the state of the dialog is a bit different. I do not have any NFT selected, image and the transaction type is gone, is this normal?
![NFTTESTING](https://user-images.githubusercontent.com/71563622/189889080-dfa0d1f9-ad88-412d-9fe1-51c55a37f6ef.gif)

2022-09-14 00:14 UTC, ArmandoGraterol requested changes
> I think that's actually the NFT lol
![FireShot Capture 719 - Safe - gnosis-safe io](https://user-images.githubusercontent.com/18473896/190031038-f80c7187-4376-4ece-9f2c-6ec40cc542a9.png)

I see, I was expecting an actual NFT creature 😂

2022-09-14 14:58 UTC, Julianahlk commented
> Excellent work Will! Left some comments but overall good job wiring this up
> 
> @Julianahlk
> 
> > I added this safe [0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A](https://gnosis-safe.io/app/rin:0x358E6D7C8Fa5e55fc6A0D50E23b875c6c49fF09A) but I didn't see any NFT image loaded, does this NFT have an image?
> 
> I think that's actually the NFT lol
> 
> > I was testing what happens if you confirm a transaction and hit the back button to go back to the control safe dialog and when I go back I see the state of the dialog is a bit different. I do not have any NFT selected, image and the transaction type is gone, is this normal?
> 
> Can confirm it's happening, and it's not normal behaviour

Sorry, I think I commented and edited the message above by accident. But thanks for clarifying. I was expecting the image of a creature.

2022-09-14 15:11 UTC, willm30 commented
@ArmandoGraterol @Julianahlk Should now be fixed.

2022-09-15 00:58 UTC, ArmandoGraterol reviewed
Right now if you change from 1 safe with NFT to another with NFT there's like 1-2 seconds of delay until the NFTs are updated, meanwhile, the NFTs of the previous safe are still showing in the NFT picker dropdown. This delay may be longer in QA/prod.

We should check that the NFT picker options are also reinitialized when the value changes

2022-09-15 00:58 UTC, ArmandoGraterol commented on src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
> +import { SelectedSafe } from '~modules/dashboard/sagas/utils/safeHelpers';
Above or else :gun::sunglasses:

2022-09-15 08:40 UTC, willm30 commented
@ArmandoGraterol what's the problem? The NFT picker is reinitialised when the safe value changes.

![nfts](https://user-images.githubusercontent.com/64402732/190357261-d65893a4-7656-4f65-9d8f-946a3e7bfee5.gif)

2022-09-15 21:09 UTC, Julianahlk approved these changes
Nice job! NFTs are now updating according to which safe is selected.

2022-09-15 22:54 UTC, ArmandoGraterol commented
> @ArmandoGraterol what's the problem? The NFT picker is reinitialised when the safe value changes.

Sorry, the second paraph must've muddied what I tried to say, I'm talking about this:

[823b57f1-1646-4339-9ec8-121096e9337e.webm](https://user-images.githubusercontent.com/18473896/190522297-a80623d4-a7cf-4d51-902f-f281cfbfd39a.webm)

I can see this delay sometimes in my dev env without any throttling. I'm expecting that in QA/prod this delay will be longer, that's why I think that if you change safes then we should also display spinner until the data is updated, just in case

2022-09-16 11:12 UTC, willm30 commented
@ArmandoGraterol I see, thanks. I've added the spinner and a cache so we don't make calls after the first time.

2022-09-16 20:09 UTC, ArmandoGraterol approved these changes
Looking great to me :ok_hand: Just have a question regarding the `setIsLoadingNFTData` but after that's addressed this should be good to go

2022-09-19 12:46 UTC, willm30 commented on src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.tsx
> +          setIsLoadingNFTData(() => false);
@ArmandoGraterol Yes you're right, have changed.

2022-09-19 12:53 UTC, merged