Add multiple tokens in streaming payment
JoinColony/colonyDapp pull request #3877
Opened 2022-09-21 07:45 UTC by agnieszkajarosikloj

## Description

This PR adds multiple tokens in 'Streaming' payment type. Adding multiple funding sources has been added in this [PR](https://github.com/JoinColony/colonyDapp/pull/3825). 
Settings section is temporary (it looks like in other payment types). It will be changed to match the  design when this [PR](https://github.com/JoinColony/colonyDapp/pull/3833) is merged.
<img width="424" alt="Screenshot 2022-09-21 at 08 48 14" src="https://user-images.githubusercontent.com/91876137/191433905-3593c5eb-9cd7-414f-bef4-beeeaf84e9c1.png">

[Figma link](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5740%3A333993)

## TODO
- [ ] Add a condition to display the "Limit" form control. It should be displayed only when payment "Ends" form control in Settings section is set to "Limit is reached".
<img width="801" alt="Screenshot 2022-09-21 at 08 52 59" src="https://user-images.githubusercontent.com/91876137/191434858-15e81d0d-5319-4ef9-be66-62e807b7ae30.png">

Resolves #3813

2022-09-21 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3877) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3877) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3877) it.</sub>

2022-09-29 09:21 UTC, willm30 reviewed
It's not clear from the issue whether the token / limit comes as a pair and should be displayed together or whether we should combine all the tokens and all the limits and display them separately, like in this pr.

Would you mind confirming @arrenv?

2022-09-29 12:32 UTC, arrenv commented
> It's not clear from the issue whether the token / limit comes as a pair and should be displayed together or whether we should combine all the tokens and all the limits and display them separately, like in this pr.
> 
> Would you mind confirming @arrenv?

Yes, this is how it was designed, although it does seem as though there could be some styling improvements - https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5541%3A510520

2022-10-04 13:35 UTC, arrenv requested changes
In addition to Will's feedback, it would also be good to avoid this issue for tokens with different symbol lengths.

![ade54078-18b1-4a94-afa6-cd65221070ea](https://user-images.githubusercontent.com/33682027/193832657-ae824f97-a607-42cb-bdb1-d3df41478acf.png)

2022-10-07 07:47 UTC, agnieszkajarosikloj commented
@arrenv @willm30 I added changes. Can you re-review, please?

2022-10-07 11:12 UTC, willm30 reviewed
Thank you for addressing my comments. 

I think @arrenv intends that the token icons be aligned. I'm still noticing misalignment when the names are of different lengths. 
![limt](https://user-images.githubusercontent.com/64402732/194540105-cf43bb14-954e-49b4-96ea-e11c3c29fb56.png)

2022-10-10 09:17 UTC, willm30 approved these changes
Nice work 👍

2022-10-10 09:17 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.tsx
> +import Limit from '../Limit';
Don't forget to put styles last

2022-10-10 10:41 UTC, chinins approved these changes
All good, just please fix the imports & ids based on my comments. Thank you!

2022-10-10 10:41 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.tsx
> +
no need for this extra empty line

2022-10-10 10:41 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.tsx
> +import Limit from '../Limit';
Can you please reorder these inputs according to our system: 
move the `../` up & together without the empty line

2022-10-10 10:41 UTC, chinins commented on src/modules/dashboard/components/ExpenditurePage/Streaming/constants.ts
> +    defaultMessage: 'month',
It should be `constants` instead of `FundingSource` in all ids

2022-10-24 09:22 UTC, agnieszkajarosikloj commented
@arrenv can you re-review please?

2022-10-26 18:28 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj 

The only thing I am noticing at the moment is just to do with the alignment to make it consistent with the design. All elements as pointed out in the below screenshots should hit the right edge.

I think the issue is worse when the scroll bar appears.

This is the current app

![download (71)](https://user-images.githubusercontent.com/33682027/198106446-ebc0cd8c-5c87-4e13-9aba-95c491de9e7c.png)

This is the design:

![Screenshot 2022-10-26 201501](https://user-images.githubusercontent.com/33682027/198106452-050dbf50-b365-49ae-9ec9-d7938c97eacc.png)

![Screenshot 2022-10-26 201514](https://user-images.githubusercontent.com/33682027/198106455-139a29fd-7d32-4723-8710-71ba31f5afa0.png)

2022-10-28 18:08 UTC, jakubcolony requested changes
Nice work @agnieszkajarosikloj, everything is looking good apart from the small misalignment that Arren also spotted in his previous review:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/112586815/198703527-97abfe44-107a-47cc-a6bb-e72241f0782c.png">

2022-10-28 18:08 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Streaming/types.ts
> +  rate: Rate[];
A small suggestion to rename this to `rates` to indicate it's an array of rates rather than a single rate

2022-10-29 00:44 UTC, Julianahlk approved these changes
Very nice work @agnieszkajarosikloj.

2022-10-31 17:20 UTC, arrenv requested changes
Thanks @agnieszkajarosikloj, the left alignment is looking better. It is just the one that @jakubcolony raised again.

Also, I notice this error in the console.

![Screenshot 2022-10-31 181817](https://user-images.githubusercontent.com/33682027/199069612-f6ace5a2-cca0-4a97-8269-d2cd8f2b2f11.png)

2022-11-03 17:50 UTC, arrenv requested changes
@agnieszkajarosikloj Great, alignment is much better and the error is gone.

It looks like we have a new error though, in the additional funding sources the multiple tokens are not appearing in the limit section. As of the below screenshot.

![5bb8e438-bc6a-49e9-9ce2-9d619d6ca6f3](https://user-images.githubusercontent.com/33682027/199797367-6ec19dc9-4489-448a-b2aa-07105f734361.png)

2022-11-04 14:31 UTC, arrenv approved these changes
@agnieszkajarosikloj fixed now, working well. Thank you!

2022-11-07 10:57 UTC, merged