Add active stream with funds to claim
JoinColony/colonyDapp pull request #3888
Opened 2022-09-22 11:35 UTC by agnieszkajarosikloj

## Description

This PR adds active stream with funds to claim. UI only.  
After clicking 'Start Stream' there is an active stream with funds to claim. "Paid to date" and "Available to claim" are mocks.
State with 'no funds to claim' and other states (failed, cancelled, ...) will be added in next PRs.

<img width="444" alt="Screenshot 2022-09-22 at 13 31 34" src="https://user-images.githubusercontent.com/91876137/191735695-c65bc1b9-9a97-4404-81c3-1f7a0154a37b.png">

[Figma link](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5544%3A601229)

Resolves #3845

2022-09-22 11:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3888) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3888) it.</sub>

2022-09-29 09:05 UTC, willm30 approved these changes
LGTM 👍

2022-09-29 09:05 UTC, willm30 commented on src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.css
> +  letter-spacing: 0.1px;
We tend not to use fractions of a pixel

2022-09-30 12:44 UTC, jakubcolony approved these changes
Looks good @agnieszkajarosikloj!

2022-09-30 12:44 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.tsx
> +          [styles.alignStart]: paidToDate && paidToDate?.length > 1,
Is the optional chaining needed here?

2022-09-30 12:44 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.tsx
> +                    [styles.marginBottom]:
Wouldn't this be better solved in CSS with `first-of-type` and `last-of-type`?

2022-10-07 12:05 UTC, chinins approved these changes
Looking good!

2022-10-24 09:23 UTC, agnieszkajarosikloj commented
@arrenv I have added fixes. Can you have a look please?

2022-10-31 11:23 UTC, arrenv reviewed
@agnieszkajarosikloj I am unable to test in the same way, as you are not able to add multiple tokens anymore.

![7378c949-7bb2-4052-b1ab-b69cb8807120](https://user-images.githubusercontent.com/33682027/198997098-a3e09580-bffa-4823-a9c9-2f73ac723b2d.png)

2022-10-31 11:23 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.tsx
> +// import { useParams } from 'react-router';
Why do you need this commented out?

2022-10-31 11:23 UTC, arrenv commented on src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.tsx
> +// import { useColonyFromNameQuery } from '~data/generated';
Why do you need this commented out?

2022-11-09 19:29 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj, very nice. It is working now with multiple tokens.

It looks like we are still getting an alignment issue with the two sections though

![f4fe6e0f-4e09-44ee-b79b-dd10c8f69725](https://user-images.githubusercontent.com/33682027/200923320-6a8d4c2c-47dd-4c4c-9586-04a6640c5ce6.png)

2022-11-10 14:29 UTC, agnieszkajarosikloj commented
@arrenv I added fix. Can you have a look, please?

2022-11-17 20:08 UTC, arrenv requested changes
Thank you @agnieszkajarosikloj, looks good, except it looks like we lost the space. After adding that back in we should be good.

![download](https://user-images.githubusercontent.com/33682027/202548754-df61da23-1014-4338-82ee-a0ad88498610.png)

2022-11-18 08:09 UTC, agnieszkajarosikloj commented
@arrenv I added space. Can you have a look?

2022-11-18 09:55 UTC, arrenv approved these changes
Thank you @agnieszkajarosikloj, looks good to me!

2022-11-18 10:16 UTC, merged