added edit mode
JoinColony/colonyDapp pull request #3893
Opened 2022-09-23 14:10 UTC by agnieszkajarosikloj

## Description

This PR adds edition in locked state in streaming payment. 
When streaming payment is in locked state, user sees an 'edit' icon. After clicking on it user can change payment details (settings and funding source). 
The modal doesn't show user changes yet. Modal will be added in another PR.  Necessary changes have not yet been merged.

<img width="1158" alt="Screenshot 2022-09-23 at 16 09 03" src="https://user-images.githubusercontent.com/91876137/191979737-389f348f-bb7d-4b10-a1aa-0583df762ad1.png">

Resolves #3857

2022-09-23 14:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3893) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3893) it.</sub>

2022-09-27 08:47 UTC, jakubcolony reviewed
Looks good to me!
![image](https://user-images.githubusercontent.com/112586815/192479250-c7db1ee7-997a-4977-88bc-a8317e59876b.png)

Left a few comments/questions

2022-09-29 07:23 UTC, jakubcolony requested changes
It looks good @agnieszkajarosikloj! I noticed you renamed `state` to `stage` so I highlighted a few places where it's still using the old name. Would be great to change it all for consistency.

2022-09-29 07:23 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
>    activeStateId?: string;
A few occurrences of the old `state` name

2022-09-29 07:23 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
>    activeStateId,
A few occurrences of the old `state` name

2022-09-29 07:23 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
>    activeStateId,
A few occurrences of the old `state` name

2022-09-29 09:40 UTC, jakubcolony approved these changes
Great work!

2022-09-29 15:02 UTC, arrenv approved these changes
Looks good to me @agnieszkajarosikloj

2022-10-03 13:50 UTC, chinins approved these changes
Very good!

2022-11-07 07:52 UTC, merged