Add V2 IPFS metadata support for decisions
JoinColony/colonyDapp pull request #3919
Opened 2022-09-28 12:17 UTC by chinins

## Description

This PR adds V2 IPFS metadata support fro decisions. You need to run npm i to have an updated version of the package.

resolves #3887

2022-09-28 16:42 UTC, danbr approved these changes
Code looks good. Decision details are being retrieved (so must've been uploaded successfully) - well done.
There is a (an existing) bug that is stopping me from checking the objection details.

2022-09-28 17:03 UTC, danbr requested changes
I noticed something out of the 'new' way of accessing metadata. We should be using getAnnotationMsgFromResponse rather than calling JSON.parse directly.

2022-09-28 17:19 UTC, danbr approved these changes
I found an improvement that corrects a bug, but also good practice to use the new metadata parsing lib. Can you please replace.......
I'll approve. Well done.

2022-09-28 17:35 UTC, chinins commented on src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.tsx
> +    const details: DecisionDetails = getDecisionDetailsFromResponse(
All done!

2022-09-29 07:16 UTC, jakubcolony approved these changes
Looks good to me as far as I can tell

2022-09-29 08:03 UTC, merged