Add validation schema in streaming payment
JoinColony/colonyDapp pull request #3963
Opened 2022-10-10 11:44 UTC by agnieszkajarosikloj

## Description

This PR adds validation schema in streaming payment type.

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-10-10 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3963) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3963) it.</sub>

2022-10-14 10:14 UTC, jakubcolony requested changes
Hey @agnieszkajarosikloj, nice work with the validation!

A couple of comments:

In Figma, there's an error message under this field if it's invalid:
![image](https://user-images.githubusercontent.com/112586815/195819209-6d661412-43bf-470a-b60d-80bfb2f5f299.png)
![image](https://user-images.githubusercontent.com/112586815/195819312-cbebf3df-a482-4c3d-bf6c-baf3e6aa8d9a.png)

There seems to be no validation for limit (if you select "When limit is reached option"):
![image](https://user-images.githubusercontent.com/112586815/195819479-6cb6b7c4-69e5-40f9-b604-bab450b4fa9b.png)
I can submit the form if it's empty too

It seems that the end date colours got broken (not sure if it happened in this PR or not). They should look like this:
![image](https://user-images.githubusercontent.com/112586815/195821466-0d3f6254-13b2-42e2-9414-3cfff116d1af.png)
And now they look like this (also DatePicker colours were affected):
![image](https://user-images.githubusercontent.com/112586815/195822792-817dd073-473b-421a-b9e2-1539575772fd.png)

2022-10-17 07:18 UTC, agnieszkajarosikloj commented
@jakubcolony I have added changes. Can you re-review please?

2022-10-17 10:36 UTC, jakubcolony requested changes
Thanks for making the changes @agnieszkajarosikloj!

I spotted a few things with Limit field validation:

If you enter a character that is allowed in a number input but is not a valid number (e.g. `,`, `.`, `-`) you get an ugly-looking error:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/112586815/196150017-6b5311a9-c8d7-4192-a4db-f4be05d73292.png">
It works nicely in the Rate field however:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/112586815/196153006-04432559-d507-44fa-941f-a546b310423a.png">

If you enter something invalid in the limit field (particularly a non-numeric characters such as above), then change the "Ends" option to anything other than "Limit is reached", you can't see any errors yet the form submission is blocked:

https://user-images.githubusercontent.com/112586815/196156489-3613e8bb-3ee1-410c-9385-ca8502a770a6.mov

2022-10-18 06:52 UTC, agnieszkajarosikloj commented
@jakubcolony I have added fix. It's ready for re-review.

2022-10-18 08:25 UTC, jakubcolony approved these changes
@agnieszkajarosikloj great job, everything works nicely now:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/112586815/196374976-c8a9550c-d73a-481d-a3e8-cfc4567baa97.png">
I can also confirm the validation works if you left something over in the limit field and subsequently switched to a different "Ends" option

2022-10-18 09:23 UTC, chinins approved these changes
Looking good - great job!

2022-10-18 18:46 UTC, jakubcolony commented on src/modules/dashboard/components/ExpenditurePage/Streaming/FieldError/FieldError.tsx
> +const FieldError = ({ name }: Props) => {
I just had a thought (and I might be 100% wrong), is this component needed or could you maybe use the existing `InputStatus`?

2022-10-19 09:55 UTC, merged