Implement Insufficient Funds Error
JoinColony/colonyDapp pull request #3966
Opened 2022-10-10 13:54 UTC by joannasia

## Description

- Streaming locked fundings - on claim funds click lighten up insufficient fields

## TODO

- Add logic to mock functionality.
- Waiting for [3845-active-stream](https://github.com/JoinColony/colonyDapp/tree/feature/3845-active-stream) to be merged to the phase-3, and went it;s approved and done, then merge this branch with target branch [feature/3846-locked-funding-source](https://github.com/JoinColony/colonyDapp/tree/feature/3846-locked-funding-source) - bc right now there are changes also from active-stream branch

Resolves #3914

2022-10-10 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3966) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=3966) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: agnieszkajarosikloj<br/>:x: joannasia<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=3966) it.</sub>

2022-10-18 09:56 UTC, joannasia commented
@willm30 HI, this one is still not ready for CR, it is blocked by other MR which needs to be merged firstly :)

2022-11-18 10:20 UTC, arrenv requested changes
It is looking good. With the mock data, it does not really allow you to test it properly though. I think it would be worthwhile adding in the actual balances. How to do this is shown here - src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx

It would also help to then be able to ensure that it is identifying the right team that does not have enough funds. It seems to just mark the first one, which would seem a lot of logic is missing.

![97a9603c-ab48-46c7-876b-492f6c8240ea](https://user-images.githubusercontent.com/33682027/202679045-80e62122-82b8-4686-bbf6-b1a760d1a20c.png)

2022-11-18 22:37 UTC, ArmandoGraterol submitted a review, later dismissed
Apart from the things Mr. Arren already pointed, I noticed some small things on the code

2022-11-18 22:37 UTC, ArmandoGraterol commented on src/modules/dashboard/components/ExpenditurePage/Streaming/LockedStreaming.tsx
> +import SingleLockedFunding from './SingleLockedFunding';
This needs to go above style imports, style imports are always last.

2022-11-23 18:45 UTC, ArmandoGraterol reviewed
For ETH, it's working as expected however for the native token of the colony it's still not detecting that there are not enough funds to pay:
![FireShot Capture 755 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/203624235-ee60612d-3524-468c-ad60-2eb917526128.png)
![FireShot Capture 756 - Create Expenditure - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/203624243-ba60550d-276d-4d38-9992-d04bcce9b6e1.png)

2022-11-28 09:39 UTC, agnieszkajarosikloj commented
@arrenv @ArmandoGraterol  I have added changes. Can you have a look?

2022-12-07 19:41 UTC, arrenv approved these changes
Looking to be working much better thank you @agnieszkajarosikloj for your hard work.

I seemed to notice one issue, where the root team which had enough funds was marked with a red dot, but the value was not highlighted red.

![ca18dd0d-6b53-4bd6-9cb4-0c39bf34ae2e](https://user-images.githubusercontent.com/33682027/206279644-74923336-0e39-4f22-af35-c67ea181902a.png)

2022-12-09 10:04 UTC, chinins approved these changes
All good other than what Arren noticed.

2022-12-15 11:16 UTC, merged