Set scroll position to bottom when going back from preview
JoinColony/colonyDapp pull request #3995
Opened 2022-10-13 20:36 UTC by Julianahlk

## Description

This PR adds a small fix so when you click the "back" button from the transaction preview screen and return to the ControlSafe form the scroll position is set to the bottom instead of the top.

**New stuff** ✨

* 

**Changes** 🏗

*  

Resolves #3942

2022-10-14 11:23 UTC, willm30 requested changes
Looks to be working in most cases! However, not for Transfer NFT. I'm still seeing the behaviour of the gif I posted in the issue. When it's single tx or when Transfer NFT is the last of multiple.

2022-10-19 20:26 UTC, Julianahlk commented
> Looks to be working in most cases! However, not for Transfer NFT. I'm still seeing the behaviour of the gif I posted in the issue. When it's single tx or when Transfer NFT is the last of multiple.

Hey @willm30, After spending a few hours yesterday and today trying to find a solution for this issue and based on your suggestions, I found out that whenever a `SpinnerLoader` is rendered, the form is scrolled to display the loader which overrides calling `scrollIntoView`.  I am not sure how we could prevent the spinner loaders from doing this and I don’t know if we would want to prevent the users from seeing the loaders?

One possible solution, if there are multiple transactions, is to collapse the multiple transactions so the spinners are not displayed and therefore, making the scrollIntoView work as expected. However, this won’t work for the situation of a single transaction as it is not collapsable. 

I don’t think the setTimeout(ref.current.scrollIntoView.bind(ref.current), 0) is a viable solution because the setTimeOut has to be set to last longer than the loader in the form. 

Let me know your thoughts.

2022-10-21 08:12 UTC, willm30 commented
@Julianahlk When moving back to the NFT preview, there should be no spinner loader displayed. This has been fixed https://github.com/JoinColony/colonyDapp/pull/3998. Would you mind rebasing on this branch and seeing if that solves your problem? 

Great work by the way figuring that out. I'll have to quiz you in detail about your debugging strategy!

2022-10-25 21:32 UTC, Julianahlk commented
> @Julianahlk When moving back to the NFT preview, there should be no spinner loader displayed. This has been fixed #3998. Would you mind rebasing on this branch and seeing if that solves your problem?

Yes! I rebased off your branch in #3998 and the issue seems to haven been fixed now. Can you please test it again when you have a chance? Thanks again for your help and suggestions.

![previewbottom](https://user-images.githubusercontent.com/71563622/197886121-193d9a3d-ad35-4ca2-b357-1cc21678d71b.gif)

2022-10-26 09:53 UTC, willm30 commented
@Julianahlk I will look at not showing the loader when clicking back in the contract interaction section. It should be fine but it's a bit tricky since we're using a bunch of effects and I need to be careful I don't break anything else.

2022-10-26 12:07 UTC, willm30 commented
@Julianahlk Was easier than I expected. Can you rebase off this pr https://github.com/JoinColony/colonyDapp/pull/4030 and confirm it now works for contract interaction?

2022-10-26 13:24 UTC, willm30 commented
Note that the rinkeby safe transaction endpoint has been deprecated, which means the transfer funds and transfer nft sections will not work with a rinkeby safe. I think it's fine to not worry about these for now, given they were working previously. Should only need to confirm the contract interaction and raw tx sections

2022-10-26 14:25 UTC, willm30 commented
Alternatively, you could comment out the code that prevents you from moving to-from the preview just for testing, e.g. error components and the button's disabled logic.

2022-10-26 21:09 UTC, Julianahlk commented
> @Julianahlk Was easier than I expected. Can you rebase off this pr #4030 and confirm it now works for contract interaction?

After I rebased I can confirm all transactions are working now, specifically the contract interaction and raw transactions. 
![contractinteractionandraw](https://user-images.githubusercontent.com/71563622/198137081-47dc09e1-23e1-4863-b4ef-501e0a1e1c9f.gif)
![cnotractandraw2](https://user-images.githubusercontent.com/71563622/198137096-5780cf8f-27fb-407e-ad7b-0f2e8f2d1fea.gif)

2022-10-27 09:54 UTC, willm30 approved these changes
Working for me! Good job.

2022-10-27 13:29 UTC, chinins approved these changes
Looking good. Have you tried adding ref to DialogSection instead of span? It seems that it might work without extra span element...

2022-11-01 01:54 UTC, Julianahlk commented
> Looking good. Have you tried adding ref to DialogSection instead of span? It seems that it might work without extra span element...

@chinins I added the ref to the DialogSection. Can you please check if this is what you were thinking of? Thanks 😉.

2022-11-01 01:55 UTC, Julianahlk commented
> > Looking good. Have you tried adding ref to DialogSection instead of span? It seems that it might work without extra span element...
> 
> @chinins I added the ref to the DialogSection. Can you please check before I merge if this is what you were thinking of ? Thanks 😉.

2022-11-01 06:30 UTC, chinins commented
> @chinins I added the ref to the DialogSection. Can you please check if this is what you were thinking of? Thanks 😉.

I think that this is a better solution but I'm also open to what other people think.

2022-11-02 01:48 UTC, Julianahlk commented
> > @chinins I added the ref to the DialogSection. Can you please check if this is what you were thinking of? Thanks 😉.
> 
> I think that this is a better solution but I'm also open to what other people think.

Any thoughts @ArmandoGraterol, @willm30? :)

2022-11-02 04:54 UTC, ArmandoGraterol approved these changes
Looks good to me :) 

The only thing I would change is to wrap the export of `DialogSection` with the `forwardRef` instead of the component assignment so that it looks less convoluted but that's just my opinion

2022-11-03 17:48 UTC, ArmandoGraterol commented
> > wrap the export of `DialogSection` with the `forwardRef`
> 
> @ArmandoGraterol , I made the change. Let me know if that's what you had in mind. wink Thanks.

That's it! Thank you Juliana

2022-11-04 04:20 UTC, merged