Fix errors counter
JoinColony/colonyDapp pull request #4022
Opened 2022-10-24 08:32 UTC by agnieszkajarosikloj

## Description

This PR fixes the bug in updating error counter. The counter was not correctly updating after adding multiple funding sources. It is shown [here](https://github.com/JoinColony/colonyDapp/pull/3852#pullrequestreview-1148851724).

**New stuff** ✨

Added focus in DatePicker component after clicking "Fix it" button.

<img width="504" alt="Screenshot 2022-10-24 at 15 11 05" src="https://user-images.githubusercontent.com/91876137/197533471-782d280d-50ab-48d5-a86a-b9bb3df13039.png">

Resolves #4024

2022-10-24 08:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=4022) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=4022) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=4022) it.</sub>

2022-10-24 20:22 UTC, jakubcolony requested changes
Hey @agnieszkajarosikloj, nice work with the counter, it updates as soon as you fix an invalid field now.
I left some comments about the code but I'm also wondering if the approach of identifying the invalid fields by their order rather than something like name is the right one. I don't think it's super clear you need to set the index prop manually for it to function whereas every field already has a name prop that's also its unique identifier. 
Would be good if someone else could weigh in on that

2022-10-24 20:22 UTC, jakubcolony commented on src/modules/core/components/Fields/DatePicker/DatePicker.tsx
> +interface DatePicKerError {
```suggestion
interface DatePickerError {
```

2022-10-24 20:22 UTC, jakubcolony commented on src/modules/core/components/Fields/DatePicker/DatePicker.tsx
> +  const { inputRef: omniInputRef } = useDateTriggerFocus(index, false);
Not sure this should be called `omniInputRef`

2022-10-25 12:27 UTC, agnieszkajarosikloj commented
@jakubcolony I have removed indexes. Now names are compared.

2022-10-25 19:25 UTC, jakubcolony approved these changes
Thanks for making the changes @agnieszkajarosikloj, LGTM 👍

2022-10-26 07:17 UTC, chinins approved these changes
Very nice - good job!

2022-10-26 07:21 UTC, merged