Add instructions link to the first step of adding a safe
JoinColony/colonyDapp pull request #4093
Opened 2022-11-30 21:59 UTC by ArmandoGraterol

![FireShot Capture 758 - Actions - Colony - wonker - localhost](https://user-images.githubusercontent.com/18473896/204916979-b033d4ed-a857-4124-bcb6-3476e17295e1.png)

Resolves #4082

2022-12-01 02:49 UTC, Julianahlk approved these changes
LGTM 👍

2022-12-02 04:57 UTC, chinins approved these changes
Good to go!

2022-12-02 10:14 UTC, arrenv requested changes
Just a small typo to fix. 

EDIT: Sorry to do this but Karol made some design updates after the design review, they should be minor, you can find them here: https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=8187%3A25003&t=0tPMrXoN383cJxhi-1

![Screenshot 2022-12-02 130318](https://user-images.githubusercontent.com/33682027/205288835-f73d9eda-b983-4a35-ab64-6d741a57741f.png)

2022-12-02 10:14 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/CheckSafe.tsx
> +    defaultMessage: '<span>Important!</span>  Read instuctions before starting',
I blame myself, but there is a typo here in "instuctions", it should be "Important! Read instructions before starting"

2022-12-07 19:51 UTC, arrenv approved these changes
@ArmandoGraterol Looks good, just a couple of minor fixes.

2022-12-07 19:51 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/CheckSafe.tsx
> +    defaultMessage: '<span>Important!</span>  Read the instuctions first.',
@ArmandoGraterol We have the typo here still "instuctions: should be "instructions"

2022-12-07 19:51 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/CheckSafe.tsx
> +    defaultMessage: 'Warning!',
This text can change to "Important!" now.

2022-12-14 01:19 UTC, merged