Add incorporation modal with slides
JoinColony/colonyDapp pull request #4163
Opened 2023-01-26 22:05 UTC by agnieszkajarosikloj

## Description

This PR adds Modal with Slides, to learn about DAO incorporation. Modal consists of 3 tabs and slides. User can switch between slides by clicking on the tab or on the button. 

To test click on the New Action button and choose DAO Incorporation option.

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Added **widthAuto** prop to the Dialog core component. With this flag set to true, the dialog can be wider than 500 pixels.
<img width="1002" alt="Screenshot 2023-01-26 at 23 04 28" src="https://user-images.githubusercontent.com/91876137/214960998-1a964ebc-6769-4017-a92d-a87cae7a0275.png">

[Figma Link - Slide 1](https://www.figma.com/file/fmnKIUY0LGfEnsOOQloVVX/Korporatio?node-id=976%3A109822&t=2F2oGhbRnHI53L7V-0)
[Figma Link - Slide 2](https://www.figma.com/file/fmnKIUY0LGfEnsOOQloVVX/Korporatio?node-id=976%3A131168&t=2F2oGhbRnHI53L7V-0)
[Figma Link - Slide 3](https://www.figma.com/file/fmnKIUY0LGfEnsOOQloVVX/Korporatio?node-id=976%3A131409&t=2F2oGhbRnHI53L7V-0)

Resolves  #4154

2023-01-26 22:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=4163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyDapp?pullRequest=4163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyDapp?pullRequest=4163) it.</sub>

2023-02-01 19:17 UTC, arrenv requested changes
Thanks @agnieszkajarosikloj, this has the same issue as https://github.com/JoinColony/colonyDapp/pull/4141 regarding Incorporating being in the wrong location of the modal.

2023-02-01 19:17 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/HowPanel.tsx
> +    defaultMessage: `Korporatio will process the application and finalise the incorporate. The DAO will then be able to start benefitting for a legal DAO wrapper.<div> Step time: 15 - 20 business day
There is a type here, please change to: "Korporatio will process the application and finalize the incorporation. The DAO and contributors will then start benefiting from the legal DAO wrapper.<div> Step time: 15 - 20 business days"

2023-02-01 19:17 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/WhyPanel.tsx
> +    defaultMessage: `Setup a legal wrapper for you DAO to extend it’s functionality and help protect contributors. Incorporation is done in Panama through a partner of Colony, Korporatio. Who is spec
Please change to: "Setup a legal wrapper for you DAO to extend it’s functionality and help protect contributors. Incorporation is done in Panama through a service provided by Korporatio. Who is specifically focused on helping to support smart companies built and run on-chain."

2023-02-06 11:52 UTC, agnieszkajarosikloj commented
@arrenv  I added changes. Can you have a look?

2023-02-14 17:40 UTC, arrenv approved these changes
Just one typo on my end, but I have approved.

2023-02-14 17:40 UTC, arrenv commented on src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/WhyPanel.tsx
> +    defaultMessage: `Setup a legal wrapper for you DAO to extend it's functionality and help protect contributors. Incorporation is done in Panama through a service provided by Korporatio. Who is spe
My apologies, I have a typo in my replacement, it should be: "Setup a legal wrapper for your DAO to extend it's functionality and help protect contributors. Incorporation is done in Panama through a service provided by Korporatio. Who is specifically focused on helping to support smart companies built and run on-chain."

2023-02-23 09:15 UTC, merged